### ISSUE TITLE
CWG2531 [dcl.constexpr] Static data members redeclared as constexpr

### ISSUE THREAD

**Issue by opensdh** [cplusplus/CWG#1]
# Reference (section label)
[dcl.constexpr]/1

# Issue description
C++17 made constexpr static data members implicitly inline:

> A function or static data member declared with the constexpr or consteval specifier is implicitly an inline function or variable ([dcl.inline]).

However, that makes the following well-formed C++14 program IFNDR per [dcl.inline]/5:

```cpp
// x.hh
struct X {
  static const int x;
};
```

```cpp
// TU 1
#include"x.hh"
constexpr int X::x{};
```

```cpp
// TU 2
#include"x.hh"
int main() {return !&X::x;}
```

Current GCC and Clang do treat `X::x` as a weak symbol, but since they emit it even without an odr-use in the TU programs like this do work in practice.

# Suggested resolution
Change [dcl.constexpr]/1 as follows:

> [&hellip;] A function or static data member declared with the constexpr or consteval specifier<ins> on its first declaration</ins> is implicitly an inline function or variable ([dcl.inline]). [&hellip;]

(Functions must be declared `constexpr` on every declaration if on any, so this isn't a change for them.)

**Comment by jensmaurer** [comment]
Reflector thread: http://lists.isocpp.org/core/2022/02/12017.php

**Comment by opensdh** [comment]
It looks correct; presumably you omitted the implementation behavior purposefully.

**Comment by jensmaurer** [comment]
Yeah, I'm not sure it adds much, given that we want to outlaw the situation regardless.
