### ISSUE TITLE
[basic.lval] The divergence of treatment of the value category of a named variable in the return statement

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#100]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

````cpp
int& fun(){
   int a;
   return a;
}
````
GCC accept this example but Clang rejects it with the following diagnosis
> non-const lvalue reference to type 'int' cannot bind to a temporary of type 'int'

which seems that Clang views `a` as an xvalue. [expr.prim.id.unqual] p3 says
> The expression is an lvalue if the entity is a function, variable, structured binding, data member, or template parameter object and a prvalue otherwise ([basic.lval]);

`a` is definitely an lvalue as per this rule. However, [basic.lval] p1.3 says
> An xvalue is a glvalue that denotes an object whose resources can be reused (**usually because it is near the end of its lifetime**).

`a` is nearly at the end of its lifetime in the execution of the return statement.  From this perspective, `a` can be considered as an xvalue? It seems that the divergence of these implementations does arise from the reading of such two rules.

**Comment by villevoutilainen** [comment]
Well, presumably clang already implements https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2266r3.html

**Comment by ecatmur** [comment]
> Well, presumably clang already implements https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2266r3.html

Yes, see https://reviews.llvm.org/D99005
