### ISSUE TITLE
CWG2610 [dcl.init.aggr] definition of an aggregate is not clear for type with non-direct private/protected bases

### ISSUE THREAD

**Issue by cebowler** [cplusplus/CWG#101]
Both g++ and clang++ interpret the type `S` as an aggregate:

```
#include<type_traits>

struct B1 {};
struct B2 : private B1 {};
struct S : public B2 {};

void f() {
   static_assert(std::is_aggregate<S>::value);
}
```

Though I interpret `[dcl.init.aggr]` to be unclear:

```
An aggregate is an array or a class (Clause 11) with
...— no virtual, private, or protected base classes
```

**Comment by xmh0511** [comment]
[class.derived] p2 says
> A class B is a base class of a class D if it is a direct base class of D or a direct base class of one of D's base classes.

In your case, B1 is a base class of S, merely is not a direct base class.

**Comment by hubert-reinterpretcast** [comment]
> In your case, B1 is a base class of S, merely is not a direct base class. No defect seems to need to be clearn up.

Your interpretation matches what the wording can be taken to say; however, that is inconsistent with what implementations do. Fundamentally, there is no particular reason to disallow aggregate initialization of S (it is possible to provide an instance of B2 for the initialization).

**Comment by xmh0511** [comment]
> Fundamentally, there is no particular reason to disallow aggregate initialization of S (it is possible to provide an instance of B2 for the initialization).

Aha, it is reasonable that the rule should only apply to these direct base classes, which is similar to the restriction for the non-static data member of an aggregate.

**Comment by jensmaurer** [comment]
CWG2610

**Comment by jensmaurer** [comment]
@cebowler , if you want a less acronym-y variant of your name in the core issue, please advise.

**Comment by cebowler** [comment]
> @cebowler , if you want a less acronym-y variant of your name in the core issue, please advise.

"Chris Bowler" or similar would be appreciated.  Thank-you.

**Comment by jensmaurer** [comment]
Done.
