### ISSUE TITLE
CWG2611 [temp.variadic] Missing parentheses in expansion of fold-expression could cause syntactic reinterpretation

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/CWG#109]
Full name of submitter (unless configured in github; will be published with the issue): 

Reference (section label): temp.variadic

Link to reflector thread (if any):

Issue description:

[temp.variadic]p10 expands a fold-expression (including its enclosing parentheses) to an unparenthesized expression. If interpreted literally, this could result in reassociation and misinterpretation of the expression. For example, given:

```
template<int ...N> int k = 2 * (... + N);
```

... `k<1, 2, 3>` is specified as expanding to `int k<1, 2, 3> = 2 * 1 + (2 + 3);` resulting in a value of 7 rather than the intended value of 12.

Suggested resolution:

Add parentheses to the expansions. Change in [temp.variadic]p10:

> The instantiation of a *fold-expression* produces:
> - <ins>`(`</ins>`((`E<sub>1</sub> *op* E<sub>2</sub>`)` *op* ⋯`)` *op* E<sub>N</sub><ins>`)`</ins> for a unary left fold,
> - <ins>`(`</ins>E<sub>1</sub> *op* `(`⋯ *op* `(`E<sub>N−1</sub> *op* E<sub>N</sub>`))`<ins>`)`</ins> for a unary right fold,
> - <ins>`(`</ins>`(((`E *op* E<sub>1</sub>`)` *op* E<sub>2</sub>`)` *op* ⋯`)` *op* E<sub>N</sub><ins>`)`</ins> for a binary left fold, and
> - <ins>`(`</ins>E<sub>1</sub> *op* `(`⋯ *op* `(`E<sub>N−1</sub> *op* `(`E<sub>N</sub> *op* E`)))`<ins>`)`</ins> for a binary right fold.
> [...]

**Comment by jensmaurer** [comment]
CWG2611
