### ISSUE TITLE
[special] Unclear if two constructors are of the same kind if default arguments are present

### ISSUE THREAD

**Issue by royjacobson** [cplusplus/CWG#110]
Full name of submitter (unless configured in github; will be published with the issue): 
Roy Jacobson

Reference (section label):
11.4.4 [special]

Link to reflector thread (if any): not that I know of

Issue description:

Shafik Yaghmour raised the issue of whether such copy constructors:

```
struct A {
  A(const A&);
  A(const A&, int x = 1);
};
```
qualify as having 'the same kind' for the purpose of computing special member methods eligibility.

The standard says that
>   Two special member functions are of the same kind if [...] or they are both copy or move constructors with the same first parameter type, or [...]

According to this, such two copy constructors are of the same kind. However, this means that it is required to compare constraints of functions with different parameter lists, which is inconsistent with the regular overload resolution process.

In practice, such code is unlikely to be written - the call to the constructor will be ambiguous anyway.

Suggested resolution:
To explicitly note that it is intended that the constructors are of the same kind, or modify the behavior.

**Comment by jensmaurer** [comment]
In general, constraints refer to template parameters, so the shape of the function parameters is generally uninteresting for constraint checking. But maybe you can build an interesting example using `decltype` and a trailing _requires-clause_. Care to create a scary example?

**Comment by royjacobson** [comment]
But according to the wording added in P2113R0 functions with different parameter lists should not be sorted w.r.t to constraints. So I still think that's a slight inconsistency.

I'll think about some more complex cases, it's maybe possible to do something weird with templated default constructors.

**Comment by jensmaurer** [comment]
The wording added with P2113R0 expanded the definition of "more specialized" for partial ordering purposes. In one of the bullets, it refers to [temp.constr.order].

Unrelated to that, 11.4.4 [special] also refers to [temp.constr.order] for a different purpose. Note that 11.4.4 expressly does not talk about "more specialized" or "partial ordering" in general. I understand that "more specialized" happens to invoke [temp.constr.order] only for same function parameter lists, but the definition in [temp.constr.order] appears to talk about subsumption only, which is an abstract analysis of the (normalized) constraints, unrelated to the function parameter list.

I guess I'd like to see an example where the definition in [temp.constr.order] breaks down for the "not the same function parameter list" case. I'm not seeing any.

**Comment by royjacobson** [comment]
So, here's a (very artificial) example of what I thought is a bit problematic with the current wording. Consider

```C++
#include <type_traits>
#include <algorithm>

template <class T>
struct ConditionallyTriviallyCopyable {
  ConditionallyTriviallyCopyable() = default;
  ConditionallyTriviallyCopyable(const ConditionallyTriviallyCopyable&, T t = T{});
  ConditionallyTriviallyCopyable(const ConditionallyTriviallyCopyable&)
    requires (std::is_trivially_copyable_v<T>) = default;
  T t;
};

void f1(ConditionallyTriviallyCopyable<int> src) {
  ConditionallyTriviallyCopyable<int> target(src);
}

void f2(ConditionallyTriviallyCopyable<int> src) {
  ConditionallyTriviallyCopyable<int> target;
  std::copy(&src, 1 + &src, &target);
}
```

Under the 11.4.4 [special] rules `ConditionallyTriviallyCopyable<int>` is trivially copyable, even though its copy constructor cannot even be called: when calling the copy constructor the compiler does overload resolution that considers none of those more specialized than the other, so we get ambiguous overloads.

So then because the STL does the "replace copy constructor with mem{cpy,mov} if type is trivially copyable" optimization f2 fails to compile, but f2 will work just fine.

**Comment by jensmaurer** [comment]
I agree that `ConditionallyTriviallyCopyable<int>` is trivially copyable per the current rules, even if no copy constructor can ever be invoked due to ambiguity.

I'm still not seeing a defect here; the wording we have (note the emphasis on "first parameter") was deliberately crafted for a case like yours. There are other situations where we make copies of classes even though we might not be able to invoke a copy constructor, e.g. [class.temporary] p3.

**Comment by royjacobson** [comment]
Thanks, that answers my question.
