### ISSUE TITLE
CWG2616 [stmt.stmt] "Occur in" is not clear enough

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#118]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[stmt.break] says
> The break statement shall **occur only in** an iteration-statement or a switch statement and causes termination of the smallest enclosing iteration-statement or switch statement; 

[stmt.cont] says
> The continue statement shall occur only in an iteration-statement   

[stmt.label] says
> Case labels and default labels shall occur only in switch statements.

Consider this example
````cpp
for(int i = 0; i< 10; ++i){
   auto f = [](){
      break; // #1
   };
}
````
Isn't the statement `break` not **occurring in** the *iteration-statement*? However, such usage is rejected by implementations, their diagnoses are
>  'break' statement not in loop or switch statement 

Similar issues are that the `case` label in a compound-statement of a lambda expression that occurs in a switch statement, `label` in a compound-statement of a lambda expression that occurs in a function, and `continue` in ...

However, "occurs in" is ok for this case
````cpp
for(int i = 0; i< 10; ++i){
    try{continue;}catch(...){break;}
}
````

We may have to give a special rule for these statements that can appear in a `compound-statement` that occurs in particular statements such as `switch` and `iteration-statement` but the compound-statement shall not be the component of a lambda expression.

**Comment by jensmaurer** [comment]
See CWG2616

**Comment by xmh0511** [comment]
> [CWG2616](https://cplusplus.github.io/CWG/issues/2616.html)

It seems that "enclose" still has the same problem.
````cpp
for(auto i = 0;i<10;i++){
    break; // enclosed by the for
   {
      break; // still enclosed by the for
     {
          break; // the same as above
      }
     [](){
          break; //  has the same reason as above 
      };
   }
}
````
We should explicitly say that the **intervening statement** between such as `break` and `for` shall not be the *compound-statement* of a lambda expression.

**Comment by jensmaurer** [comment]
"enclosed" is defined in [stmt.pre] p3

The definition was explicitly crafted to exclude lambda-expressions. Could you please explain why you believe that doesn't work?

**Comment by xmh0511** [comment]
>  Could you please explain why you believe that doesn't work?
````cpp
for(int i = 0; i<10; i++) /* S1 */ 
{ // S2
  [](){  // this compound-statement is `S4`
     break;  // S5
  };  // the whole expression-statement is `S3`
}
````
`S2` is a substatement of `S1` hence `S1` encloses `S2`, `S3` is a substatement of `S2` therefore `S2` encloses `S3`, therefore `S1` encloses `S3`. Since `S4` is not a substatement of `S3`, although `S4` encloses `S5`, `S3` does not enclose `S4` therefore it still does not enclose `S5`. Oh, "enclose" can work here since we have defined the meaning of  "enclose" for statements, it's my oversight.
