### ISSUE TITLE
CWG2568 [class.protected] Defaulted comparisons with protected base class

### ISSUE THREAD

**Issue by brevzin** [cplusplus/CWG#119]
Reference (section label): [class.compare.default]

Link to reflector thread (if any): https://lists.isocpp.org/core/2022/04/12289.php

Issue description:

This is currently rejected by all implementations:

```cpp
struct B {
protected:
    bool operator==(B const&) const = default;
};

struct D : B {
    int i;
    bool operator==(D const&) const = defulat;
};

bool check(D const& x, D const& y) {
    return x == y;
}
```

This is, logically, a reasonable thing to write that should not run afoul of access issues. But it is rejected because we talk about `D`'s defaulted comparison as comparing two `B` subobjects, in a way that looks like (as [Cameron points out](https://lists.isocpp.org/ext/2022/04/18986.php)):

```cpp
struct D : B {
    int i;
    bool operator==(D const& other) const
    {
        return static_cast<B const&>(*this) == static_cast<B const&>(other)
            && i == other.i;
    }
};
```

which is ill-formed. But in this context, we're not just comparing _any_ `B`s, we're comparing _specifically_ the `B`s that we should be allowed to compare. This is... expressible in code for `==` being a member function, but not for it being a non-member:

```cpp
    bool operator==(D const& other) const {
        return this->B::operator==((B const&)other)
            && i == other.i;
    }
```

But I don't think we actually have to worry about not having syntax for the non-member case, since the implementation could just do the right thing?

**Comment by jensmaurer** [comment]
Can you offer suggested wording to fix this?

**Comment by brevzin** [comment]
I'm not sure. We currently have this in [class.compare.default]/5:

> The direct base class subobjects of C, in the order of their declaration in the [base-specifier-list](https://eel.is/c++draft/class.derived.general#nt:base-specifier-list) of C, followed by the non-static data members of C, in the order of their declaration in the [member-specification](https://eel.is/c++draft/class.mem.general#nt:member-specification) of C, form a list of subobjects[.](https://eel.is/c++draft/class.compare#default-5.sentence-1) In that list, any subobject of array type is recursively expanded to the sequence of its elements, in the order of increasing subscript[.](https://eel.is/c++draft/class.compare#default-5.sentence-2) Let xi be an lvalue denoting the ith element in the expanded list of subobjects for an object x (of length n), where xi is formed by a sequence of derived-to-base conversions ([[over.best.ics]](https://eel.is/c++draft/over.best.ics)), class member access expressions ([[expr.ref]](https://eel.is/c++draft/expr.ref)), and array subscript expressions ([[expr.sub]](https://eel.is/c++draft/expr.sub)) applied to x[.](https://eel.is/c++draft/class.compare#default-5.sentence-3)

and then this in [class.eq]/2:

> A defaulted == operator function for a class C is defined as deleted unless, for each xi in the expanded list of subobjects for an object x of type C, xi == xi is usable ([[class.compare.default]](https://eel.is/c++draft/class.compare#default))[.](https://eel.is/c++draft/class.compare#class.eq-2.sentence-1)

and this in [class.protected]/1:

> If the access is to form a pointer to member ([[expr.unary.op]](https://eel.is/c++draft/expr.unary.op)), the [nested-name-specifier](https://eel.is/c++draft/expr.prim.id.qual#nt:nested-name-specifier) shall denote C or a class derived from C[.](https://eel.is/c++draft/class#protected-1.sentence-3) All other accesses involve a (possibly implicit) object expression ([[expr.ref]](https://eel.is/c++draft/expr.ref))[.](https://eel.is/c++draft/class#protected-1.sentence-4) In this case, the class of the object expression shall be C or a class derived from C[.](https://eel.is/c++draft/class#protected-1.sentence-5)


Maybe [class.protected]/1 needs to carve out an exception for, in the case of a defaulted comparison operator, where the subobject is a base class subobject of `C`?

**Comment by brevzin** [comment]
Actually this:

> the class of the object expression is a base class of C and occurs in the context of a defaulted comparison operator function for C

is an incorrect suggestion, since if we had a situation like:

```cpp
struct D : B {
    int i;
    B b;
    bool operator==(D const&) const = default;
};
```

then while comparing the `B` base class subobjects should be allowed, comparing the `B` _member_ subobjects should not. That's clearly outside the scope of `protected`.

Perhaps closer to:

> the object expression is evaluating a comparison function of two base class subobjects of `C` in the context of a defaulted comparison function for `C`.

**Comment by jensmaurer** [comment]
This is CWG2568.
