### ISSUE TITLE
CWG2601 [except.ctor] stack unwinding for arrray object with the dynamic storage duration

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#120]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

Consider this example
````cpp
struct A{
    A(int v):id(v){
        if(v == 3){
            throw 0;
        }
    }
    ~A(){
        std::cout<<"destroy A "<<id<<std::endl;
    }
    int id;
};
int main(){
     try{
     auto ptr = new A[3]{0,1,3};
   }catch(...){
       std::cout<<"caught\n";
   }
}
````
Implementations invoke the destructors for the class objects whose ids are `0`, `1`. However, [except.ctor] is not clear to cover this point. 

First, [except.ctor] p2 is only for objects with automatic storage duration. [except.ctor] p3 seems to be only defined for objects with class type. 
> If the initialization or destruction of an object other than by delegating constructor is terminated by an exception, the destructor is invoked for each of the object's direct subobjects and,

This part seems to cover the array object, however, the last part says
> Such destruction is sequenced before entering a handler of the function-try-block of the **constructor or destructor**, if any.  

It makes the meaning vague. Does [except.ctor] p2 cover array object? If the intent is, why we didn't say it as the following?  
> Such destruction is sequenced before entering a handler of the **try-block** or the function-try-block of the **constructor or destructor**(if any)    

to cover the case where the exception that occurs in the initialization of an array object which doesn't have a constructor and can appear in a try-block context. 

***
Moreover, "whose initialization has completed" cross-references to [dcl.init], however, that clause didn't give the definition of how an initialization is considered complete.

**Comment by jensmaurer** [comment]
"If any" means "ignore this if there is none". Obviously, an array doesn't have a constructor or destructor, so this sequencing rule just is to be ignored (in this case).

**Comment by xmh0511** [comment]
>  Obviously, an array doesn't have a constructor or destructor, so this sequencing rule just is to be ignored (in this case).

Should [except.ctor] cover the case for sequencing rule in try-block? That is, the destruction of any subobject is sequenced before entering the handle of the try-block. 

Since there is no obvious rule says that the destruction of the subobject when the exception occurs in the initialization of a containing object is part of the full-expression of the initialization. Moreover, [expr.new] p26 says
> If any part of the object initialization described above terminates by throwing an exception and a suitable deallocation function can be found, **the deallocation function is called** to free the memory in which the object was being constructed,

This rule, at best, that implies the invocation of the deallocation function is part of the full-expresssion of the **new-expression**. 

We should have a clear rule that says the destruction of subobjects and deallocation function invocation(if any) are sequenced before entering the handle(of try-block or function-try-block).

**Comment by jensmaurer** [comment]
Could you please put separate concerns into separate issues?

The array situation that you were concerned about at the top of this issue is addressed by CWG2601.
