### ISSUE TITLE
CWG2622 [implimits] p2.3 The mentioned type is not complete

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#125]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[implimits] p2.3 says
> Pointer ([dcl.ptr]), array ([dcl.array]), and function ([dcl.fct]) declarators (in any combination) **modifying a class, arithmetic, or incomplete type** in a **declaration** [256].

Consider this example:
````cpp
using T = void();
T *** ... *** ptr = 0;

using U = int B::*;
U *** ... *** ptr1 = 0;

T arr[N0][N1] ... [N];
````  
In this **declaration**, the pointer declarator is used to **modify** the type `T`, according to [dcl.ptr], where `T` is the complete *decl-specifier-seq*  in the declaration, If I understand the meaning of "modify" correctly. However, `T` is not a class, arithmetic, or incomplete type, it's a **function type**.

### Suggested resolution
We should supplement the types the modification can apply to make this recommendation cover these cases.

**Comment by jensmaurer** [comment]
CWG2622
