### ISSUE TITLE
CWG2632 [intro.defs] Adding definition for the term "user-declared"

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#127]
Full name of submitter (unless configured in github; will be published with the issue): Anoop Rana

Reference (section label): [intro.defs]

Link to reflector thread (if any): [thread1](https://lists.isocpp.org/std-discussion/2022/09/1792.php), [thread2](https://stackoverflow.com/questions/73625024/is-the-term-user-declared-constructor-ambiguous-or-is-it-self-explanatory#comment130019103_73625024) and [thread3](https://stackoverflow.com/questions/73624520/whats-the-definition-of-user-declared-constructor-in-the-c-standard#comment130012905_73624520).

**Issue description**: Currently the C++ standard does not formally define the term **user-declared** while it uses it at various places in the standard. For example, this term is used when talking about `user-declared constructors`, `user-declared namespace` and so on. Upon looking at its wide usage and also that some [experienced users think that](https://stackoverflow.com/questions/73624520/whats-the-definition-of-user-declared-constructor-in-the-c-standard#comment130012905_73624520) the term is not self-explanatory and even ambiguous at times, I think that the standard should formally provide a definition for it.  

<h3>Suggested resolution:</h3>

In [intro.defs], we can add something along the lines of:

> **User-declared**
>
>  A declaration is said to be *user-declared* if it is explicitly written by the user(whoever that user might be). 
> [Example 1:
> ```
> struct C
> {
>     C() = default; //user-declared constructor
> };
> ```
> end example]

**Comment by jensmaurer** [comment]
CWG2632

**Comment by frederick-vs-ja** [comment]
CWG3148 seems to supersede this.
