### ISSUE TITLE
[class.member.lookup] p1 should be moved to [basic.lookup.general]

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#128]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[class.member.lookup] p1 says
> **A search in a scope X for a name N from a program point P is a single search in X for N from P** unless X is the scope of a class or class template T, in which case the following steps define the result of the search.

The emphasized part that defines the concept "a search in a scope" should be a common sense for any kind of lookup that depends on this concept. Such as [basic.lookup.unqual]
> An unqualified search in a scope S from a program point P includes the results of **searches from P in** 

In the current, the definition of "search" is placed in [class.member.lookup], which looks like it only applies to the name of an entity that is a **member** of a namespace or class.   

### Suggested resolution
Move [class.member.lookup] p1 to the place after [basic.lookup.general] p3 where p3 defines the meaning of the single search, as a general rule, the new paragraph would be like
> A search in a scope X for a name N from a program point P is a single search in X for N from P. Unless `X` is the scope of a class or class template `T`, in which case [class.member.lookup] defines the result of the search.

This makes more sense.

**Comment by jensmaurer** [comment]
@opensdh, that sounds plausible; suggested wording for the "general" section would be:

> A search in a scope X other than that of a class or class template for a name N from a program point P is a single search in X for N from P.

and in class.member.lookup:

> A search in a scope X of a class or class template T for a name N from a program point P is a single search in X for N from P.

**Comment by jensmaurer** [comment]
Agreed with @opensdh; there is no actual defect here.

If you disagree, feel free to file an NB comment for the ongoing CD ballot for C++23.

**Comment by xmh0511** [comment]
> the section headings imply a restriction on the applicability of a term

It sometimes does. As we have discussed in other issues. The heading restricts the extent of the application of the rule.

**Comment by opensdh** [comment]
> It sometimes does. As we have discussed in other issues.

There's still no possibility of misreading this, since you either fail to find a definition for "search" or get the right answer because there's no class involved anyway.

> The heading restricts the extent of the application of the rule. I would say, for instance, the rule defined in [class.derived.general] is talking about "Derived classes".

What rule do you mean?  There certainly are places where we say something like "In this subclause, _x_ means&hellip;" ([basic.life]/11, [over.built]/2, and [concepts.equality]/1, at least), but I don't see any definition in that subclause that seems to be "implicitly scoped".

**Comment by xmh0511** [comment]
> What rule do you mean?

As @jensmaurer has said in his https://github.com/cplusplus/CWG/issues/137#issuecomment-1250206236. The heading is less or more to imply which stuff the rule defined in the **subclause** applies to. Such as [xxx.pre], or [xxx.general] implies the rules defined in these clauses are common rules for `xxx`. Conversely, the rules that are defined in such as [basic.lookup.qual] basically only apply to the qualified names.
