### ISSUE TITLE
CWG2541 [module.unit] linkage declarations, module purview and module attachment

### ISSUE THREAD

**Issue by urnathan** [cplusplus/CWG#13]
Submitter: Nathan Sidwell

Reference: module.unit

Link to reflector thread:  https://lists.isocpp.org/core/2022/02/11983.php

Issue description:
The interaction between linkage declarations [dcl.link] and named or global module purview and attachment [module.unit] is confusing.  The addition of linkage declarations attaching their contents to the global module is not fully integrated into the wording and examples would also help.

1) module purview and attachment are not necessarily the same. This is never explicitly mentioned.

2) [module.unit]/7 explicitly calls out replaceable allocation and deallocation functions as being (implicitly) attached to the global module.  This is unnecessary.

3) [basic.start.main] specifies that there is a main function in the global namespace, but only in para 3 do we specify that not attaching it to the global module is ill-formed.

Suggested resolution:

a) Address #2 by removing that requirement.  Users that need to replace such functions in named-module purview should use a linkage declaration.

b) Address #1 with an example (with thanks to Mathias Stearn), in [module.unit]:

```
  // Source "foo.cc"
  export module Foo;
   void Quux (); // # module-linkage, attached to Foo
   extern "C++" {
     // Both Bar and Baz have external-linkage and global module attachment
     export void Bar (); // # nameable by importers
     void Baz (); // #nameable in Foo's purview
   }
```
  Both Bar and Baz are also nameable from TUs that have a redeclaration.  For instance:
```
  // Legacy header "foo.h"
  extern "C++" void Bar ();
```
```
  // Legacy header "foo-internal.h"
  extern "C++" void Baz ();
```
[Mathias's example had Bar & Baz calling Quux, IMHO that's unnecessary in this example.]

c) Address 3 by inserting the words 'attached to the global module' to [basic.start.main]/1

d) [optional] Remove [basic.start.main]'s restriction of prohibiting main to appear in a linkage declaration.  Thus permitting named-modules to provide main in their purview.

e) [optional] Add a cross reference from [dcl.link] to [module.global.frag]

**Comment by jensmaurer** [comment]
CWG2541

Leaving out "d"; this feels like a (small) extension that should best be addressed to LEWG.

Leaving out "e"; I'm not seeing the connection.
