### ISSUE TITLE
CWG2629 [stmt.switch] p2 Condition as floating-point variable

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#130]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[stmt.switch] p2 says
> The condition shall be of integral type, enumeration type, or class type.

Consider this example
````cpp
switch(float v = 0){
   case 0:;
}
````
[stmt.pre] p4, p5 explicitly say
> The rules for conditions apply both to selection-statements and to the for and while statements ([stmt.iter]). 
>
> The value of a condition that is an initialized declaration in a switch statement is the value of the declared variable if it has integral or enumeration type, **or of that variable implicitly converted to integral or enumeration type otherwise**.
>
> **The value of the condition** will be referred to as simply **“the condition”** where the usage is unambiguous.  

First, a floating-point value can be **implicitly** converted to an integral value as per [conv.fpint]. In this case, the initial type of the condition is `float`, hence 
> The value of a condition that is an initialized declaration in a switch statement is the value of that variable implicitly converted to integral or enumeration type otherwise.

applies to this case. "the condition" in [stmt.switch] p2 refers to "the value of the condition", according to the above rule. However, this case is rejected by [implementations](https://godbolt.org/z/j8hx9Ev66). 

I think [stmt.pre] p4 and p5 intend to cover this case. [stmt.switch] p2 says may be more clear if we say
> The (possibly converted)condition shall be of integral type, enumeration type, or class type.

**Comment by jensmaurer** [comment]
CWG2629
