### ISSUE TITLE
CWG2626 [basic.fundamental] The base-2 representation vs. value representation for integer types

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#131]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[basic.fundamental] p3 says
> For each value x of a signed integer type, the value of the corresponding unsigned integer type congruent to x modulo 2<sup>N</sup> has the same value of corresponding bits in **its value representation**.  

[basic.fundamental] p5 says
> Each value x of an unsigned integer type with width N has a unique representation x= x<sub>0</sub>2<sup>0</sup> + x<sub>1</sub>2<sup>1</sup> + ... + x<sub>N-1</sub>2<sup>N-1</sup> where each coefficient x<sub>i</sub> is either 0 or 1; this is called the base-2 representation of x.  
>
> **The base-2 representation of a value of signed integer type is the base-2 representation of the congruent value of the corresponding unsigned integer type**.

Such two phrases(the first and the latest) essentially imply they convey the same things. In other words, they indicate that the value representation of an integer type is represented by the particular sequence of the coefficients in the base-2 representation of the value. In short, each bit in the value representation is the value of the corresponding coefficient.  

### Suggested resolution
Should we make the implication apparent in the clause? Consider the big/little endian, we may say
> The value representation of a value of an integer type is an implementation-defined sequence of bits whose values are taken from the coefficients of the base-2 representation of that value.

**Comment by languagelawyer** [comment]
> Such two phrases(the first and the latest) essentially imply they convey the same things

No. Value representation ≠ representation of a value

> In other words, they indicate that the value representation of an integer type is represented by the particular sequence of the coefficients in the base-2 representation of the value. In short, each bit in the value representation is the value of the corresponding coefficient.

Where does this follow from?

Imagine a hypothetical implementation which, for any integer value, stores all `0`s in the value representation of an object (of signed or unsigned type) having such value. This satisfy [basic.fundamental]/3, but
> each bit in the value representation is the value of the corresponding coefficient

is not true.

**Comment by xmh0511** [comment]
> Where does this follow from?

The note implies this point, see[ basic.fundamental.footnote/34. The defintion of two's complement representation, which is defined in wikipedia, see https://en.wikipedia.org/wiki/Two%27s_complement 

***
> Imagine a hypothetical implementation which, for any integer value, stores all 0s in the value representation of an object (of signed or unsigned type) having such value. 

I would say how the value can be distincted if the value representations of any integer values are filling with `0`？Moreover, for the unary operator `~`, we define the result as the ones' complement of that value, how the result would be if the value reprensentation is not clear? 

I think we should define a set for the value representation for the integer type rather than let it be as a infinitly possible set.

**Comment by languagelawyer** [comment]
> I would say how the value can be distincted if the value representations of any integer values are filling with `0`？

How can different pointer values with the same value representation be distincted?

> Moreover, for the unary operator `~`, we define the result as the ones' complement of that value

Yes, of the value, not of the value representation of an object. `~` does not work with objects and their representations.

**Comment by xmh0511** [comment]
> Yes, of the value, not of the value representation of an object. ~ does not work with objects and their representations.

Either one's or two's complement, they all concern what the values of the bits of the value are. First, we say
> the signed and unsigned integer value that are congruent has the same value representation

Then, we implies the value representation is relevant to two's complement. The defintion of two's complement specify how a value is represented in a N-bits system. The standard then says
> The value representation of a signed or unsigned integer type comprises N bits, where N is the respective width. 

So, why do not admit the value of bits in the value representation is relevant to the coefficient of the base-2 representation of the value?

**Comment by jensmaurer** [comment]
We're intentionally not saying anything about the bit representation of integers (as might be observed by looking at the object representation); we just talk about certain properties of the types.

The current wording, I believe, makes an `unsigned int` representation valid that uniquely encodes each value, but with a seemingly random bit pattern (think AES-encrypted or so). Changing this would need a paper to argue the merits of adding further restrictions, I think.

**Comment by xmh0511** [comment]
@jensmaurer @languagelawyer 
What I am concerned here is, the most expression evaluations that touch "bits" evaluation does not need to concern what the concrete value representations are. Since we have defined two abstract concepts in this document: congruent relation, and base-2 representation. 

For example, such as [Bitwise AND operator], the result of the operation is only based on the coefficients of the base-2 representations of the operands. Assume, we have four-bits integer type, the signed version is named as `I4` and the unsigned version is named as `U4`
````cpp
I4 i = 1;
I4 i2 = 2;
````
the congruent concept specify that the value of type `U4` that corresponds to the value `1` of type `I4` is `1`, and for `i2`, the corresponding value is `2`. Now, we can get the base-2 representation fo these values,  `1`'s base-2 representation is `0, 0, 0, 1` while `2` is `0,0,1,0`. Hence, the resulting base-2 representation of the result of `i & i2` is `0,0,0,0`. The resulting base-2 representation corresponds to the `0` of `U4`, and then **congruent relation** can let us figure out the signed version of the value, which is still `0`. In this process, we do not need to touch any value representation. 

**HOWEVER**, the ones' complementation does not have a abstract function of the calculation for the result of `~`, and this evaluation does need to touch the value representation

**Comment by jensmaurer** [comment]
There might be room for a bit of rigor in the description (along the lines of bit-AND), but the idea is that ones' complement takes the base-2 representation of the operand value and switches each coefficient valued 0 to 1 and vice versa.

**Comment by xmh0511** [comment]
> the idea is that ones' complement takes the base-2 representation of the operand value and switches each coefficient valued 0 to 1 and vice versa.

This is the way we should take to reword [expr.unary.op] p10. For all bit operation, we should take the manner as [Bitwise AND operator] have done(i.e use an abstract descirption) to avoid use the term that would touch the bits(value representation). 

### Suggested resolution
> The operand of ~ shall have integral or unscoped enumeration type. Integral promotions are performed, if necessary. Given the coefficients x<sub>i</sub> of the base-2 representation of the (possible promoted) operands x, the coefficient r<sub>i</sub>of the base-2 representation of the result r is `1` if x<sub>i</sub> is `0`, and `0` otherwise. The type of the result is the type of the (possible promoted) operand.

For other bits operation, we should check whether they use the term that is not defined in this manner, and change them if they are.

**Comment by jensmaurer** [comment]
CWG2626

**Comment by xmh0511** [comment]
Thanks. I would add them here if there were. It seems there is no more bit operation definition in the document.
