### ISSUE TITLE
CWG2627 [dcl.init.list] Bit-fields and narrowing conversions

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/CWG#132]
Full name of submitter (unless configured in github; will be published with the issue): Tim Song

Reference (section label): [dcl.init.list]

Link to reflector thread (if any): https://lists.isocpp.org/core/2021/08/11319.php

Issue description:

The rules for narrowing conversions between integer types in [dcl.init.list]/7 do not take bit-fieldness into account, only the type:

> A narrowing conversionis an implicit conversion
> - [...]
> - from an integer type or unscoped enumeration type to an integer type that cannot represent all the values of the original type, except where the source is a constant expression whose value after integral promotions will fit into the target type

 This leads to surprising behavior in various cases. For instance, because integral promotions can convert a `long long` bitfield into an `int` ([conv.prom]/5 - the intended meaning seems clear even though a "prvalue for an integral bit-field" isn't really a thing), such a promotion would be narrowing. For example:

```cpp
#include <compare>

struct C {
    long long i : 8;
};

void f() {
    C x{1}, y{2};
    x.i <=> y.i; // ill-formed: narrowing conversion required ([expr.spaceship]/4)
}
```

And similarly in initialization:

```cpp
struct A1 { long long i : 8; };
struct A2 { long long i; };
struct B { int n; };
A1 a1;
A2 a2;
B b1 = {a1.i}; // #1
B b2 = {a2.i}; // #2
```

There is [reportedly implementation divergence](https://lists.isocpp.org/core/2021/08/11328.php) in the handling of this example.

We could carve out integer promotions specifically from narrowing conversions, but that leads to odd results in cases like

```cpp
// assuming int and long are 32-bits and long long is 64 bits
int i{a1.i}; // OK, integral promotion -> not narrowing
long j{a1.i}; // error
```

Suggested resolution:

Relax the rule in [dcl.init.list]/7.4 so that if the source is a bit-field whose width is less than that of its type (or the underlying type, for an enumeration), "the original type" is considered to be a hypothetical extended integer type with the same signedness whose width is equal to the width of the bit-field.

**Comment by jensmaurer** [comment]
CWG2627

**Comment by JohelEGP** [comment]
The date seems wrong:
> Date: 2021-08-13

**Comment by languagelawyer** [comment]
@JohelEGP it is based on the reflector thread date
