### ISSUE TITLE
CWG2628 [over.match.class.deduct] Implicit CTAD guides should propagate constraints.

### ISSUE THREAD

**Issue by royjacobson** [cplusplus/CWG#133]
Full name of submitter: Roy Jacobson

Reference (section label): [over.match.class.deduct]p1.1

Link to reflector thread: Maybe?

Issue description:
When performing CTAD, implicit deduction guides are created that don't inherit the constraints of the original constructors.
GCC and MSVC implement CTAD and _do_ inherit the constraints, but Clang does not.

Relevant Clang issue: https://github.com/llvm/llvm-project/issues/43829

Suggested resolution:

Add a bullet item with 'with the same trailing requires-clause as the constructor, if it has one' (or equivalent).

**Comment by jensmaurer** [comment]
CWG2628

**Comment by royjacobson** [comment]
Thanks Jens!
