### ISSUE TITLE
[class.mem.general] p26 The permission of reading an inactive member

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#135]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

In the current draft, the only case where we can access an object that is a member of a union and is inactive is specified in [class.mem.general] p26, which says
> In a standard-layout union with an active member of struct type T1, it is permitted to read a non-static data member m of another union member of struct type T2 provided m is part of the common initial sequence of T1 and T2; the behavior is as if the corresponding member of T1 were nominated.

The corresponding illustrate example is
````cpp
struct T1 { int a, b; };
struct T2 { int c; double d; };
union U { T1 t1; T2 t2; };
int f() {
  U u = { { 1, 2 } };   // active member is t1
  return u.t2.c;        // OK, as if u.t1.a were nominated
}
````
However, consider this example
````cpp
struct T1 { int a, b; };
union U { T1 t1;  int c;};
U u = {{1,2}}; // active member is t1
auto c = u.c; // undefined 
````
It could arguably say the access to `U::c` should have the resemble behavior to that of the first case. However, IIUC, the second case is just UB since it is not the case where the current [class.mem.general] p26 try to specify, nor the lifetime of `U::c` is begun. 

Should [class.mem.general] p26 cover the second case?

**Comment by jensmaurer** [comment]
Why should it? The existing wording is pretty clear (you need two struct types), and I think C has the same restrictions.

I'm not seeing a defect here; if you want a change, consider writing a paper and submitting it to WG21.

**Comment by xmh0511** [comment]
It might not be a big change. In the current wording, the two standard-layout struct members of a standard-layout union object are pointer-interconvertible, and their first non-static-data members are pointer-interconvertible, hence the above rule can work(it's the essence of why). 

Resemble, the non-static data member of the union that is a layout-compatible type with the first non-static of the other struct member of the union should also be so. 

***
In general, it is not the wording defect, it is an extension of the wording.

**Comment by jensmaurer** [comment]
This directly affects the ability to optimize on pointer-interconvertibility.

> In general, it is not the wording defect, it is an extension of the wording.

So, please write a paper if you want that feature, including rationale why you think it's beneficial for uses of C++.
