### ISSUE TITLE
[class.derived] Whether the order in which the non-static members are allocated is unspecified?

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#137]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[class.derived.general] p5 says
> The order in which the base class subobjects are allocated in the most derived object ([intro.object]) is unspecified.

How about the order of the allocation of direct non-static member subobjects of a class object? It is vague, since [class.derived.general] p5 can imply two options
> 1. Only the allocation order of all base class subobjects themself are unspecified. In other words, the direct non-static member of the most derived object is specified as in the declaration order.
> 2.  The base class subobjects can/may place into the intervening of two non-static data members, which results in the allocation order of the non-static data member of the most derived object being also unspecified.

We have explicitly mentioned the allocation order of the base class subobjects, however, we didn't say anything about the non-static data member subobjects. This arises the room of the suppose for how the allocation order of the latter is.

**Comment by jensmaurer** [comment]
That's specified by [expr.rel] p4.2:

> If two pointers point to different non-static data members of the same object, or to subobjects of such members, recursively, the pointer to the later declared member is required to compare greater ...

I'm not seeing a defect here. And yes, some interleaving of non-static data members and base class subobjects seems a valid implementation strategy.

**Comment by xmh0511** [comment]
So, [expr.rel] p4.2 implies that: The allocation order of non-static data member subobjects always obeys the order of their declaration order while the allocation order of each base class subobjects is unspecified to each other. 

I think we should cross-reference to [expr.rel] p4.2 in [class.derived.general] to implicitly the allocation order of the non-static data member subobjects, or we explicitly specify them with a brief wording
> The order in which the non-static data member subobjects are allocated in the most derived object ([intro.object]) is as the declared order. 

Then [expr.rel] p4.2 specify the concrete relationship.

**Comment by jensmaurer** [comment]
No, we avoid normative duplication in the standard as much as possible. That gets out-of-sync pretty quickly.

Second, [class.derived.general] is talking about "Derived classes", as its heading implies, so there is no reason to expect utterances about non-static data members here.

Again, I'm not seeing a defect here.

**Comment by xmh0511** [comment]
Ah, a similar note is located in https://eel.is/c++draft/class.mem#general-20
