### ISSUE TITLE
NAD [expr.type.conv] Could constrained auto be used in function-style cast?

### ISSUE THREAD

**Issue by cpplearner** [cplusplus/CWG#14]
Full name of submitter (unless configured in github; will be published with the issue): S. B. Tam

Reference (section label): [expr.type.conv]

Link to reflector thread (if any):

Issue description:
It is unclear whether a *placeholder-type-specifier* in the form of `Concept auto` is a valid type specifier in a function-style cast.

    template<class T>
    concept C = true;
    auto x = auto(1);     // valid (P0849R8)
    auto y = C auto(1);   // Is this valid?
    auto z = C<> auto(2); // What about this?

Intuitively, neither `C auto(1)` nor `C<> auto(2)` should be allowed, since in general, a function-style cast can only have a single-word type name.

Suggested resolution:

Change [expr.type.conv] paragraph 1 as follows:

> Otherwise, if the type contains a placeholder type, <ins>the type shall be `auto` and shall not contain a *type-constraint*, and</ins> it is replaced by the type determined by placeholder type deduction ([[dcl.type.auto.deduct]](http://eel.is/c++draft/dcl.type.auto.deduct))[.](http://eel.is/c++draft/expr.type.conv#1.sentence-3)

**Comment by cpplearner** [comment]
At the time of writing, GCC trunk permits `C auto(1)` but rejects `C<> auto(1)`: https://godbolt.org/z/YbWsTPMo9

**Comment by jensmaurer** [comment]
I think [dcl.type.auto.deduct] p2.3 is clear here:

> For an explicit type conversion (7.6.1.4), T is the specified type, which shall be auto.

In other places in the bulleted list, we say "T shall be either type-constraint opt decltype(auto) or cv type-constraint opt auto.", so it's obvious that the examples above are ill-formed.
