### ISSUE TITLE
CWG2672 [temp.arg.deduct] Lambda body SFINAE is still required, contrary to intent and note 

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/CWG#143]
Full name of submitter (unless configured in github; will be published with the issue): 

Reference (section label): temp.arg.deduct

Link to reflector thread (if any):

Issue description:

[temp.arg.deduct]p9:

> A lambda-expression appearing in a function type or a template parameter is not considered part of the immediate context for the purposes of template argument deduction.
> [Note 7: The intent is to avoid requiring implementations to deal with substitution failure involving arbitrary statements.

But the intent in the note is not satisfied by the wording. A lambda appearing in a requires-expression has the same concerns as one in a function signature and is not covered here.

Suggested resolution:

Change the rule to say that substitution into the body of a lambda is never in the immediate context of substitution into the lambda-expression and move the rule somewhere more general.

**Comment by jensmaurer** [comment]
CWG2672
