### ISSUE TITLE
CWG2661 [class.mem] missing disambiguation rule for pure-specifier vs brace-or-equal-initializer

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/CWG#146]
## Issue description

We have an ambiguous grammar for member-declarator:

> _member-declarator:_
> - _declarator virt-specifier-seq_[opt] _pure-specifier_[opt]
> - _declarator brace-or-equal-initializer_[opt]

> _pure-specifier:_
> - `=` `0`

The primary issue here is that `foo = 0` matches both _member-declarator_ productions. Secondarily, a _declarator_ by itself is also ambiguous, but that's easily fixed by removing the [opt] from the second production and doesn't lead to two different program interpretations.

We then have:

> 11. A _brace-or-equal-initializer_ shall appear only in the declaration of a data member.
> 13. A _pure-specifier_ shall be used only in the declaration of a virtual function that is not a friend declaration.

... which make the two mutually exclusive but isn't itself a disambiguation rule.

Utterances like `virtual FunctionType f = 0;` are valid, so we can't disambiguate based on the syntactic form of the _declarator_. In practice, implementations disambiguate based on whether _decl-specifier-seq declarator_ declares a name with function type, and I believe that is the intent based on the rule in [temp.spec] that acquiring a function type through a dependent type is ill-formed.

### Option 1

Add a disambiguation rule, such as:

> The token sequence `=` `0` is treated as a _pure-specifier_ if the type of the _declarator-id_ [dcl.meaning.general] is a function type, and is otherwise treated as a _brace-or-equal-initializer_. [*Note*: If the member declaration acquires a function type through template instantiation, the program is ill-formed; see [temp.spec.general].]

... and remove the other ambiguity with a grammar change:

> _member-declarator:_
> - _declarator virt-specifier-seq_[opt] _pure-specifier_[opt]
> - _declarator brace-or-equal-initializer_<del>[opt]</del>

### Option 2

Change the grammar to remove the ambiguity entirely:

> _member-declarator:_
> - _declarator virt-specifier-seq_[opt] <del>_pure-specifier_[opt]</del> <ins>_brace-or-equal-initializer_[opt]</ins>
> - <del>_declarator_ _brace-or-equal-initializer_[opt]</del>

> <del>_pure-specifier:_</del>
> - <del>`=` `0`</del>

> 11. A _brace-or-equal-initializer_ shall appear only in the declaration of a data member<ins> or a function</ins>. [...]
> 13. [...] . <ins>A _brace-or-equal-initializer_ appearing in the declaration of a member function shall be of the form `=` `0`, and is called a _pure-specifier_</ins>. A _pure-specifier_ shall be used only in the declaration of a virtual function that is not a friend declaration.

Either way, this seems borderline editorial to me.

**Comment by jensmaurer** [comment]
CWG2661
