### ISSUE TITLE
[except.spec] Circular dependency between except.spec and expr.unary.noexcept and potentially unclear clauses

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#151]
Full name of submitter (unless configured in github; will be published with the issue): Anoop Rana

Reference (section label): [except.spec], [expr.unary.noexcept]

Link to reflector thread (if any):

Issue description: While reading [except.spec] and [expr.unary.noexcept], I think that there is potential circular dependency between the two clauses. In particular, [expr.unary.noexcept#3](https://timsong-cpp.github.io/cppwp/n4861/expr.unary.noexcept#3) says:

> The result of the noexcept operator is true unless the [expression](https://timsong-cpp.github.io/cppwp/n4861/expr.comma#nt:expression) is potentially-throwing ([[except.spec]](https://timsong-cpp.github.io/cppwp/n4861/except.spec))[.](https://timsong-cpp.github.io/cppwp/n4861/expr.unary.noexcept#3.sentence-1).

Suppose we have:

```
struct C
{
     void f() noexcept(noexcept(5))
     {
     }
};
```
Now according to the above quoted statement [expr.unary.noexcept#3], the result of the predicate `noexcept(5)` (that uses the noexcept operator) will be `true`  unless the expression `5` is potentially-throwing. The important point to note here is that "result of `noexcept(5)` depends on whether `5` is potentially-throwing".

Now to find out whether or not expression `5` is potentially-throwing we've to look up to [except.spec] which says that:

> **If the predicate is false, the function has** a [potentially-throwing exception specification](https://timsong-cpp.github.io/cppwp/n4861/except.spec#def:potentially-throwing,exception_specification), otherwise it has a [non-throwing exception specification](https://timsong-cpp.github.io/cppwp/n4861/except.spec#def:non-throwing_exception_specification)[.](https://timsong-cpp.github.io/cppwp/n4861/except.spec#1.sentence-2).

(emphasis mine)

The important point to note here is that according to the above quoted [except.spec], "whether **function** `f` has potentially-throwing exception specification depends on whether the predicate `noexcept(5)` is false". But that is what we wanted to find out. In particular, our aim was to find out the result of `noexcept(5)` for which we had to find out if the expression `5` is potentially-throwing or not. But [except.spec] bring us back to where we started by saying that if predicate is false the function has potentially throwing excepetion specification. 

Essentially, we end up where we started. Also, one more thing that I noted is that [expr.unary.noexcept] talks about "expression" while [except.talks] about "function". That is, in our example we have the expression `5` for which we want to find out if it is potentially-throwing or not. But the function is `f` which will have a potentially-throwing exception specification if the predicate `noexcept(5)` is false. But [except.spec] does not say how to find out whether the **expression** `5` is potentially-throwing. All it says is that the function will have a potentially-throwing exception specification if the predicate is false.

<h3>Suggested resolution</h3>

The wording should be change accordingly to remove the circular dependency(if there really is any) and also to make this part of the language more clear.

**Comment by JohelEGP** [comment]
> [3](https://eel.is/c++draft/expr.unary.noexcept#3)
[#](http://github.com/Eelis/draft/tree/c72033915672dc6eca50e9dc7fc06c507e062609/source/expressions.tex#L5034)
The result of the noexcept operator is true unless the [expression](https://eel.is/c++draft/expr.comma#nt:expression) is potentially-throwing ([[except.spec]](https://eel.is/c++draft/except.spec))[.](https://eel.is/c++draft/expr.unary.noexcept#3.sentence-1)

> [6](https://eel.is/c++draft/except.spec#6)
[#](http://github.com/Eelis/draft/tree/c72033915672dc6eca50e9dc7fc06c507e062609/source/exceptions.tex#L796)
An expression E is [potentially-throwing](https://eel.is/c++draft/except.spec#def:potentially-throwing,expression) if

`5` is not potentially-throwing.



> > **If the predicate is false, the function has** a [potentially-throwing exception specification](https://timsong-cpp.github.io/cppwp/n4861/except.spec#def:potentially-throwing,exception_specification), otherwise it has a [non-throwing exception specification](https://timsong-cpp.github.io/cppwp/n4861/except.spec#def:non-throwing_exception_specification)[.](https://timsong-cpp.github.io/cppwp/n4861/except.spec#1.sentence-2).
> 
> (emphasis mine)

This is about the _noexcept-specifier_, not the _noexcept-expression_.

**Comment by ranaanoop** [comment]
@JohelEGP Thanks for correcting me. When i clicked on the link given at the end of [expr.unary.noexcept#3](https://timsong-cpp.github.io/cppwp/n4861/expr.unary.noexcept#3), i got redirected to [expect.spec](https://timsong-cpp.github.io/cppwp/n4861/except.spec) instead of more direct [expect.spec#6](https://timsong-cpp.github.io/cppwp/n4861/except.spec#6) and the main mistake that I made was that I did not read the full [expcet.spec], otherwise this would've been tirvial. 

Thanks again
