### ISSUE TITLE
[expr.const] Disjunction disqualifies `construct_at` of non-active member

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/CWG#155]
Full name of submitter (unless configured in github; will be published with the issue): 

Reference (section label): [expr.const]

Link to reflector thread (if any):

Issue description:
> [6](https://eel.is/c++draft/expr.const#6)
[#](http://github.com/Eelis/draft/tree/b8cf1c46fd8fe0b5d509afc8944f2a2b3d29a515/source/expressions.tex#L7562)
[[...]](https://eel.is/c++draft/expr.const#6.sentence-1)
Similarly, the evaluation of a call to std​::​construct_­at or std​::​ranges​::​construct_­at ([[specialized.construct]](https://eel.is/c++draft/specialized.construct)) does not disqualify E from being a core constant expression unless the first argument, of type T*, does not point to storage allocated with std​::​allocator<T> or to an object whose lifetime began within the evaluation of E, or the evaluation of the underlying constructor call disqualifies E from being a core constant expression[.](https://eel.is/c++draft/expr.const#6.sentence-2)

According to the wording, this code should be ill-formed, but implementations accept it: https://compiler-explorer.com/z/f8Tjx8EK5.

```C++
#include <memory>
union num {
  int i;
  constexpr num() {
    std::construct_at(&i); // the first argument does not point
    // to storage allocated with std​::​allocator<T> or
    // to an object whose lifetime began within the evaluation of E
  }
};
static_assert(num{}.i == 0);
```

Suggested resolution:

**Comment by jensmaurer** [comment]
The wording in question here was removed. @JohelEGP , is this still relevant?
