### ISSUE TITLE
CWG2630 [expr.ref] p4 use "shall" or "requires"

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#162]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[expr.ref] p4 says
> The class type **shall be complete** unless the class member access appears in the definition of that class.

We only define whether a class is complete if the point and the class definition appear in the same TU and the point is after the closing `}`, or the point is in the  complete-class context of the class. 

This remains the gas that if the point and the class definition are in different TUs? For example:
````cpp
// file a
export module A;
export class X{
   void fun(){}
};

// file b
import A;
A a;
a.fun(); // A shall be complete
````
Name lookup is well-defined for this case. However, the class member access needs the class type to be complete, we have nothing wording clearly specifies this point. 

[basic.def.odr] p13 says
> A definition of a class **shall be reachable** in every context in which the class is used in a way that **requires the class type to be complete**.

This issue is similar to https://github.com/cplusplus/CWG/issues/81 but it is more clear here. "shall" means we impose the requirement to the case, the construct will be ill-formed if the rule is violated. Using "shall" requires us clearly know whether the requirement is satisfied, unfortunately in this case, whether the type is complete or not is not clear. Even though, whether the construct(class member access) is well-formed or not can be determined by [basic.def.odr] p13 since we clearly define whether the class definition is reachable at that point. However, [expr.ref] p4 also uses "shall" and in this case, the violation is not determinable. 

### Suggested resolution
We may use "requires" in place of "shall", and in all contexts we **requires** complete class type are regulated by [basic.def.odr] p13. For example, change [expr.ref] p4  to
> The class type **is required to be complete** unless the class member access appears in the definition of that class.

If the class definition is not reachable in the context we require the class to be complete, the construct will violate [basic.def.odr] p13 and therefore will be ill-formed.

**Comment by jensmaurer** [comment]
I think CWG2630 will address this.

**Comment by xmh0511** [comment]
Shall we change the suggested resolution to
> A class(template) is regarded as complete **at a point P** if the class(template) definition is reachable at P, or P is within the complete-class context of the class(template); otherwise it is regarded as incomplete within its own class member-specification.
