### ISSUE TITLE
CWG1436 [cpp.cond] Constant expressions? In MY preprocessor? I think not.

### ISSUE THREAD

**Issue by AaronBallman** [cplusplus/CWG#17]
Full name of submitter: Aaron Ballman

Reference (section label): [cpp.cond]

Link to reflector thread (if any): N/A

Issue description: [cpp.cond]p12 says, "The resulting tokens comprise the controlling constant expression which is evaluated according to the rules of [expr.const] using arithmetic that has at least the ranges specified in [support.limits]. For the purposes of this token conversion and evaluation all signed and unsigned integer types act as if they have the same representation as, respectively, intmax_­t or uintmax_­t. This includes interpreting character-literals according to the rules in [lex.ccon]. Each subexpression with type bool is subjected to integral promotion before processing continues."

I don't think this captures the intent quite right because we don't really expect the preprocessor to be able to handle arbitrary constant expressions. e.g., we don't expect this to preprocess:
```
template <typename Ty>
constexpr Ty func() { return static_cast<Ty>(12); }

#if func<unsigned int>() == 12u
#endif
```
Suggested resolution: I think we need to make it more clear as to what kinds of constant expressions are allowed in a preprocessor conditional and which ones are not. I don't see implementation divergence here, but this came up when trying to determine whether a UDL could be used in the preprocessor conditional or not given that the UDL is `constexpr`, which started seeming more reasonable from the current wording in [cpp.cond].

**Comment by jensmaurer** [comment]
Frankly, I think the standard is very clear here if you read [cpp.cond] from start to end. In particular, p11 says

> After all replacements due to macro expansion and evaluations of defined-macro-expressions, has-include-expressions, and has-attribute-expressions have been performed, all remaining identifiers and keywords, except for true and false, are replaced with the pp-number 0, and then each preprocessing token is converted into a token.

So, the snippet you posted above is actually equivalent to
```
#if 0<0 0>() == 12u
#endif
```
and that's certainly a nicely ill-formed constant expression.

For UDLs (only), I think the situation less clear, because they survive the treatment and do end up in the resulting constant expression unharmed. So, this latter part does warrant a core issue.

**Comment by AaronBallman** [comment]
Fair point about the fact that identifiers and keywords are replaced with pp-number 0, but consider floating-point constants as another example where this isn't well specified (same issue exists in C):
```
#if 1.2 == 1.2
#endif
```

**Comment by jensmaurer** [comment]
Net result: duplicate of CWG1436

I'll remove the drafting assignment, because it seems to be stale.

**Comment by AaronBallman** [comment]
Ah, thank you!

**Comment by pmor13** [comment]
Related: https://stackoverflow.com/q/70943108/1778275.
