### ISSUE TITLE
[temp.param] Proposal to allow multiple template parameters packs of different types

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#174]
Full name of submitter (unless configured in github; will be published with the issue): Anoop Rana

Reference (section label): [temp.param]

Link to reflector thread (if any):

<h4>Issue description:</h4>

Currently [temp.param#14] makes the following program ill-formed:
```
//----------------------vvvv--------------------->note U Is a nontype template parameter pack
template<typename... T, bool... U> void f()
{

}
int main()
{
    f<int, double, true, false>(); //ill-formed as per current wording
}
```
This program should be well-formed because the underlying type of `T` and `U` are different. One is a template type parameter pack while the other is a template non-type parameter pack so that the last two arguments `true` and `false` can't possibly be matched with `T`. In other words, **there is no way that `T` can consume all the four template arguments since the last two arguments are `true` and `false`.** This means that the user expects(and a compiler can also distinguish) that `T` will be matched only with the first two arguments `int` and `double` while `U` with the remaining two arguments. 

So we aim to solve this issue when the underlying type of the parameters are different. The pdf document describing the proposal is attached at the end of this issue where things are discussed in more detail.

<h3>Suggested resolution:</h3>

<h4>Change 1</h4>

The first change is to add a separate clause in the standard which more or less have the same meaning as saying that a template parameter pack `T` consumes all the explicitly provided template argument(s) **of the same kind** until an argument of different kind is encountered so that the template parameter `U` **directly** following `T` will match with the remaining argument(s) with the same process as described above. That is, this process will repeat for each parameter(s). The qualifier "directly" in the previous sentence means that there is no parameter in between `T` and `U` . In case there are no more arguments left after matching explicitly provided argument(s) with a  parameter, the remaining template parameter packs(if any) will be empty.

This essentially means that `template<typename... T, typename... U> void f(); f<int, int>();` will not be well-formed with `T={int,int}, U={}`.  We also note that we observer [compiler divergenece](https://godbolt.org/z/r784r11s5) here as gcc and clang already accepts [this](https://godbolt.org/z/r784r11s5) program while msvc rejects it. Since a template parameter pack like `U` can be an empty pack, it makes sense to make the [program](https://godbolt.org/z/r784r11s5) well-formed with `T={int,int}, U={}`.

Similarly, `template<typename... T, bool... U> void f(); f<int,int>();` is accepted by gcc and clang but rejected by msvc. [Compiler divergence](https://godbolt.org/z/EnEddGn59).

<h4>Change 2</h4>

Second change that will be needed is in [temp.param#14] that will make `template<typename... T, bool... U> void f(); f<int,int, true, false>();` well-formed. The first change(addition of separate clause) highly influence this second change. Maybe even the addition of separate clause can be done in [temp.param#14].

Below is the attached proposal in pdf format.
[DnnnnR0.pdf](https://github.com/cplusplus/CWG/files/10028421/DnnnnR0.pdf)

**Comment by jensmaurer** [comment]
The status quo wording seems clear; this is a request for an extension. Feel free to submit a proposal to the Evolution Working Group for due consideration.
