### ISSUE TITLE
CWG2551 [basic.life] such a pointer/glvalue refers to allocated storage

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/CWG#19]
**Full name of submitter** (unless configured in github; will be published with the issue):  Andrey Erokhin

**Reference (section label)**: [basic.life]

**Link to reflector thread (if any)**: https://github.com/cplusplus/draft/issues/4153

**Issue description**:
[basic.life] has normative wording like «such a pointer/glvalue refers to allocated storage»
It is unclear what does this mean (when we know about http://eel.is/c++draft/basic.compound#3.sentence-8 and http://eel.is/c++draft/basic.lval#def:glvalue)

**Suggested resolution**:

**Comment by jensmaurer** [comment]
CWG2551

**Comment by languagelawyer** [comment]
> An out-of-lifetime object does not exist

May I ask you to remove this?

As for the issue description and the suggested resolution, I don't think there are any problems with pointer value or glvalue definitions. I don't even see how the suggested resolution affects the (absence of the) meaning of «refers to allocated storage». I'd just remove the sentences with «refers to allocated storage» from [basic.life].

**Comment by jensmaurer** [comment]
> May I ask you to remove this?

Removed that sentence.

> As for the issue description and the suggested resolution, I don't think there are any problems with pointer value or glvalue definitions.

What would the kind of pointer value be for the out-of-lifetime objects we're talking about here, per [basic.life] p3?

And "refers to allocated storage" does seem to have a meaning; you can placement-new over the storage in the "provides storage" sense.

**Comment by languagelawyer** [comment]
> What would the kind of pointer value be for the out-of-lifetime objects we're talking about here, per [basic.life] p3?

What's wrong with «pointer to object»?

> And "refers to allocated storage" does seem to have a meaning; you can placement-new over the storage in the "provides storage" sense.

«Pointer to object» should be enough. Yes, there is a tiny problem with «represents the address», http://eel.is/c++draft/basic.compound#footnote-36 ought to be normative.

**Comment by jensmaurer** [comment]
Ok.

So, your only concern is that "refers to allocated storage" has no normative meaning and should thus be struck; any properties we might want in this area are already covered by the definition of "object".

**Comment by jensmaurer** [comment]
Fixed: CWG2551

**Comment by languagelawyer** [comment]
Has just discovered www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#1853, but I see that CWG1853 already mentions CWG2251…
