### ISSUE TITLE
[intro.defs] Adding definition for the term "built-in type"

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#192]
Full name of submitter (unless configured in github; will be published with the issue): Anoop Rana

Reference (section label): [intro.defs]

Link to reflector thread (if any):

**Issue description:** Currently the C++ standard does not formally define the term **built-in type** while it uses that term at various places in the [standard](https://open-std.org/jtc1/sc22/wg21/docs/papers/2020/n4861.pdf).

<h3>Suggested resolution:</h3>

Either change the term "built in type" in [concepts.object#2](https://timsong-cpp.github.io/cppwp/n4861/concepts.object#2) and [concepts.object#3](https://timsong-cpp.github.io/cppwp/n4861/concepts.object#3) to the term "fundamental type"

Or 

Add a new entry in [intro.defs] saying something like:

> **built-in type[defns.builtin.type]**
> 
> Same as fundamental type.

**Comment by JohelEGP** [comment]
Searching the WD from the beginning, the use of "built-in" as an adjective for "type" occurs only in two consecutive notes in the library side at [concept.totallyordered]. The language side has no such use.

**Comment by ranaanoop** [comment]
@jensmaurer I can find 2 uses in [this draft](https://open-std.org/jtc1/sc22/wg21/docs/papers/2020/n4861.pdf). Both are used in notes given in [concepts.object](https://timsong-cpp.github.io/cppwp/n4861/concepts.object).

Here is the [first use](https://timsong-cpp.github.io/cppwp/n4861/concepts.object#2).

Here is the [second use](https://timsong-cpp.github.io/cppwp/n4861/concepts.object#3)

Also I agree that instead of introducing a synonym it's better(or atleast easy) to replace "built in type" with "fundamental type". 
**I've updated my suggested resolution accordingly.**

**Comment by JohelEGP** [comment]
That's where I found them (I gave the wrong stable label). This should be an [editorial issue](https://github.com/cplusplus/draft#c-standard-draft-sources) instead.

**Comment by ranaanoop** [comment]
@JohelEGP I've made the [pull request 6012](https://github.com/cplusplus/draft/pull/6012).
