### ISSUE TITLE
CWG2689 [basic.fundamental] Clarifying that std::nullptr_t is a fundamental type even though it is defined in header cstddef by changing the non-normative note to a clause

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#193]
Full name of submitter (unless configured in github; will be published with the issue): Anoop Rana

Reference (section label): [basic.fundamental] 

Link to reflector thread (if any):

**Issue description:**

Currently [basic.fundamental#14](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#14) says:
> A **value** of type `std​::​nullptr_­t` is a [null pointer constant](https://timsong-cpp.github.io/cppwp/n4861/conv.ptr#def:null_pointer_constant)[.](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#14.sentence-1) Such **values** participate in the pointer and the pointer-to-member conversions ([[conv.ptr]](https://timsong-cpp.github.io/cppwp/n4861/conv.ptr), [[conv.mem]](https://timsong-cpp.github.io/cppwp/n4861/conv.mem))[.](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#14.sentence-2) `sizeof(std​::​nullptr_­t)` shall be equal to sizeof(void*)[.](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#14.sentence-3)

(emphasis mine)

Note the emphasis on the term "value". My point is that the above clause seems to be mainly talking about "value" instead of "type" while it should be mainly talking about the "type" `std::nullptr_t` which is defined in [cstddef.syn](https://timsong-cpp.github.io/cppwp/n4861/cstddef.syn) inside namespace `std`.

This matters because [basic.fundamental#15](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#15) says:
> The **types** described in this subclause are called [fundamental types](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#def:fundamental_type)[.](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#15.sentence-1) [ [Note](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#15.note-1): Even if the implementation defines two or more fundamental types to have the same value representation, they are nevertheless different types[.](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#15.sentence-2) — end note ]

(emphasis mine)

Again note that the [above clause](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#15) talks about "types described" instead of "types of values described" in this subclause. Though this doesn't seem to be a big problem as one can assume that "types described" is the same as "types of value described", I suggest that we should instead move atleast part of the [non-normative note](https://timsong-cpp.github.io/cppwp/n4861/lex.nullptr) to [basic.fundamental#14](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#14).

<h3>Suggested resolution:</h3>

Change [basic.fundamental#14](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#14) to as highlighted(in bold) below:

> **`std​::​nullptr_­t` is a distinct type that is neither a pointer type nor a pointer-to-member type**. A value of type `std​::​nullptr_­t` is a [null pointer constant](https://timsong-cpp.github.io/cppwp/n4861/conv.ptr#def:null_pointer_constant)[.](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#14.sentence-1) Such values participate in the pointer and the pointer-to-member conversions ([[conv.ptr]](https://timsong-cpp.github.io/cppwp/n4861/conv.ptr), [[conv.mem]](https://timsong-cpp.github.io/cppwp/n4861/conv.mem))[.](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#14.sentence-2) `sizeof(std​::​nullptr_­t)` shall be equal to `sizeof(void*`)[.](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#14.sentence-3). 

As we can see the note from [lex.nullptr](https://timsong-cpp.github.io/cppwp/n4861/lex.nullptr) is taken and is added into [basic.fundamental#14](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#14).

---

Moroever if needed a separate note can be added into [basic.fundamental#15](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#15) saying as highlighted(in bold) below:

> The types described in this subclause are called [fundamental types](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#def:fundamental_type)[.](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#15.sentence-1)
[ [Note](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#15.note-1): Even if the implementation defines two or more fundamental types to have the same value representation, they are nevertheless different types[.](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#15.sentence-2) — end note ] 
 **[Note: Even though `std::nullptr_t` is declared in `cstddef`, it is still considered a fundamental type --end note]**

Note that the above added note is the second change that this issue suggests.

**Comment by ranaanoop** [comment]
@JohelEGP I've removed that reiteration. Check out my updated suggested resolution. Thanks for pointing that out.

**Comment by frederick-vs-ja** [comment]
`std::nullptr_t` is not _defined_ in any header. In C++, a (non-template) typedef-name is merely declared and never defined ([[basic.def]/2.9](https://eel.is/c++draft/basic.def#2.9), [[basic.def]/2.10](https://eel.is/c++draft/basic.def#2.10)).

**Comment by ranaanoop** [comment]
> `std::nullptr_t` is not _defined_ in any header. In C++, a (non-template) typedef-name is merely declared and never defined ([[basic.def]/2.9](https://eel.is/c++draft/basic.def#2.9), [[basic.def]/2.10](https://eel.is/c++draft/basic.def#2.10)).

@frederick-vs-ja No, I think you missed [cstddef.syn](https://timsong-cpp.github.io/cppwp/n4861/cstddef.syn) which says:
> Header `<cstddef>` synopsis 
>
> ```
> namespace std {
>  using nullptr_­t = decltype(nullptr);
>
>  //other things here
> }
> ```

**Comment by ranaanoop** [comment]
@frederick-vs-ja I've changed the term "defined" to "declared" in my 2nd suggestion(which is a note).

**Comment by AlanVoore** [comment]
@jensmaurer I think the intention(of the current standard's wording) is to have `std::nullptr_t` a fundamental type(aka built in type). So this issue's resolution does make sense. Although I've seen people saying that `std::nullptr_t` is not a fundamental type. The additions mentioned here will help clarify the same.

**Comment by frederick-vs-ja** [comment]
I guess the original issue can be resolved as editorial (i.e., a PR to [cplusplus/draft](https://github.com/cplusplus/draft) is suitable).

However, I'm afraid that the currently proposed note is problematic. A parallel statement - "Even though `std::int32_t` is declared in `<cstdint>`, it is still considered a fundamental type." - seems confusing. I believe that a fundamental type itself is not declared anywhere, only the typedef-name denoting it can be declared.

BTW, there seems another issue - _cv_-qualified versions of `std::nullptr_t` are not mentioned in [basic.fundamental].

**Comment by ranaanoop** [comment]
> I'm not seeing a need to normatively say that `std::nullptr_t` is not a pointer or pointer-to-member type. **The former is a fundamental type, the latter are compound types**.

@jensmaurer  AFAIK both are fundamental types as per [basic.compound-1.3](https://timsong-cpp.github.io/cppwp/n4861/basic.types#basic.compound-1.3) and [basic.compound-1.8](https://timsong-cpp.github.io/cppwp/n4861/basic.types#basic.compound-1.8). Moreover, [cppreference's documentation on types](https://en.cppreference.com/w/cpp/language/type) also says that `std::nullptr_t` is a fundamental type and both a pointer as well as a pointer-to-member type are compound types. 

Perhaps I missed something here or you overlooked this?

**Comment by jensmaurer** [comment]
@ranaanoop , I feel there is a communication disconnect.

I said that cv `std::nullptr_t` is a fundamental type. I also said that a pointer type is a compound type, as is a pointer-to-member type. By virtue of having different type categories (fundamental vs. compound), a `std::nullptr_t` can't possibly be a pointer type or a pointer-to-member type, and thus we don't have to repeat that explicitly normatively. The note we have elsewhere is good enough.

**Comment by ranaanoop** [comment]
@jensmaurer Oh, I see when you said "former" I though you mean "pointer" and when you said "latter" you meant "pointer to member" but that was not the case. In particular, by "former" you actually meant `std::nullptr_t` and "latter" was for "pointer as well as pointer to member". I misread that comment of yours. Thanks for clarifying. 

Regards
