### ISSUE TITLE
[lex.ccon] and [lex.string] Defining basic-c-char and basic-s-char to be not `new-line` is insufficient

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#196]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[basic-s-char](https://eel.is/c++draft/lex.string#nt:basic-s-char) says
> any member of the translation character set except the U+0022 quotation mark, U+005c reverse solidus, or **new-line character**

where the `new-line` character is specified in [lex.charset] p2  

 ||character|glyph|
|----|-----|----|
|U+000a | line feed | new-line|

Consider this example, the following will generate an issue code
````cpp
#include <iostream>
#include <string>
#include <fstream>
int main(){
	std::ofstream file("./out.cpp");
	auto s = "#include <iostream>\n#include <string>\nint main(){\n auto s =\"a\rb\";  \n}";
	file << s;
}
````
So, running this code will get the `out.cpp`, which will look like
````cpp
#include <iostream>
#include <string>
int main(){
 auto s ="a
b";  
}
````
This code is rejected by major implementations, which report the diagnosis:
````
out.cpp:4:10: warning: missing terminating '"' character [-Winvalid-pp-token]
 auto s ="a
         ^
out.cpp:4:10: error: expected expression
````
As shown in the first code, we ensure that the character between `a` and `b` in the *s-char-sequence* of `s` is not a *new-line* but a carriage return. 

This issue may be fixed by P2348R2.

**Comment by tahonermann** [comment]
_new-line_ is a grammar term defined in [\[cpp.pre\]](http://eel.is/c++draft/cpp.pre#:new-line). The use of "new-line" in the [\[lex.charset\] table](http://eel.is/c++draft/tab:lex.charset.basic) is descriptive of the glyph used to represent the U+000A character; it isn't a defining term.

There should be wording somewhere that states that the set of characters accepted as new-line characters is implementation-defined. I've been unable to find any such wording though. The _new-line_ grammar production is also suggestive that there is exactly one character that qualifies as "the" new-line character. That reflects neither intent nor existing practice.
```
new-line:
    the new-line character
```

> This issue may be fixed by P2348R2.

Yes, I believe it will be.

**Comment by jensmaurer** [comment]
I think CWG2639 has addressed this.

"new-line character" means exactly U+000A in the translation character set.

See [lex.phases] p1 as amended: For UTF-8 source files, all of CR-only, CR/LF, and LF-only map to U+000A newlines. For other source files, the end-of-line behavior is implementation-defined (like anything else about interpreting non-UTF-8 source files).

I'm not seeing a residual CWG defect; neither for the original issue nor Tom's concerns.

**Comment by tahonermann** [comment]
> I think [CWG2639](https://cplusplus.github.io/CWG/issues/2639.html) has addressed this.

Ah, yes, I forgot about that update.

> I'm not seeing a residual CWG defect; neither for the original issue nor Tom's concerns.

I agree.

**Comment by xmh0511** [comment]
Fixed by [CWG2639](https://cplusplus.github.io/CWG/issues/2639.html)
