### ISSUE TITLE
CWG2532 [expr.new] does not specify kind of pointer value in case of an array with no elements

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/CWG#2]
https://github.com/cplusplus/draft/issues/3178 http://lists.isocpp.org/core/2019/09/7203.php

Full name of submitter (unless configured in github; will be published with the issue): Andrey Erokhin

Reference (section label): [expr.new]

Issue description:
[expr.new] shall specify which kind of pointer value ([basic.compound]):
> Every value of pointer type is one of the following:
> [(3.1)](http://eel.is/c++draft/basic.compound#3.1) — a [pointer to](http://eel.is/c++draft/basic.compound#def:pointer_to) an object or function (the [point](http://eel.is/c++draft/basic.compound#def:point)er is said to point to the object or function), or
> [(3.2)](http://eel.is/c++draft/basic.compound#3.2) — a [pointer past the end of](http://eel.is/c++draft/basic.compound#def:pointer_past_the_end_of) an object ([[expr.add]](http://eel.is/c++draft/expr.add)), or
> [(3.3)](http://eel.is/c++draft/basic.compound#3.3) — the [null pointer value](http://eel.is/c++draft/basic.compound#def:value,null_pointer) for that type, or
> [(3.4)](http://eel.is/c++draft/basic.compound#3.4) — an [invalid pointer value](http://eel.is/c++draft/basic.compound#def:value,invalid_pointer)[.](http://eel.is/c++draft/basic.compound#3.sentence-8)

is produced by `new T[0]`.

**Comment by jensmaurer** [comment]
CWG2532
