### ISSUE TITLE
[expr.const] `allocate_at_least` is not mentioned

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/CWG#20]
Full name of submitter (unless configured in github; will be published with the issue): Jiang An

Reference (section label): [expr.const]

Link to reflector thread (if any):

Issue description:

`std::allocator<T>::allocate_at_least` also dynamically allocates storage in constant evaluation like `std::allocator<T>::allocate`. Presumably `allocate_at_least` should have the same restrictions in constant evaluation as `allocate`.

Suggested resolution:

Change [expr.const]/(5.21) as indicated:
> a call to an instance of `std​::​allocator<T>​::​allocate` **or `std::allocator<T>::allocate_at_least`** ([allocator.members]), unless the allocated storage is deallocated within the evaluation of _E_;

**Comment by jensmaurer** [comment]
`allocate_at_least` was added by [P0401R6](https://wg21.link/p0401r6) Providing size feedback in the Allocator interface

**Comment by jensmaurer** [comment]
It's not readily apparent why `allocate_at_least` would be useful during constant evaluation, since the memory needs to be freed during constant evaluation, too. I do notice that `constexpr` was added to the interface after the LEWG review in Prague. I'll ask the authors what they want.

**Comment by jwakely** [comment]
I don't see why a Core issue is needed here, it should be fixed in the library by saying that during constant evaluation, `std::allocator<T>::allocate_at_least(n)` returns `{allocate(n), n}`.

This needs no special treatment from the Core language and no changes to compiler implementations to support it.

**Comment by JohelEGP** [comment]
I could see an use for returning `{allocate(n), m}` where `m >= n`, even during constant evaluation, to help catch UB that would otherwise manifest only at runtime.
