### ISSUE TITLE
[expr.await] `await_suspend` can have type `std::coroutine_handle<>` but we restrict the type to `std::coroutine_handle<Z>`

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#203]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

````cpp
#include <iostream>
#include <coroutine>
struct Task{
    struct promise_type;
    using handle = std::coroutine_handle<promise_type>;
    struct promise_type{
        auto initial_suspend(){
            return std::suspend_never{};
        }
        auto final_suspend() noexcept{
            return std::suspend_always{};
        }
        void unhandled_exception(){}
        void return_void(){}
        auto get_return_object(){
           return Task{handle::from_promise(*this)};
        }
    };
    handle coro;
};
struct SecondTimes{
    bool await_ready(){
        return false;
    }
    std::coroutine_handle<> await_suspend(std::coroutine_handle<> p){  // #1
        return p;
    }
    void await_resume(){}
};

Task fun(){
    std::cout<<"begin\n";
    co_await SecondTimes{};
    std::cout<<"end\n";
}

int main() {
   auto r = fun();
   //r.coro.resume();
}
````
As [shown](https://godbolt.org/z/fo4Kbj1jE) in `#1`, the return type of `await_expression` can have `std::coroutine_handle<>`, however, [expr.await] p3 and [expr.await] p5 instead say
> await-suspend is the expression e.await_­suspend(h), which shall be a prvalue of type void, bool, or std​::​coroutine_­handle<Z> for **some type Z**.

That means `Z` at least is a valid type in C++. How about `std​::​coroutine_­handle<>`?

**Comment by villevoutilainen** [comment]
Yeah, well, for coroutine_handle<>, Z is void. What's the problem?

**Comment by jensmaurer** [comment]
`std::coroutine_handle<void>` and `std::coroutine_handle<>` are the same type; see [support.coroutine].
