### ISSUE TITLE
[basic.life], [class.cdtor] Referring to a member of a virtual base outside lifetime

### ISSUE THREAD

**Issue by ecatmur** [cplusplus/CWG#204]
[[basic.life]](https://wg21.link/basic.life) paragraphs 6-7 prohibit the pointer-to-virtual-base and reference-to-virtual-base conversions respectively for out-of-lifetime class objects; however they do not bar the equally dangerous formation of a glvalue to a *member* of a virtual base class:

    struct B { int i; };
    struct D : virtual B {};
    union U { int i; D d; } u = {.i = 0};
    int& r = u.d.i;

(Note that this does *not* involve formation of an lvalue to the `B` subobject of `u.d`, which would be undefined behavior under [basic.life] paragraph 7; instead, [[expr.ref]](https://wg21.link/expr.ref) works on the basis that members of a base class are members of the derived class; see e.g. paragraph 7 of that clause.)

Indeed, since B is here a standard-layout type, `u.d` is pointer-interconvertible with `u.d.i` [[class.mem]](https://wg21.link/class.mem) and so we can use a cast to bypass the prohibition:

    B& b = reinterpret_cast<B&>(u.d.i);

[[class.cdtor]](https://wg21.link/class.cdtor) paragraph 1 tries to prohibit referencing members of virtual bases, along with virtual bases themselves (a class with a virtual base has a nontrivial constructor) but fails because it does not cover access to objects of class type with nontrivial constructor whose lifetime was ended other than by calling a nontrivial destructor (e.g. via storage reuse):

    struct B { int i; };
    struct D : virtual B {};
    union U { int i; D d; } u = {.d = {}};
    D& d = u.d;
    u.i = 0;
    int& r = d.i;

Per [issue 1530](https://wg21.link/cwg1530), the prohibitions in [class.cdtor] paragraphs 1 and 3 are overbroad and inconsistent with [basic.life]; we want to permit address computation on bases and members as long as virtual base layouts are not involved:

    struct X { float f; ~X() {} };
    union U { int i; X x; } u = {.x = {}};
    u.i = 0;
    &u.x.f;  // OK per [basic.life]/7, but
    u.x = {};
    u.x.~X();  // invoking the destructor of x makes this...
    u.x.i = 0;
    &u.x.f;  // ...UB per [class.cdtor]/1

Indeed, [class.cdtor] should only concern itself with objects under construction and destruction, and not those outside lifetime whose construction and/or destruction is not under way: [[basic.life]/6](https://wg21.link/basic.life#6.sentence-2) [[basic.life]/7](https://wg21.link/basic.life#7.sentence-2).

(See also [issue 1517](https://wg21.link/cwg1517).)

Suggested resolution:

1. Change [basic.life] paragraph 6 as follows:

... The program has undefined behavior if:
* the pointer is used as the operand of a delete-expression,<ins> or</ins>
* <del>the pointer is used to access a non-static data member or call a non-static member function of the object, or</del>
* the pointer is implicitly converted ([conv.ptr]) to a pointer to a virtual base class, or
* the pointer is used as the operand of a static_cast ([expr.static.cast]), except when the conversion is to pointer to cv void, or to pointer to cv void and subsequently to pointer to cv char, cv unsigned char, or cv std::byte ([cstddef.syn]), or
* the pointer is used as the operand of a dynamic_cast ([expr.dynamic.cast]).
<ins>[Note: referencing a non-static data member or calling a non-static member function is performed via a glvalue formed by indirecting the pointer; see below. --end note]</ins>
...
void B::mutate() {
  new (this) D2;    // reuses storage --- ends the lifetime of *this
  f();              // undefined behavior<ins> (see below)</ins>
  ... = this;       // OK, this points to valid memory
}

void g() {
  void* p = std::malloc(sizeof(D1) + sizeof(D2));
  B* pb = new (p) D1;
  pb->mutate();
  \*pb;              // OK, pb points to valid memory
  void* q = pb;     // OK, pb points to valid memory
  pb->f();          // undefined behavior<ins> (see below)</ins>: lifetime of *pb has ended
}
-- end example]

Drafting note: the removed bullet point is unnecessary and misleading, since class member access expressions involving pointer syntax are transformed to `(*(E1)).E2` [expr.ref]. This means the calls to `B::f()` in the example need to refer to the following paragraph.

2. Change [basic.life] paragraph 7 as follows:

[...] The program has undefined behavior if:
* the glvalue is used to access the object, or
* the glvalue is used to call a non-static member function of the object, or
* the glvalue is bound to a reference to a virtual base class ([dcl.init.ref]), or
* <ins>the gvalue is used to refer to a non-static data member of a virtual base class, or</ins>
* the glvalue is used as the operand of a dynamic_cast ([expr.dynamic.cast]) or as the operand of typeid.
<ins>[Example:
    struct W { int j; };
    struct X : public virtual W { };
    struct Y {
      int* p;
      X x;
      Y() : p(&x.j) {   // undefined, x is not yet constructed
        }
    };
-- end example]</ins>

Drafting note: alternatively, the inserted bullet point could be formalized, viz:
* the glvalue is used as the object of a class member access expression whose id-expression refers to a non-static data member of a virtual base class, or

3. Strike [class.cdtor] paragraph 1 entirely, including examples, and replace with:

[Note: [basic.life] describes how a pointer or glvalue to an object that is outside its lifetime and is not under construction or destruction can be used. --end note]

Drafting note: the wording "to an object that is outside its lifetime" is a bit careless; [basic.life] paragraphs 6 and 7 are more exact but I don't feel it's necessary to replicate that wording here.

4. Change [class.cdtor] paragraph 3 as follows:

To explicitly or implicitly convert a pointer (a glvalue) referring to an object of class X <ins>that is under construction or destruction</ins> to a pointer (reference) to a direct or indirect <ins>virtual</ins> base class B of X<ins>, or to use said pointer (glvalue) to form a glvalue to a non-static data member of the B subobject of obj, or to call a non-static member function of said subobject</ins>, the construction of X and the construction of all of its direct or indirect bases <del>that directly or indirectly derive from</del><ins>for which</ins> B <ins>is a direct or indirect virtual base</ins> shall have started and the destruction of these classes shall not have completed, otherwise the conversion<ins>, member access or member function call</ins> results in undefined behavior. <del>To form a pointer to (or access the value of) a direct non-static member of an object obj, the construction of obj shall have started and its destruction shall not have completed, otherwise the computation of the pointer value (or accessing the member value) results in undefined behavior.</del>

Drafting note: several of these changes are taken from issue 1517 as regarding the application of the resolution of [issue 597](https://wg21.link/cwg597) to [class.cdtor] paragraph 3.

**Comment by jensmaurer** [comment]
For your first example, note that the union contains a `D`, which is not a standard-layout type per [class.prop] p3. Could you please point to the rule "we can use the first member provision to bypass the prohibition"  that makes the `reinterpret_cast` have defined behavior?

**Comment by jensmaurer** [comment]
Note that [class.cdtor] is intended to discuss behavior during construction and destruction only.

> there seems little point to retain the prohibition on calling non-static member functions in general, given that it is only calling virtual member functions and member functions of virtual base classes that actually causes an issue:

Invoking a non-static member function on an out-of-lifetime object is undefined behavior per [basic.life] p7.2, which requires a diagnostic in constant evaluation context per [expr.const] p5.8. The standard is clear in that regard; I'm not seeing a defect here.   Please file a bug report for the compilers that don't diagnose it during constant evaluation. It may or may not be reasonable to allow such invocations, but that seems clearly evolutionary.

The only remaining concern (beyond the already-existing core issues) is this one, it seems:

```
struct B { int i; };
struct D : virtual B {};
union U { int i; D d; } u = {.d = {}};
D& d = u.d;
u.i = 0;
int& r = d.i;
```

**Comment by ecatmur** [comment]
> For your first example, note that the union contains a `D`, which is not a standard-layout type per [class.prop] p3. Could you please point to the rule "we can use the first member provision to bypass the prohibition" that makes the `reinterpret_cast` have defined behavior?

Sure; this is [class.mem]/27. It doesn't matter that `D` is not standard-layout, since the cast only relates to the `B` subobject, which is standard-layout.

**Comment by ecatmur** [comment]
> Note that [class.cdtor] is intended to discuss behavior during construction and destruction only.

Yes; it needs clarification, removal of wording related to behavior outside of those times, and some relaxation to ensure that it is no more strict than [basic.life]. (It should not be possible for an operation on an object that would be UB to *become* defined solely by ending the life of the object.)

> Invoking a non-static member function on an out-of-lifetime object is undefined behavior per [basic.life] p7.2, which requires a diagnostic in constant evaluation context per [expr.const] p5.8. The standard is clear in that regard; I'm not seeing a defect here. Please file a bug report for the compilers that don't diagnose it during constant evaluation. It may or may not be reasonable to allow such invocations, but that seems clearly evolutionary.

OK; I'll retarget to retain that prohibition and prepare a proposal to EWG.

> The only remaining concern (beyond the already-existing core issues) is this one, it seems:
> 
> ```
> struct B { int i; };
> struct D : virtual B {};
> union U { int i; D d; } u = {.d = {}};
> D& d = u.d;
> u.i = 0;
> int& r = d.i;
> ```

I think clarifying [class.cdtor] is also necessary.

**Comment by jensmaurer** [comment]
For the last example `int& r = d.i;`, it seems we conceptually convert `d` to `B&` to evaluate the class member access, but [expr.ref] is not written that way, and [epxr.ref] p7 makes it clear by using "direct member" that the mentions of "member" elsewhere in that subclause rely on "a member of a base class is also a member of a derived class".

**Comment by ecatmur** [comment]
> For the last example `int& r = d.i;`, it seems we conceptually convert `d` to `B&` to evaluate the class member access, but [expr.ref] is not written that way, and [epxr.ref] p7 makes it clear by using "direct member" that the mentions of "member" elsewhere in that subclause rely on "a member of a base class is also a member of a derived class".

Yes. I'll mention that to try to ensure people don't come into this with the wrong mental model.

**Comment by ecatmur** [comment]
It has been pointed out to me that my last example here results from a misconception; [class.cdtor] paragraph 1 applies in addition to [basic.life] paragraphs 6 and 7 (that is, it further restricts allowable programs); it does not supersede those paragraphs. I think that a few Notes could clarify things here; I'll propose as editorial.
