### ISSUE TITLE
[expr.const] Constant expression evaluation of non-defining declarations of variables with static or thread_local storage duration

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [cplusplus/CWG#21]
**Full name of submitter (unless configured in github; will be published with the issue):** Hubert Tong

**Reference (section label):** [expr.const]

**Link to reflector thread (if any):** N/A

**Issue description:**
[P2242](https://wg21.link/p2242), "Non-literal variables (and labels and gotos) in constexpr functions", adds a bullet to the list of things that are not okay to evaluate in a core constant expression:

> - a control flow that passes through a declaration of a variable with static or thread storage duration

It seems block-scope extern declarations are included by the above bullet.

The new bullet was added as part of removing a restriction on having _definitions_ of such variables in constexpr bodies. Even if there is wording that says that non-defining declarations are not part of any sequence of control flow (I am not sure that there is), it would be less confusing for the bullet to just say "definition" instead of "declaration".

**Suggested resolution:**
Change the bullet as follows:

> - a control flow that passes through a <del>declaration </del><ins>definition </ins>of a variable with static or thread storage duration

**Comment by jensmaurer** [comment]
CWG2552

**Comment by jensmaurer** [comment]
@hubert-reinterpretcast , I've also added a fix for [stmt.dcl] for consistency.

**Comment by hubert-reinterpretcast** [comment]
> @hubert-reinterpretcast , I've also added a fix for [stmt.dcl] for consistency.

LGTM. I think the [stmt.dcl] change is editorial in nature (but makes sense to group with this one).
