### ISSUE TITLE
No pointers to member bit-field

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#214]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[class.bit] p3 says
> The address-of operator & shall not be applied to a bit-field, so **there are no pointers to bit-fields**.

[basic.compound] p3 says
>  Except for pointers to static members, **text referring to “pointers” does not apply to pointers to members**.

So, are there pointers to member bit-fields? Even though, the former part can forbid `&Class::bit_field`. 
````cpp
struct A{
  int a: 10;
};
int main(){
  int A::* ptr = &A::a;
}
````

### Suggested resolution
> The address-of operator & shall not be applied to a bit-field, so there are no pointers to bit-fields or pointers to member bit-fields.

Change [expr.unary.op] p3
> The operand of the unary & operator shall be an lvalue of some type T. The result is a prvalue.
>> -  If the qualified-id names a non-static ~or variant~ member m of some class C, other than an explicit object member function, **the qualified-id shall not denote a bit-field**, the result has type “pointer to member of class C of type T” and designates C​::​m.

A drive-by fix is that a variant member is a non-static data member.

**Comment by jensmaurer** [comment]
[expr.unary.op] p5 says "The operand of & shall not be a bit-field."

That seems to express the desired restriction. I'm not seeing a defect in the standard.
