### ISSUE TITLE
CWG2681 [over.match.class.deduct] deducing member array type from string literal

### ISSUE THREAD

**Issue by cmeerw** [cplusplus/CWG#217]
Full name of submitter (unless configured in github; will be published with the issue): originally reported by Jonathan Caves a long time ago

Reference (section label): over.match.class.deduct

Link to reflector thread (if any): [Minor issue with CTAD for aggregates](https://lists.isocpp.org/core/2020/03/8682.php)

Issue description: [over.match.class.deduct/1.8](https://eel.is/c++draft/over.match.class.deduct#1.8) states "if ei is of array type and xi is a [braced-init-list](https://eel.is/c++draft/dcl.init.general#nt:braced-init-list) or [string-literal](https://eel.is/c++draft/lex.string#nt:string-literal), Ti is an rvalue reference to the declared type of ei,"

For a string literal this will then fail overload resolution as it is an lvalue.

Suggested resolution: see [Re: Minor issue with CTAD for aggregates](https://lists.isocpp.org/core/2020/03/8685.php) - use a const lvalue reference instead

**Comment by jensmaurer** [comment]
CWG2681

Thanks for keeping an eye on those old things.
