### ISSUE TITLE
CWG2682 [temp.pre] Function/variable/class templates are templated functions/variables/classes

### ISSUE THREAD

**Issue by LegionMammal978** [cplusplus/CWG#219]
Full name of submitter (unless configured in github; will be published with the issue): Matthew House

Reference (section label): [[temp.pre] paragraph 8](https://wg21.link/temp.pre#8)

Link to reflector thread (if any):

Issue description:

The Standard often uses the terms "templated function", "templated variable", and "templated class" to refer to certain kinds of templated entities. In context, these terms are clearly meant to include function templates, variable templates, and class templates. However, the terms are never explicitly defined, and a strict reading might conclude that, e.g., a function template is not a templated function, since it is not a function. Therefore, the inclusive meanings of these terms should be clarified.

Suggested resolution:

Change [[temp.pre] paragraph 8](https://wg21.link/temp.pre#8) as follows:

> An entity is *templated* if it is
>
> - a template,
> - an entity defined ([[basic.def]](https://wg21.link/basic.def)) or created ([[class.temporary]](https://wg21.link/class.temporary)) in a templated entity,
> - a member of a templated entity,
> - an enumerator for an enumeration that is a templated entity, or
> - the closure type of a *lambda-expression* ([[expr.prim.lambda.closure]](https://wg21.link/expr.prim.lambda.closure)) appearing in the declaration of a templated entity.
>
> [*Note 6*: A local class, a local or block variable, or a friend function defined in a templated entity is a templated entity. — *end note*]
> <ins>A *templated function* is a function template or a function that is templated. A *templated class* is a class template or a class that is templated. A *templated variable* is a variable template or a variable that is templated.</ins>

Change [[dcl.spec.auto.general] paragraph 12](https://wg21.link/dcl.spec.auto.general#12) as follows:

> Return type deduction for a templated <del>entity that is a</del> function <del>or function template</del> with a placeholder in its declared type occurs when the definition is instantiated even if the function body contains a `return` statement with a non-type-dependent operand.

**Comment by jensmaurer** [comment]
CWG2682
