### ISSUE TITLE
[expr.new] Lacks the wording about how the pointer supplied in new-placement can be converted to `void*`

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#221]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[expr.new] p19 says:
> If the new-placement syntax is used, the **initializer-clauses in its expression-list are the succeeding arguments**.  

Consider this example:
````cpp
#include <iostream>
int main(){
   auto ptr = new int{0};
   new (ptr) int{1}; // #2
}
````
The expression `ptr` in the *expression-list* of *new-placement* has type `int*`, the found candidate of allocation function is `[[nodiscard]] void* operator new(std::size_t size, void* ptr) noexcept;`, where the arguments of the calling might be: `sizeof(int), ptr`. Note that there is no implicit conversion sequence from `int*` to `void*`, however, the candidate is a matched one. 

### Suggested resolution:
We lack the wording to specify how the `ptr` match `void*` in the non-allocation form case.

**Comment by jensmaurer** [comment]
> Note that there is no implicit conversion sequence from int* to void*

Of course, there is; see [conv.ptr] p2:

> A prvalue of type “pointer to cv T”, where T is an object type, can be converted to a prvalue of type “pointer to cv void”.

**Comment by xmh0511** [comment]
Yes, [conv.ptr] p2 definitely covers this case.
