### ISSUE TITLE
CWG2685 [over.match.class.deduct] Aggregate CTAD, strings, and brace elision

### ISSUE THREAD

**Issue by cmeerw** [cplusplus/CWG#222]
Full name of submitter (unless configured in github; will be published with the issue): originally reported by Jason Merrill

Reference (section label): over.match.class.deduct

Link to reflector thread (if any): [Aggregate CTAD, strings, and brace elision](https://lists.isocpp.org/core/2020/07/9583.php)

Issue description: [(1.5)](https://eel.is/c++draft/over.match.class.deduct#1.5) brace elision is not considered for any aggregate element that has a dependent non-array type or an array type with a value-dependent bound

This causes issues for an array with non-dependent bound initialized with a string literal.

There is implementation divergence: https://gcc.godbolt.org/z/95G31evdM

Suggested resolution: see [Re: Aggregate CTAD, strings, and brace elision](https://lists.isocpp.org/core/2020/07/9584.php)

**Comment by jensmaurer** [comment]
CWG2685
