### ISSUE TITLE
CWG2689 [basic.fundamental] No mention of cv std::nullptr_t in basic.fundamental

### ISSUE THREAD

**Issue by anooprana986** [cplusplus/CWG#223]
Full name of submitter (unless configured in github; will be published with the issue): Anoop Rana

Reference (section label): [basic.fundamental]

Link to reflector thread (if any): https://github.com/cplusplus/CWG/issues/193#issuecomment-1383612343

Issue description: There is no mention of cv qualified `std::nullptr_t` in [basic.fundamental](https://timsong-cpp.github.io/cppwp/n4861/basic.fundamental#14).

<h4>Suggested resolution:</h4>

Add wording for cv qualified version of `std::nullptr_t` in [basic.fundamental].

**Comment by jensmaurer** [comment]
CWG2689

**Comment by languagelawyer** [comment]
Isn't
> The types denoted by std::nullptr_t, const std::nullptr_t, volatile std::nullptr_t, and const volatile std::nullptr_t are distinct types.

an extremely long and boring way to say
> the type of `nullptr` is a non-class, non-array type

?

**Comment by languagelawyer** [comment]
How about

[lex.nullptr]/1
> The pointer literal is the keyword `nullptr`. It has <ins>a distinct fundamental</ins> type <ins>([basic.fundamental]) <del>`std​::​nullptr_t`</del>.

[basic.fundamental]/16
> <ins>The type of `nullptr` prvalue (and any its _cv_-qualified version) is a non-class, non-array object type, distinct from other types in this subclause.</ins> A value of type std​::​nullptr_t is a null pointer constant ([conv.ptr])…
