### ISSUE TITLE
CWG2559 [expr.const] Should consteval = default functions be allowed to fallback to runtime evaluation?

### ISSUE THREAD

**Issue by AaronBallman** [cplusplus/CWG#23]
Full name of submitter (unless configured in github; will be published with the issue): Aaron Ballman

Reference (section label): [expr.const]p5.5, see also [dcl.constexpr]p7

Link to reflector thread (if any): https://lists.isocpp.org/core/2022/03/12116.php

Issue description: I believe that consteval functions should always be evaluated at compile time and never fallback to runtime. Based on that, I think that a consteval =default function which doesn't satisfy the constexpr requirements should still be treated as a consteval function. There is implementation divergence with the following example:
```
template <typename Ty>
struct S {
  Ty i;
  consteval S() = default;
};

template <typename Ty>
struct T {
  Ty i;
  consteval T() {}
};

S<int> one; // Clang rejects
T<int> two; // Clang, GCC, ICC, MSVC reject

void locals() {
  S<int> three; // Clang rejects
  T<int> four;  // Clang, GCC, ICC, MSVC reject
}
```
I believe the Clang behavior is what's desired.

Suggested resolution:

**Comment by jensmaurer** [comment]
CWG2559

This one seems moot if CWG2558 confirms the status quo of the normative wording (and confirms that all current implementations are non-conforming).
