### ISSUE TITLE
CWG2691 [lex.ccon] hexadecimal-escape-sequence

### ISSUE THREAD

**Issue by fraserjgordon** [cplusplus/CWG#230]
Full name of submitter: Fraser Gordon

Reference: [[lex.ccon]](https://eel.is/c++draft/lex.ccon) [hexadecimal-escape-sequence](https://eel.is/c++draft/lex.ccon#nt:hexadecimal-escape-sequence)

Link to reflector thread: https://lists.isocpp.org/std-proposals/2023/01/5532.php

Issue description:

The _hexadecimal-escape-sequence_ rule matches text of the form `\x{20}20` as an escape sequence due to its recursive definition.

Suggested resolution:

_hexadecimal-escape-sequence_:
    \x _simple-hexadecimal-digit-sequence_
    \x{ _simple-hexadecimal-digit-sequence_ }

**Comment by jensmaurer** [comment]
CWG2691
