### ISSUE TITLE
CWG2879 [expr.const.cast] p3 does not cover all cases of similar types

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#232]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[expr.const.cast] p3 says:
> For **two similar types T1 and T2**, a prvalue of type T1 may be explicitly converted to the type T2 using a const_­cast if, considering the qualification-decompositions of both types, each P<sup>1</sup><sub>i</sub> is the same as P<sup>2</sup><sub>i</sub> for all i. **The result of a const_­cast refers to the original entity**.

The first case is:
````cpp
const_cast<int>(0);
````
All mainstream [implementations](https://godbolt.org/z/96ox4YT8n) emit the error:
> invalid use of 'const_cast' with type 'int', which is not a pointer, reference, nor a pointer-to-data-member type

However, we do not have this limitation in subclause [expr.const.cast] p3. Moreover, each P<sup>1</sup><sub>i</sub> is the same as P<sup>2</sup><sub>i</sub> for all i can just be vacuous true if `Pi` is empty. 

[expr.const.cast] p2 also implies the case
> Subject to the restrictions in this subclause, an expression can be cast to its own type using a const_­cast operator[.](https://eel.is/c++draft/expr.const.cast#2.sentence-1)

The relevant issue is https://stackoverflow.com/questions/61003855/const-cast-to-non-pointer-non-reference-type

***

The second case is 
> The result of a const_­cast refers to the original entity

This only applies to the case where the destination type is pointer or reference type. 
````cpp
int const a = 0;
const_cast<int>(a); // The result does not refer to the original entity
````

**Comment by frederick-vs-ja** [comment]
There's implementation divergence on
- function pointer types,
- function reference types,
- pointer-to-member-function types,
- enumeration types, and
- `nullptr_t`.

MSVC accepts identically converting cases, while GCC and Clang reject them.

Presumably, the intent is restricting the types to object pointer types (including _cv_ `void*`), object reference types, and pointer-to-data-member types.

**Comment by frederick-vs-ja** [comment]
Addressed by CWG2879.
