### ISSUE TITLE
[lex.phases] p1 Which is the resulting sequence?

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#233]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[lex.phases] p1 says
>  If an input file is determined to be a UTF-8 file, then it shall be a well-formed UTF-8 code unit sequence and **it is decoded** to **produce a sequence of UCS scalar values** that constitutes the sequence of elements of the translation character set. **In the resulting sequence**, each pair of characters in the input sequence consisting of U+000d carriage return followed by U+000a line feed, as well as each U+000d carriage return not immediately followed by a U+000a line feed, is replaced by a single new-line character.

The first sentence means: The input file is decoded to a sequence of UCS scalar values, which makes sense to be the resulting sequence since it is the subject of the sentence. However, regardless in the following paragraph or the relevant defined grammar, we use characters, for example:

[lex.phases] p1  itself says:
> each pair of **characters** in the input sequence

[lex.phases] p1.2
> If the first translation **character** is U+feff byte order mark

lex.name#nt:identifier-start:
> an element of the **translation character set** of class XID_Start

### Suggested resolution
Presumably, the resulting sequence should refer to the sequence of elements of the translation character set. Change [lex.phases] p1 to
> If an input file is determined to be a UTF-8 file, then it shall be a well-formed UTF-8 code unit sequence and it is decoded to produce a sequence of UCS scalar values, **which then identifies the sequence of elements of the translation character set as the resulting sequence**.

**Comment by jensmaurer** [comment]
That's what we say

"that constitutes the sequence of elements of the translation character set."

The definition of "translation character set" is (almost) clear it consists of characters. There is paper P2749 in flight that seek to change the text in that area.

**Comment by xmh0511** [comment]
> That's what we say
> 
> "that constitutes the sequence of elements of the translation character set."
> 
> The definition of "translation character set" is (almost) clear it consists of characters. There is paper P2749 in flight that seek to change the text in that area.

I would say the resulting sequence is ambiguous in the context for which sequence it refers to
> - a sequence of UCS scalar values
> - the sequence of elements of the translation character set

From English, `the sequence of elements of the translation character set` is the attribute clause of `a sequence of UCS scalar values`, and the latter is the subject of the sentence, hence, the "resulting sequence" in the next sentence should refer to the subject of the previous sentence(i.e. `a sequence of UCS scalar values`). This is the concern. I don't know how P2749 will reword this part.

**Comment by tahonermann** [comment]
> There is paper P2749 in flight that seek to change the text in that area.

That paper hasn't been published yet, but a draft can be found [here](https://wg21.link/d2749r0).

**Comment by xmh0511** [comment]
> > There is paper P2749 in flight that seek to change the text in that area.
> 
> That paper hasn't been published yet, but a draft can be found [here](https://wg21.link/d2749r0).

Thanks for the link.
