### ISSUE TITLE
CWG2707 [temp.deduct.guide] trailing requires-clause for deduction guides

### ISSUE THREAD

**Issue by cmeerw** [cplusplus/CWG#234]
Full name of submitter (unless configured in github; will be published with the issue): originally reported by Richard Smith

Reference (section label): temp.deduct.guide

Link to reflector thread (if any): [defect report: class template argument deduction ignores constructor requires-clauses](https://lists.isocpp.org/core/2020/02/8566.php)

Issue description: the deduction guide grammar in [temp.deduct.guide] doesn't allow a requires-clause after the deduction-guide, but gcc and MSVC accept it (clang rejects)

(the other issue mentioned in that email is covered by CWG2628)

Suggested resolution: update grammar to allow a trailing requires-clause

**Comment by jensmaurer** [comment]
CWG2707
