### ISSUE TITLE
[over.ics.list]/8 Deleted constructor in list-initialization sequence of aggregate

### ISSUE THREAD

**Issue by leni536** [cplusplus/CWG#235]
Full name of submitter (unless configured in github; will be published with the issue): Lénárd Szolnoki

**Reference** (section label): [[over.ics.list]/8](https://eel.is/c++draft/over.ics.list#8)
https://github.com/cplusplus/draft/blob/388eff69768d3ba97c095de98e9972685f2e3579/source/overloading.tex#L2464-L2468
> Otherwise, if the parameter has an aggregate type which can be initialized from the initializer list according to the rules for aggregate initialization ([[dcl.init.aggr]](https://eel.is/c++draft/dcl.init.aggr)), the implicit conversion sequence is a user-defined conversion sequence whose second standard conversion sequence is an identity conversion[.](https://eel.is/c++draft/over.ics.list#8.sentence-1)

**Issue description:**

Consider the following program

```cpp
struct A1 {
    A1(int) = delete;
};

struct A2 {
    A2(int) {}
};

struct B1 {
    A1 a;
};

struct B2 {
    A2 i;
};

int foo(B1) {
    return 1;
}
int foo(B2) {
    return 2;
}

int main() {
    return foo({1});
}
```

I would expect this program to be ill-formed, due to the call `foo({1})` being ambiguous, as a deleted function is not meant to alter overload resolution.

However according to the wording `void foo(B1)` is not viable, and the program returns with 2.

There is implementation divergence:
https://godbolt.org/z/7d6zfaKnE

**Further notes:**
[[cwg2169]](https://wg21.link/cwg2169) is closely related (same paragraph), but focuses on narrowing conversion.

There are many examples for ill-formed conversion within a list-initialization sequence that are not meant to alter overload resolution. Without trying to be exhaustive:

1. Calling a deleted function (this issue)
2. Narrowing conversion ([[cwg2169]](https://wg21.link/cwg2169))
3. Calling a private function https://godbolt.org/z/5e8Tz1G7Y
4. Binding a non-const reference to a bitfield https://godbolt.org/z/vonGYTz7b
5. Calling explicit constructor in list-initialization https://godbolt.org/z/xGe5a1GbY
6. Calling a consteval constructor with arguments not usable in constant expression https://godbolt.org/z/dPafTfjqE
7. Initializing an aggregate with designated initializer in wrong order https://godbolt.org/z/K1KrYncbr (brought up at https://lists.isocpp.org/std-discussion/2023/01/2008.php)

This issue might be the same as [[cwg2169]](https://wg21.link/cwg2169), or it could be merged with it. But I wanted to point out that the issue is not limited to narrowing conversions, therefore a resolution should not just carve out edge cases for that.

Suggested resolution:

I suggest that a list-initialization sequence of an aggregate should consider implicit conversion sequences from each initializer-clause to the corresponding explicitly initialized aggregate element, and implicit conversion sequences from the default member initializers or `{}` for the remaining elements.

**Comment by jensmaurer** [comment]
I have amended CWG2169 accordingly. I don't think this warrants a separate issue, just some care when addressing the other one.
