### ISSUE TITLE
CWG2705 [expr.ref] Accessing ambiguous subobjects

### ISSUE THREAD

**Issue by opensdh** [cplusplus/CWG#242]
Reference (section label): [expr.ref]

Link to reflector thread (if any): (discussion in Issaquah)

Issue description:

Consider
```cpp
struct A {int i;};
struct X : A {};
struct Y : A {};
struct S : X,Y {};

void f(S &s) {++s.X::i;}
```
There is a rule that `&s` be able to "be implicitly converted to a pointer to the naming class of the right operand" ([class.access.base]/6), which correctly selects `X` here, but [expr.ref]/6.2 merely says that

> If `E2` is a non-static data member [&hellip;], the expression designates the corresponding member subobject of the object designated by the first expression.

`E2` and `Y::i` equally denote `A::i` (since name lookup produces declarations), and there's nothing that indicates which `A::i` is selected as the "corresponding member subobject".  (Note that `s.X::A::i` means the same as `s.A::i` and is ambiguous.)  This is of course part of the broader confusion between base classes and base class subobjects.

Suggested resolution:

Change [class.access.base]/6 to actually perform the conversion it requires, possibly moving it to [expr.ref] since it's not about access control.  (The definition of "naming class" in [class.access.base]/5 would then need to be italicized.)

**Comment by jensmaurer** [comment]
CWG2705
