### ISSUE TITLE
[intro.races] p14 Can "B does not happen before A" imply "A happen before B"?

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#252]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[intro.races] p14 says
> The value of an atomic object M, as determined by evaluation B, shall be the value stored by some side effect A that modifies M, where **B does not happen before A**. 

Does "B does not happen before A" definitely mean "A happens before B"? For example, if we say `B` is not sequenced before `A`, it can mean
>1. A is sequenced before B,
>2. A and B may be indeterminately sequenced
>3. A and B may be unsequenced

That is, it does not definitely mean: `B` is not sequenced before `A` can imply A is sequenced before B. There may be other cases. So, for "happens before", "B does not happen before A" can only imply "A happens before B"? Are there any other cases? If there no any other possibilities, why don't we just says
> The value of an atomic object M, as determined by evaluation B, shall be the value stored by some side effect A that modifies M, where `A` happens before `B`

？This is direct.

**Comment by languagelawyer** [comment]
There are relaxed atomic operations

**Comment by jensmaurer** [comment]
No, "B does not happen before A" does not mean (or imply) "A happens before B".   If I say "y is not larger than x", it does not mean "x is larger than y" (because x and y may be equal).  In this case, (for example) A and B may be indeterminately sequenced or may be potentially-concurrent without any synchronization that would establish a happens-before relation.

**Comment by xmh0511** [comment]
> No.
> 
> "B does not happen before A" does not mean (or imply) "A happens before B". If I say "y is not larger than x", it does not mean "x is larger than y" (because x and y may be equal). In this case, (for example) A and B may be indeterminately sequenced or may be potentially-concurrent without any synchronization that would establish a happens-before relation.

However, we can prove `B` does not happen before `A` if we proved that `A` happens before `B` per the definition of "happen before". For the other cases, we cannot prove whether `B` does not happen before `A` or not, which is not provable this is the issue in the rule.
