### ISSUE TITLE
[intro.races] "happen before" should use italic type in rules

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#253]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

For example, [intro.races] p15 says
> If an operation A that modifies an atomic object M **happens before** an operation B that modifies M, then A shall be earlier than B in the modification order of M.

In this rule, we use the literal word "happen before", but we define *happen before*, *simply happen before*, and *strongly happen before*. Do we intend to use "happen before" to refer to all? For instance, we use literally wording "expression" to refer to all expressions in [expr], however, if we use italic *expression*, we refer to the syntax *expression* that is a comma expression.

[syntax] p1
> In the syntax notation used in this document, syntactic categories are indicated by italic type, and literal words and characters in constant width type.

However, these rules that use "happen before" seem only to refer to exact *happen before* concept.

**Comment by jensmaurer** [comment]
In general, we use grammar font for grammar non-terminals and the italics variant of the plain text font when we define a term. Any references to that term are not italicized.

[intro.races] p9 and following defines a number of terms involving "happens before", but only one of these terms is (plain) happens before, and that's the one we talk about in the quoted paragraph.

With respect to the question in the title "should use italic type", this is not a defect.

**Comment by xmh0511** [comment]
> In general, we use grammar font for grammar non-terminals and the italics variant of the plain text font when we define a term. Any references to that term are not italicized.
> 
> [intro.races] p9 and following defines a number of terms involving "happens before", but only one of these terms is (plain) happens before, and that's the one we talk about in the quoted paragraph.
> 
> With respect to the question in the title "should use italic type", this is not a defect.

That is, "happens before" only refers to *happens before* rather than *simply happens before* or *strongly happens before*?

**Comment by jensmaurer** [comment]
Yes.
