### ISSUE TITLE
[defns.dynamic.type] The note is misleading

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#257]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

>  If a pointer p whose static type is “pointer to class B” is **pointing to an object of class D**, derived from B, the dynamic type of the expression *p is “D”. References are treated similarly.  

Since the pointer `p` already points to the subobject `B`, how does it simultaneously point to the containing object? The intent should be:
> If a pointer p whose static type is “pointer to class B” points to an object that is a base class subobject of an object of class `D` derived from `B`, the dynamic type of the expression `*p` is `D`. References are treated similarly.

**Comment by languagelawyer** [comment]
> Since the pointer `p` already points to the subobject `B`

It does not.

> points to an object that is a subobject of an object of class `D` derived from `B`, the dynamic type of the expression `*p` is `D`

In this case, the dynamic type would be the type of the subobject.

**Comment by xmh0511** [comment]
> I think the point here is that having a `B*` pointing to a `D` is rather unusual, as obtaining one requires a `reinterpret_cast`, because the implicit derived-to-base conversion yields a pointer to the base class subobject.

Yes, the only possibility that we point to an object of a derived class type with a pointer value of type "pointer to base class type" is `reinterpret_cast<B*>(ptr_d_obj);`, indirection such a pointer can result in UB per [expr.pre] p4
> If during the evaluation of an expression, the result is not mathematically defined or not in the range of representable values for its type, the behavior is undefined.

Although this wording is unclear whether the value of the Derived class type is out of the range of representable values for the bass class.

**Comment by frederick-vs-ja** [comment]
> (Not sure why this wasn't opened as an editorial issue.)

I think we should continue in cplusplus/draft#5762.

**Comment by tkoeppe** [comment]
Closing this, since it only affects an example and is thus editorial.
