### ISSUE TITLE
[expr.eq] p3 Implementations has a diffrent behavior for comparing the same invalid pointers

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#258]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

> Comparing pointers is defined as follows: 
>> - If one pointer represents the address of a complete object, and another pointer represents the address one past the last element of a different complete object, the result of the comparison is unspecified.
>> - Otherwise, if the pointers are both null, both point to the same function, or both represent the same address, they compare equal.
>> - Otherwise, the pointers compare unequal.

Consider this example:
````cpp
int main(){
    int* ptr = 0;
    {
        int a = 0;
        ptr = &a;
    }
   bool r = ptr== ptr;
}
````
Both GCC and Clang output `true` for `r`. However, this case should fall into the third bullet. In the second bullet, *represent the same address* refer to
> A value of a pointer type that is a **pointer to or past the end of an object** represents the address of the first byte in memory ([intro.memory]) occupied by the object or the first byte in memory after the end of the storage occupied by the object, respectively.

An invalid pointer is not a pointer to a function, object, past the end of an object, or null pointer. Hence, only third bullet is suitable for this case. 

> If two operands compare equal, the result is true for the == operator and false for the != operator.
**If two operands compare unequal, the result is false for the == operator and true for the != operator.**
Otherwise, the result of each of the operators is unspecified.

Hence, the result is guaranteed to be false, as per the current wording.

**Comment by languagelawyer** [comment]
> the result is guaranteed to be false, as per the current wording

[Per the current wording, the behavior is implementation-defined.](http://eel.is/c++draft/basic.stc.general#4.sentence-3)

**Comment by xmh0511** [comment]
> > the result is guaranteed to be false, as per the current wording
> 
> [Per the current wording, the behavior is implementation-defined.](http://eel.is/c++draft/conv.lval#3.3)

However, it does not impact the rule in [expr.eq] p3, which defines rule for **pointers**. The result of lvalue-to-rvalue conversion only specifies what the **value** is. Or, do you mean whether the result of the conversion can be called an invalid pointer or not is implementation-defined?

**Comment by languagelawyer** [comment]
> However, it does not impact the rule in [expr.eq] p3

Even if you somehow got an IPV prvalue, http://eel.is/c++draft/basic.stc.general#4.sentence-3 impacts

> do you mean whether the result of the conversion can be called an invalid pointer or not is implementation-defined?

An implementation can produce e.g. a null pointer value when applying the conversion.
