### ISSUE TITLE
CWG2565 [expr.prim.req] Invalid types formed in the parameter-declaration-clause of a requires-expression

### ISSUE THREAD

**Issue by brevzin** [cplusplus/CWG#26]
Reference (section label): [expr.prim.req]

Issue description: Everyone accepts this example:

```cpp
template <typename T>
concept C = requires (typename T::type x) {
    x + 1;
};

static_assert(!C<int>);
```

However, the rule in [expr.prim.req]/5 currently reads (emphasis mine):

> The substitution of template arguments into a _requires-expression_ may result in the formation of invalid types or expressions **in its _requirement_ s** or the violation of the semantic constraints of those _requirement_ s. In such cases, the _requires-expression_ evaluates to `false`; it does not cause the program to be ill-formed.

This doesn't cover the _parameter-declaration-clause_, which seems to be an oversight. 

Suggested resolution: Something like this:

> The substitution of template arguments into a _requires-expression_ may result in the formation of invalid types or expressions in its _requirement_ s <ins>or _parameter-declaration-clause_, if any,</ins> or the violation of the semantic constraints of those _requirement_ s.

**Comment by jensmaurer** [comment]
CWG2565
