### ISSUE TITLE
CWG2535 [expr.ref] Impose the requirement between the type of object expression and the type of the referred object

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#264]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

Consider this example
````cpp
struct Base{
   int a = 0;
};
struct Base2{
    int a = 1;
};
struct Derived: Base2, Base{
};
int main(){
   Derived d;
   auto ptr = reinterpret_cast<Base*>(&d);
   auto c = ptr->a; // 0 or something else? 
}
````
First, `ptr` points to the object `d` with the type "pointer to Base". [expr.ref] p6 says:
> If E2 is a non-static data member, ...,  the expression designates the corresponding member subobject of the object designated by the first expression.

The lookup context of `a` in `ptr->a` is `Base`, hence the name `a` denotes non-static data member `Base::a`,  the object designated by the first expression is `d`, hence, the glvalue `ptr->a` should designate the instance of `Base::a` in `d`. However, in all implementations, `c` does not have the value `0`. 

### Suggested resolution: 
The behavior seems to be considered as UB. Supply an additional rule in [expr.ref] p3
> If the type of the object expression and the type of the object referred to by the object expression are not similar, the behavior is undefined.

**Comment by frederick-vs-ja** [comment]
This is probably CWG2535.
