### ISSUE TITLE
[basic.def.odr] ODR and non-identical string literal objects in inline functions

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/CWG#269]
Full name of submitter (unless configured in github; will be published with the issue): Jiang An

Reference (section label): [basic.def.odr]

Link to reflector thread (if any):

Issue description:

Given the following 3 inline functions defined in multiple translation units.
```C++
inline const char* f()
{
    return "string literal";
}

inline const char* g()
{
    constexpr auto p = "string literal";
    return p;
}

inline const char* h()
{
    static constexpr auto p = "string literal";
    return p;
}
```
Assuming string literal objects in the same inline functions in different TUs are not merged (permitted by CWG1823), CWG2678 clarfied that different definitions of `g` and `h` render the program ill-formed, no diagnostic required. It seems that multiple non-equivalent definitions of `f` are OK.

The handling is reasonable for `h` since there's only one `p` object in `h` which can't be constant-initialized to different values. However, it seems that `g` is doing the same thing as `f`, and non-equivalent definitions shouldn't make the program IFNDR.

Suggested resolution:

**Comment by jensmaurer** [comment]
We're aware that CWG2678 is a rather ... broad approach, but we don't have a better idea right now.

I think we can imagine interesting things to happen with the (constant) address of the string literal in "g" before the pointer is returned. We would need to clearly delineate the "good" and "bad" cases, which needs a paper targeted at EWG.

There is no wording defect I can see. The advice to users is "don't use string literals in manifestly-constant expressions in inline functions".
