### ISSUE TITLE
CWG2592 [expr.new] We lack the rule that specifies which are placement allocation and deallocation functions

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#28]
[expr.new] p28 says
> If the lookup finds a **usual deallocation function** and that function, considered as a placement deallocation function, would have been selected as a match for the allocation function, the program is ill-formed. 

We explicitly define which form of a deallocation function is a **usual** one. However, we didn't define which are placement allocation functions and which are placement deallocation functions. The meaning of the rule is unclear when we refer to placement allocation/deallocation functions within the rule.   

Consider this example
````cpp
struct S {
  static void* operator new(std::size_t n, std::align_val_t alignment);  // #1
  static void operator delete(void* ptr, std::align_val_t alignment);  // #2
};
S* p = new (std::align_val_t(alignof(S))) S;
````
In my view, `#1` is a placement allocation function while `#2` is a usual deallocation function as per [basic.stc.dynamic.deallocation] p3. This example is similar to [expr.new] example#7, however, implementations accept this example but reject [expr.new] example#7.   

resolution suggestion:    

> Define provision for placement allocation function
>> - A placement allocation function is an allocation function that has more than one parameter.   

> Define provision for placement deallocation function
>> - A placement deallocation function is a deallocation function that is not a usual deallocation function.  

A contrast version of [[expr.new] example#7](https://eel.is/c++draft/expr.new#example-7)
````cpp
#include <iostream>
struct S {
  // Placement allocation function:
  static void* operator new(std::size_t, std::size_t);

  // Usual (non-placement) deallocation function: it's not true
  template<class T>
  static void operator delete(void*, T);
};
int main(){
   S* p = new (0) S;
}
````
[basic.stc.dynamic.deallocation] p3 says
> A template instance is **never** a **usual deallocation function**, regardless of its signature[.](https://eel.is/c++draft/basic.stc.dynamic.deallocation#3.sentence-9)

Clang accepts this example while GCC rejects it, the diagnosis of GCC can obviously say it's wrong 
`<source>:8:15: note: 'static void S::operator delete(void*, T) [with T = long unsigned int]' is a usual (non-placement) deallocation function`

**Comment by jensmaurer** [comment]
Please report bugs in compilers to the respective vendor; the phrasing for "is never a usual deallocation function" is quite clear.

CWG2592 for the missing definitions.

**Comment by jensmaurer** [comment]
Yes, I think an alignment-enabled allocation function is also a usual allocation function; that's the intent of CWG2592. (This function will be invoked when no placement arguments are given in the /new-expression/, so it seems plausible not to call it a placement allocation function.)
