### ISSUE TITLE
[cpp.predefined] Missing feature-test macro for P0849 `auto(x)`

### ISSUE THREAD

**Issue by brevzin** [cplusplus/CWG#281]
Full name of submitter: Zhihao Yuan

Reference (section label): [cpp.predefined]

Link to reflector thread (if any): https://lists.isocpp.org/sg10/2022/01/0821.php

Issue description:

It's hard to detect whether it is legal to
do `auto(expr)` after adopting P0849R8;
A feature testing macro would help.
For example, libc++ currently has:
```cpp
#define _LIBCPP_AUTO_CAST(expr) static_cast<typename decay<decltype((expr))>::type>(expr)
```
which could instead become:
```cpp
#ifdef __cpp_auto_cast
#define _LIBCPP_AUTO_CAST(expr) auto(expr)
#else
#define _LIBCPP_AUTO_CAST(expr) static_cast<typename decay<decltype((expr))>::type>(expr)
#endif
```

Proposed resolution:

Add the entry:

```diff
+ __cpp_auto_cast 202110L
```

**Comment by jensmaurer** [comment]
@tkoeppe, can we do this editorially?

**Comment by tkoeppe** [comment]
Yes, I have no objection to adding this if it's OK with the feature-testing and the relevant wording group.

**Comment by ericniebler** [comment]
> Yes, I have no objection to adding this if it's OK with the feature-testing and the relevant wording group.

Paging @brevzin and @jwakely

**Comment by brevzin** [comment]
> Yes, I have no objection to adding this if it's OK with the feature-testing and the relevant wording group.

Okay with the SGX (I opened the issue)

**Comment by jensmaurer** [comment]
CWG teleconference 2023-04-28: Approved.

@tkoeppe , please go ahead and apply editorially.
