### ISSUE TITLE
CWG2720 [temp.res] template validity rules don't cover templates without specializations

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/CWG#286]
[temp.res.general]/6 gives the rules that determine when a template is valid, but it's specified in terms of "valid specializations". That doesn't seem like it can work for templates that don't have specializations, in particular for concepts and alias templates. Clearly the intent here is that the same rule applies everywhere -- any construct appearing as or within a templated entity is required to be valid for at least one substitution -- but it's currently at best unclear that that follows from the wording.

I think we should replace some or most of the mentions of "specializations" and "instantiations" in that paragraph with words that talk about substitutions being performed into the template. (Also, this paragraph means to talk about templated entities, not just templates.)

It seems sufficiently clear what this wording means to say that I think we can do this editorially, but it probably makes sense to run the result past CWG.

**Comment by jensmaurer** [comment]
Hm... [temp.res.general] p6.2 specifically discusses constraints, and [temp.alias] mentions "alias template specialization" quite a few times.

I do agree that alias templates are not instantiated, though.

**Comment by jensmaurer** [comment]
CWG2720

**Comment by zygoloid** [comment]
> Hm... [temp.res.general] p6.2 specifically discusses constraints, and [temp.alias] mentions "alias template specialization" quite a few times.

I think the suggested wording for CWG2720 addresses this, but the existing wording doesn't:

> any [constraint-expression](https://eel.is/c++draft/temp.constr.decl#nt:constraint-expression) in the program, introduced or otherwise, has (in its normal form) an atomic constraint A where no satisfaction check of A could be well-formed

but the conditions for a satisfaction check not being well-formed are that substitution *succeeds* and the result is not a converted constant expression of type bool. So there are two related problems here:

- This rule does not apply if *any* substitution into the atomic constraint can fail. Eg, we can't reject `void f() requires (void(T::value), 42)` despite it never being of type `bool` because substitution can fail.
- This rule does not apply if *every* substitution into the atomic constraint will fail, because the atomic constraint is semantically invalid, for example due to a non-dependent construct. Eg, we can't reject `void f() requires ("hello" * 3)` because substitution never succeeds, so every satisfaction check appears to be well-formed.
