### ISSUE TITLE
CWG2718 [expr.static.cast] p2 Derived class type should be complete

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#293]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[expr.static.cast] p2
> An lvalue of type “cv1 B”, where B is a class type, can be cast to type “reference to cv2 D”, **where D is a class derived from B**, if cv2 is the same cv-qualification as, or greater cv-qualification than, cv1.

The class type `D` should have a similar restriction to that in the other paragraphs. For example

[expr.static.cast] p12
> A prvalue of type “pointer to cv1 B”, where B is a class type, can be converted to a prvalue of type “pointer to cv2 D”, **where D is a complete class derived from B**, if cv2 is the same cv-qualification as, or greater cv-qualification than, cv1.

### Suggested Resolution

Change [expr.static.cast] p2 to
> An lvalue of type “cv1 B”, where B is a class type, can be cast to type “reference to cv2 D”, **where D is a **complete** class derived from B**, if cv2 is the same cv-qualification as, or greater cv-qualification than, cv1.

**Comment by frederick-vs-ja** [comment]
I originally thought this should be resolved editorially, but this looks like missed fix in CWG2310.

Should we make corresponding change in [[dcl.init.ref] p4](https://eel.is/c++draft/dcl.init.ref#4)?

**Comment by jensmaurer** [comment]
CWG2718
