### ISSUE TITLE
CWG2719 [intro.object] p3 The provided storage should satisfy the alignment requirement of the created object

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#294]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[intro.object] p3 says
> If a complete object is created ([expr.new]) in storage associated with another object e of type “array of N unsigned char” or of type “array of N std​::​byte” ([cstddef.syn]), that array provides storage for the created object if: 
>> - the lifetime of e has begun and not ended, and
>> - the storage for the new object fits entirely within e, and
>> - there is no array object that satisfies these constraints nested within e.

No bullet in the list explicitly mentions the alignment requirement of the object being created. [basic.life] p1 says
> The lifetime of an object of type T begins when: 
>> - **storage with the proper alignment** and size for type T is obtained, and  

The array with the element of type unsigned char or std​::​byte has **the weakest alignment requirement** per [basic.align] p6 and [expr.alignof] p3. That is, the storage provided by the array is not necessary to satisfy the alignment requirement of the object being created.

**Comment by frederick-vs-ja** [comment]
[[basic.align] p1](https://eel.is/c++draft/basic.align#1) seems already sufficient.

I think the intent is that when there's no suffient size after an properly aligned address for a `T` object in the array, a `T` object is simply not created at that address. E.g. given object definition `unsigned char buf[sizeof(int)];` without `alignas`, an `int` object can be created within it only if the array happens to be allocated at an address properly aligned for `int`.

**Comment by xmh0511** [comment]
> I think the intent is that when there's no suffient size after an properly aligned address for a T object in the array, a T object is simply not created at that address.

We do not say so. The rule simply states that the array will provide storage for the object if the bullets in the list are met. Even the referenced subclause [expr.new] does not place the requirement. 
> The new-expression attempts to create an object of the type-id ([dcl.name]) or new-type-id to which it is applied.

**Comment by xmh0511** [comment]
Incidentally, [basic.align] p1 use "may", "can" rather than "shall"
> Object types have alignment requirements ([basic.fundamental], [basic.compound]) which place restrictions on the addresses at which an object of that type **may be allocated**. An alignment is an implementation-defined integer value representing the number of bytes between successive addresses at which a given object **can be allocated**.

**Comment by languagelawyer** [comment]
> No bullet in the list explicitly mentions the alignment requirement of the object being created

And why it should?

> [basic.life] p1 says

So an array will provide storage for an object whose lifetime has never started (or, rather, this should be fixed separately and become UB)

**Comment by frederick-vs-ja** [comment]
> That's insufficient. Whether the lifetime of an object has begun or ended does not mean that the object is created or not. This is implied by [intro.object] p2
> 
> > If an object is created in storage associated with a member subobject or array element e (**which may or may not be within its lifetime**)
> 
> A member subobject is **called an object** regardless of whether the object is within its lifetime or not.

I don't see the relation. The member subobject or array element may be not created before.

There may be gaps in the specification that may allow some operations to create an object without starting lifetime, which needs to be fixed IMO.

**Comment by xmh0511** [comment]
@frederick-vs-ja  See my last comment, which literally negates your opinion: an object won't be created at the storage that does not satisfy the alignment requirement of the object. 

It is indeed created, merely its lifetime never begins.

**Comment by frederick-vs-ja** [comment]
> It is indeed created, merely its lifetime never begins.

I don't think this can be right. I think [basic.align] p1 implies a precondition to object creation. How can an object be created at an address where it can't be allocated?

**Comment by frederick-vs-ja** [comment]
> See https://github.com/cplusplus/CWG/issues/294#issuecomment-1502878812, I agree with @languagelawyer here, that is, the object is indeed created.

So how do you interpret [basic.align] p1 in this case? If we claim that the object is created, then it seems unavoidable to conclude that the object is allocated at some address that violates [basic.align] p1.

**Comment by xmh0511** [comment]
> > See [#294 (comment)](https://github.com/cplusplus/CWG/issues/294#issuecomment-1502878812), I agree with @languagelawyer here, that is, the object is indeed created.
> 
> So how do you interpret [basic.align] p1 in this case? If we claim that the object is created, then it seems unavoidable to conclude that the object is allocated at some address that violates [basic.align] p1.

As I said in the above comment, the wording uses "may", and "can" modal verbs, which arguably is a suggestion. If the wording implies the intent as you said, it should say:
> An object is created at the storage if and only if the address of the storage satisfies the alignment requirement imposed by the object type. 

Actually, the current wording does not imply this meaning.

**Comment by jensmaurer** [comment]
As a side note, the "may" here conveys permission, not possibility, per ISO drafting rules.

In any case, I think we should explicitly say somewhere that it's undefined behavior to attempt to create an object in too-small storage or in misaligned storage. This also covers implicitly created objects, because possibly implicitly-created objects that are too big to fit into the storage won't satisfy the "no UB" rule and thus won't be created to start with.

**Comment by frederick-vs-ja** [comment]
> As I said in the above comment, the wording uses "may", and "can" modal verbs, which arguably is a suggestion.

Such reading seems contradictory. If the first sentence of [basic.align] p1 can be merely a suggestion, then it's wrong to say "place restrictions".

**Comment by jensmaurer** [comment]
CWG2719
