### ISSUE TITLE
[namespace.udecl]/11 Ambiguity in hiding of using declarations

### ISSUE THREAD

**Issue by seanbaxter** [cplusplus/CWG#298]
Compilers give different results on this code:
https://godbolt.org/z/T1r31PKdY

> [namespace.udecl]/11
> The set of declarations named by a using-declarator that inhabits a class C does not include member functions and member function templates of a base class that correspond to (and thus would conflict with) a declaration of a function or function template in C.

What does _would conflict mean_? I think MSVC is right by treating the call as ambiguous, since function templates may be overloaded by return type, and thus would not conflict. But the wording is too vague to know the intent of the Standard.

**Comment by jensmaurer** [comment]
"correspond" is defined in [basic.scope.scope] p4; you can ignore the parenthetical or go to [basic.scope.scope] p5 for a definition.

Reading the rules there, it seems that A::operator+= and B::operator+= do not correspond (different return types) and thus both should be visible to overload resolution and thus cause an ambiguity. Please file bug reports with the vendors.

I'm not seeing a defect in the standard.
