### ISSUE TITLE
[namespace.std] p1 Which namespace `std` is the mentioned one? 

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#299]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[namespace.std] p1 says
> Unless otherwise specified, the behavior of a C++ program is undefined if it adds declarations or definitions to **namespace `std` or to a namespace within namespace `std`**.

Which `std` namespace does the rule intend to refer to? Does the text refer to any namespace named `std`? Consider this case
````cpp
namespace A{
   namespace std{  // UB or not? 
      void show(){}
      namespace B{
         void fun(){}  // UB or not? 
     }
  }
}
int main(){
   
}
````
#### Suggested resolution 
A resemble usage like the above example can be seen in https://github.com/NVIDIA/libcudacxx, for example
````cpp
#include <cuda/std/atomic>
cuda::std::atomic<int> x;
````
Does the standard intend to prohibit any user-defined namespace called `std`, or just the namespace called `std` that inhabits the global scope? If the intent is the latter, we may want to say
> Unless otherwise specified, the behavior of a C++ program is undefined if it adds declarations or definitions to namespace `std`  or to a namespace within namespace `std`, where the namespace `std` refers to the namespace **whose declaration inhabits the global scope**.

[namespace.std] p2, p7 that refers to namespace `std` have a similar issue.

**Comment by frederick-vs-ja** [comment]
Perhaps we shouldn't only make clarification here. If I understand correctly, "namespace `std`" always refers to `::std` in the standard (including the core wording), but clarification seems missing.

**Comment by xmh0511** [comment]
It's [LWG3926](https://cplusplus.github.io/LWG/issue3926)
