### ISSUE TITLE
CWG2533 [basic.stc] storage duration of objects created by an operation implicitly creating objects

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/CWG#3]
https://lists.isocpp.org/core/2020/10/9978.php

Full name of submitter (unless configured in github; will be published with the issue): Andrey Erokhin

Reference (section label): [basic.stc]

Issue description:
[basic.stc] ([basic.stc.general]/2) doesn't specify storage duration of objects implicitly created by operations specified to do this (http://eel.is/c++draft/intro.object#def:object,implicit_creation)

**Comment by jensmaurer** [comment]
CWG2533

**Comment by languagelawyer** [comment]
Not sure I agree that storage duration of objects created by a _new-expression_ should depend on used allocating function.

**Comment by languagelawyer** [comment]
> If you placement-new into an array of `char` on the stack

And when `char` array is on the stack? Like, in a coroutine, objects created by definitions have automatic storage duration, even though the storage for them may be allocated by `operator new`. Will storage duration of an object created inside such an array depend on whether `operator new` were used or it was elided and the coroutine frame is «allocated on the stack»?

**Comment by jensmaurer** [comment]
The nominal storage duration for coroutine stuff is still "automatic storage duration", I think.

All I'm saying is that a placement-new into an array of `char` cannot change the (already well-defined) storage duration of that array of `char`, which thus also defines the storage duration of the object created via placement-new. "placement-new" simply has no effect on storage duration, because it doesn't actually come up with fresh storage (unlike allocating variants of operator new).

**Comment by languagelawyer** [comment]
> "placement-new" simply has no effect on storage duration, because it doesn't actually come up with fresh storage (unlike allocating variants of operator new)

But the so-called «allocating» variants can be substituted by user-defined ones, which I think can «allocate» from a static array. Will this be reflected in storage duration wording or objects for which memory was allocated in such way will still have dynamic storage duration?

**Comment by jensmaurer** [comment]
The user-defined case returning memory from a static array will not affect the nominal storage duration returned by allocating operator new, i.e. dynamic storage duration.

**Comment by languagelawyer** [comment]
What about https://timsong-cpp.github.io/cppwp/n4868/basic.indet#1?
