### ISSUE TITLE
CWG2567 [class.member.lookup] Operator lookup ambiguity

### ISSUE THREAD

**Issue by wmm-at-edg** [cplusplus/CWG#30]
I'd like to see an issue for the question Daveed Vandevoorde asked in https://lists.isocpp.org/core/2022/04/12231.php, in light of the implementation divergence.

To reiterate the question, [over.match.oper] paragraph 3 describes the lookup for an overloaded operator as the union of the results of four separate lookups, for member, non-member, built-in, and rewritten candidates. The question is whether an ambiguity in one of those lookups invalidates the entire lookup for the operator or only means that the lookup for that particular candidate contributes nothing to the union.

The example that occasioned the question is:

struct B1 {
  bool operator==(B1 const&) const;
};
struct B2 {
  bool operator==(B2 const&) const;
};
struct D: B1, B2 {} d;
bool operator==(D const&, D const&);

auto r = d == d;  // (1). Ambiguous?

g++ reports an error, while clang and MSVC choose the non-member candidate.

[class.member.lookup] paragraph 6 says that if the lookup result is invalid (i.e., ambiguous), the program is ill-formed; it makes no provision for simply failing if the lookup is invoked as part of some larger lookup, as in the case of the overloaded operator lookup. However, it's not clear that this was intended or desirable. To support the clang/MSVC behavior, it could be rephrased as something like, "If the declaration set of S{N,T} is invalid, the result is an empty set; otherwise, the result is that set.", which would still leave the program ill-formed if a standalone class member lookup returned an empty set but would not make the above example ill-formed.

**Comment by jensmaurer** [comment]
CWG2567
