### ISSUE TITLE
CWG2722 [expr.unary.noexcept] Specification of noexcept operator is still unclear about temporary materialization conversion

### ISSUE THREAD

**Issue by t3nsor** [cplusplus/CWG#301]
**Full name of submitter**: Brian Bi

**Reference (section label)**: [expr.unary.noexcept]

**Issue description**: The drafting note for [CWG 1354](https://wg21.link/cwg1354) says that `noexcept(A())` requires the destructor of `A` to be accessible and non-deleted, which seems to imply that the temporary materialization conversion is applied to the prvalue `A()`. However, while the resolution to CWG 1354 undoubtedly requires the destruction of temporaries created within an unevaluated operand, there is no normative wording that requires the temporary materialization conversion to be performed on the operand of `noexcept`. In contrast, there is already normative wording stating that the operands of `sizeof` and `typeid` are subject to the temporary materialization conversion, and that the operand of `decltype` is not.

**Suggested resolution**: Edit [expr.unary.noexcept]/3:

> <ins>If the operand is a prvalue, the temporary materialization conversion ([conv.rval]) is applied. </ins>The result of the `noexcept` operator is `true` unless the *expression* <ins>(including any temporary materialization conversion) </ins>is potentially-throwing ([except.spec]).

**Comment by jensmaurer** [comment]
CWG2722
