### ISSUE TITLE
[namespace.udir] Changing the note to a normative clause and append an additional example

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#302]
Full name of submitter (unless configured in github; will be published with the issue): Anoop Rana

Reference (section label): [namespace.udir] 

Link to reflector thread (if any): https://stackoverflow.com/questions/76099741/using-declaration-compiles-in-gcc-and-msvc-but-rejected-in-clang

Issue description: It is not clear if the following program is ill-formed at point labeled `#1` or at point `#2`. By reading [namespace.udir#6] it seems that the program is ill-formed at point `#2` in C++23 but ill-formed at point `#1` in C++20. Also this seems to a non-normative note. It should be changed to a clause and the below given example should be added with appropriate comment indicating the line/statement due to which the program is ill-formed.  [demo](https://godbolt.org/z/1Tsx54ro5)

```
namespace X 
{ 
    struct type {}; 
}
namespace Y 
{ 
    using type = int; 
}
using X::type;
using Y::type;   //#1:
int main()
{
    auto i = sizeof(type); //#2: gcc and msvc accepts this but clang rejects this
}
```

Currently C++23  public draft's [namespace.udir#6] says:

> [Note 6 : If name lookup finds a declaration for a name in two different namespaces, and the declarations do not
declare the same entity and do not declare functions or function templates, the use of the name is ill-formed (6.5). In
particular, the name of a variable, function or enumerator does not hide the name of a class or enumeration declared
in a different namespace...

(end quote)

The above seems to suggest that program is invalid due to `#2`. While c++20 public draft's [basic.scope.declarative](https://timsong-cpp.github.io/cppwp/n4868/basic.scope#declarative-4) says:

> Given a set of declarations in a single declarative region, each of which specifies the same unqualified name,
>
> * they shall all refer to the same entity, or all refer to functions and function templates; or
> * exactly one declaration shall declare a class name or enumeration name that is not a typedef name and the other declarations shall all refer to the same variable, non-static data member, or enumerator, or all refer to functions and function templates; in this case the class name or enumeration name is hidden ([basic.scope.hiding]).

(end quote)

The above seems to suggest that the program is invalid due to `#1`. 

So, C++23's non-normative note [namespace.udir#6] should be made a separate clause and the above program should be added as an example to indicate that the program is invalid at `#2`. 

<h4>Suggested resolution:</h4>

Add the above example in the standard(in appropriate section) and indicating the the program is ill-formed due to `#2`. 

---

Side note:

Better title for this post can be suggested.

**Comment by languagelawyer** [comment]
@opensdh would be nice to hear your comment about interaction of http://eel.is/c++draft/namespace.udir#6 (http://eel.is/c++draft/basic.lookup.general#1.sentence-5) with http://eel.is/c++draft/basic.lookup.general#4.sentence-2.

http://eel.is/c++draft/basic.lookup.general#4.sentence-2 apply only to single search in a scope S, and that the result of using-declarations replacement (http://eel.is/c++draft/basic.lookup.general#3.sentence-2) "pulls" declarations from different namespaces doesn't change the fact that it was single search in S.  Right?

**Comment by languagelawyer** [comment]
Seems correct; «denote different entities» in  http://eel.is/c++draft/basic.scope.scope#def:potentially_conflict is a bit confusing because _typedef-name_ is not an entity, but I think this definition intends to cover this case.

**Comment by jensmaurer** [comment]
So, not a bug, then: using-directives never cause conflicts at declaration time (only for lookups), but using-declarations can cause conflicts, and those are specified in the wording as ill-formed. The example at the top shows a using-declaration and the explanatory text quotes wording from using-directives.

**Comment by opensdh** [comment]
It's hard to be sure (which was a problem!), but I think C++20 rejects #1 as well per [namespace.udecl]/12.
