### ISSUE TITLE
[except.throw] p4 Where is the point of the potential destruction of the exception object if the exception-declaration declares a reference?

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#303]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[except.throw] p4 says
> The points of potential destruction for the exception object are: 
>> - when an active handler for the exception exits by any means other than rethrowing, immediately **after the destruction of the object (if any)** declared in the exception-declaration in the handler;

So, what if the *exception-declaration* only declares a reference? The mentioned rule only defines the point of potential destruction if the *exception-declaration* declares an object. Consider the corresponding example:
````cpp
struct MyError:std::exception{
    char const* what(){
        return nullptr;
    }
    ~MyError(){
        std::cout<<"destroy\n";
    }
};
int main(){
     try{
        throw MyError{};
    }catch(std::exception& e){  // declares a reference
        std::cout<<"handle\n";
    }
    std::cout<<"main\n";
}
````

The bullet in terms of `object` obviously does not define the point of potential destruction in this case. 

### Suggested resolution
Presumably, it is similar if the *exception-declaration* declares a reference. Change the first bullet to
> The points of potential destruction for the exception object are:
>> -  when an active handler for the exception exits by any means other than rethrowing, immediately after the destruction of an object as if the object was declared in the *exception-declaration*.

**Comment by jensmaurer** [comment]
What's unclear about "when an active handler for the exception exits by any means other than rethrowing"?  The "immediately after" part doesn't apply to references, as you correctly observe, but since there's no object to destroy "at exit", there is no sequencing to establish. The same reasoning applies for a handler that doesn't declare anything (i.e. `catch(...)`).

**Comment by xmh0511** [comment]
> What's unclear about "when an active handler for the exception exits by any means other than rethrowing"? The "immediately after" part doesn't apply to references, as you correctly observe, but since there's no object to destroy "at exit", there is no sequencing to establish, so nothing is lost. The same reasoning applies for a handler that doesn't declare anything (i.e. `catch(...)`).

The unclear part is we don't know when the exception object is destroyed in these cases.

**Comment by jensmaurer** [comment]
What's unclear about "when an active handler for the exception exits by any means other than rethrowing"?

**Comment by xmh0511** [comment]
> What's unclear about "when an active handler for the exception exits by any means other than rethrowing"?

Oh, there are two reading for this wording:
> 1. The points of potential destruction are immediately after destruction of the object (if any) declared ... if an active handler for the exception exits by any means other than rethrowing
>2. The points of potential destruction are the point when an active handler for the exception exits by any means other than rethrowing, and immediately after the destruction of the object if the exception-declaration declares the object. 


The first reading is based on we define the point if the conditon "an active handler for the exception exits by any means other than rethrowing" is met.

**Comment by jensmaurer** [comment]
That's why we use "when", which is temporal, and not "if", which indicates a condition. "I go home when the sun is rising" does not establish a condition, either.
