### ISSUE TITLE
[over.match.class.deduct] Allowing multiple template parameter packs in class templates that can be deduced using CTAD

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#306]
Full name of submitter (unless configured in github; will be published with the issue): Anoop Rana

Reference (section label): [over.match.class.deduct]

Link to reflector thread (if any):

**Issue description:**

Currently the standard does not allow the use of multiple template parameter packs in class templates. But since C++17 added CTAD, it should be possible to have multiple template parameter packs in a class template **as long as** those can be deduced using CTAD. This is like multiple template parameter packs are already allowed by the standard in "function templates" as long they can be deduced. 

Below is an example demonstrating the issue:

```
//this is allowed and works as expected using deduction
template< typename... Param,typename Ret, typename... Args>  
void doStuff(Ret (*ptrFunc)(const Param&... param),const Args&... args)
{

}


//this is not allowed according to the current wording but should be allowed from C++17(&onwards) since we have CTAD
template< typename... Param,typename Ret, typename... Args>  
struct C
{
    C(Ret (*ptrFunc)(const Param&... param),const Args&... args);
};
```
As we can see [here](https://godbolt.org/z/5TxzYxM8d) all compilers are standard conformant and allow multiple template parameter packs in function templates. But since the current wording doesn't allow multiple template parameter packs in class template even if they can be deduced using CTAD, the program is currently rejected by all compilers.

I suggest that the [shown](https://godbolt.org/z/5TxzYxM8d) class template `C` in the above program should be allowed since the template arguments can be deduced using CTAD. If on the other hand, CTAD cannot be used to deduce those multiple template parameter packs, then the program should be rejected. This is the same behavior as in function templates where the function template will also be rejected if the multiple template parameter pack cannot be deduced.

<h3>Suggested resolution:</h3>

I suggest that the [shown](https://godbolt.org/z/5TxzYxM8d) class template `C` in the above program should be allowed since the template arguments can be deduced using CTAD. This will make CTAD more intuitive and also make it behave more like normal template argument deduction(functionally atleast) with function templates.

<h3>Note</h3>

I think this issue is somewhat similar to [cwg2450](https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#2450) where it was notices that since C++17 allows class type nontype template parameters, so braced init list should be valid template arguments for those. There(in cwg2450) also it was noted that the current wording did not allow braced init list as template argument for class non type template parameters. 

This issue is similar to that(cwg2450) because here also it is noted that c++17 has added a new feature and so multiple template parameter can be allowed as long as they can be deduced using CTAD but current wording does not allow that.

**Comment by jensmaurer** [comment]
This doesn't seem to be a defect in the language. Feel free to write a proposal targeted at EWG, though.

I'm rejecting the argument that some other core issue appeared to be a similar corner-not-allowed-case, and thus the present issue should be a core issue, too.
