### ISSUE TITLE
CWG2569 [expr.prim.id.unqual] Use of decltype(capture) in parameter-declaration-clause

### ISSUE THREAD

**Issue by brevzin** [cplusplus/CWG#31]
Reference (section label): [expr.prim.id.unqual]

Issue description:

[P2036](https://wg21.link/p2036) changed the scope of lambda's _trailing-return-type_ and also tried to clean a few things up with respect to use of capture in certain contexts. The problem with unevaluated use of capture _early_ in lambdas is that we don't yet know if the lambda is `mutable` and so we don't know how to interpret the capture. The paper made problematic uses of capture ill-formed.

The problem is, there _are_ some uses of such in the wild. As in [libstdc++](https://github.com/gcc-mirror/gcc/blob/587953f0931d6af870c8f8fdba64985a27836914/libstdc%2B%2B-v3/include/debug/safe_unordered_container.h#L66-L73), which has a lambda that looks like this:

```cpp
[local_end](decltype(local_end) it){ return it != local_end; };
```

Since P2036 was a DR, this retroactively breaks libstdc++. 

While many unevaluated uses of capture can be be problematic -- `decltype(f(local_end))` could be, for instance -- this _specific_ case of `decltype(unparenthesized-id-that-names-a-capture)` is totally fine. We could carve out this specific case to avoid retroactively breaking libstdc++.

Suggested resolution:

Add the carve out to this bullet:

* If either P is in E’s function parameter scope but not its parameter-declaration-clause <ins>or the _unqualified-id_ is the _expression_ of a _decltype-specifier_</ins>, then the type of the expression is the type of a class member access expression ([[expr.ref]](https://eel.is/c++draft/expr.ref)) naming the non-static data member that would be declared for such a capture in the object parameter ([[dcl.fct]](https://eel.is/c++draft/dcl.fct)) of the function call operator of E[.](https://eel.is/c++draft/expr.prim.id.unqual#3.1.sentence-1)

And then change the example:

```diff
+ [=]<decltype(x) P>{};         // ok: P has type float
- [=]<decltype(x) P>{};         // error: x refers to local entity but precedes the
+ [=]<decltype((x)) P>{};       // error: x refers to local entity but precedes the
                                // lambda's function parameter scope
  [=](decltype((x)) y){};       // error: x refers to local entity but is in the lambda's
                                // [parameter-declaration-clause](https://eel.is/c++draft/dcl.fct#nt:parameter-declaration-clause)
```

**Comment by jensmaurer** [comment]
Is there any reason to single out the _decltype-specifier_ context, or should we allow any unevaluated operand (e.g. `sizeof` seems fine, too)? And p3.2 in [expr.prim.id.unqual] repeats the negated condition of p3.1 in parentheses, so needs adjustment as well.

**Comment by brevzin** [comment]
No, that's just the one that Wakely pointed me to. `sizeof` would work just fine too. Any context in which we know for sure the... `mutable`-ness... of the lambda would not affect the result. Is there a third one?

Yeah the negated p3.2 case would now be... quite complicated...

**Comment by jensmaurer** [comment]
`noexcept` would also work.

But `typeid` wouldn't, I think, so "unevaluated operand" doesn't quite refer to the right thinig.

**Comment by brevzin** [comment]
I suppose could introduce a term like (this might not be quite right for `sizeof`, want to cover `sizeof a` and `sizeof(a)` but not like `sizeof f(a)`):

> An _unqualified-id_ is _mutable-agnostic_ if it is either the _expression_ of a _decltype-specifier_ or the operand of a `sizeof` operator expression.

Which then lets you do the negation slightly nicer:

> * If <ins>either</ins> P is in E’s function parameter scope but not its parameter-declaration-clause <ins>or the _unqualified-id_ is mutable-agnostic</ins>, then the type of the expression is the type of a class member access expression ([[expr.ref]](https://eel.is/c++draft/expr.ref)) naming the non-static data member that would be declared for such a capture in the object parameter ([[dcl.fct]](https://eel.is/c++draft/dcl.fct)) of the function call operator of E[.](https://eel.is/c++draft/expr.prim.id.unqual#3.1.sentence-1)
> 
> * Otherwise (if P either precedes E's function parameter scope or is in E's parameter-declaration-clause <ins>or the _unqualified-id_ is not mutable-agnostic</ins>), the program is ill-formed.

**Comment by jensmaurer** [comment]
CWG2569

The last bullet needs "and", not "or", per rules of boolean logic.
Also, I've swapped the two parts, which seemed easier to read.

**Comment by cor3ntin** [comment]
@brevzin Thanks for creating this issue, I was about to send a mail to core. We also had one such instance in LLVM.
I suspect part of the issue is that generic lambda were not available in c++11, and so `decltype` might have been used to work around that.
I will implement the remediation, which seems reasonable

**Comment by cor3ntin** [comment]
On second thought, what is the criteria to determine what a `mutable-agnostic` expression is?
Would anything be lost if `decltype` was the only special case here? Do we really think allowing `sizeof` in particular is useful? (The implementation can get hairy)

**Comment by jensmaurer** [comment]
Well, `sizeof` seems not much different from `decltype`: If you know the type, you should also know its size. And the type is complete,because it's a capture.

For me, the criterion for "mutable-agnostic" was "unevaluated operand" as a first approximation, except where this doesn't work (e.g. `typeid`).

**Comment by jwakely** [comment]
> although, breaking code by changing language mode is not much better than doing it unconditionally

It is much better. As it stands, Clang 14 (or any other compiler that implements this DR unconditionally) would be incompatible with all released versions of libstdc++ installed everywhere in the world. Updating the C++ headers on the system is not always an option, or might happen on a slower schedule than updating to a newer Clang that consumes those headers. If it's a C++23-specific change, users have the option to continue using any older mode without problems. If it's unconditional, they don't have that option.

"To use the latest `-std` option you need updated C++ library headers" is entirely justifiable. Everybody understands that "those headers installed in 2017 do not support C++23 well". But "those headers installed in 2017 are no longer compatible with C++11 mode" is harder to justify.

</vendor>

**Comment by jensmaurer** [comment]
@cor3ntin, I think just reverting P2036R3 would require a conforming implementation to token-stash the _parameter-declaration-clause_ of a lambda,  check for `mutable`, and then analyze the _parameter-declaration-clause_ for real. That seems like a non-trivial burden.

Please move further technical discussion here: http://lists.isocpp.org/core/2022/04/12341.php
