### ISSUE TITLE
CWG2523 [basic.life] Meaningless wording regarding whether a program "depends on the side effects produced by the destructor"

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/CWG#32]
Full name of submitter (unless configured in github; will be published with the issue): 

Reference (section label): [basic.life], currently paragraph 5.

Link to reflector thread (if any):
https://lists.isocpp.org/core/2016/04/0322.php, but the relevant messages are https://lists.isocpp.org/core/2016/04/0336.php onwards.

Issue description: Current wording:

> In this case, the destructor is not implicitly invoked and any program that depends on the side effects produced by the destructor has undefined behavior.

The latter half of this sentence has no clear meaning. What does it mean for a program to "depend on the side effects produced by the destructor", given that the destructor doesn't even run? How can you depend on something that doesn't happen?

Perhaps this means:

a) the program depends on the side effects if it would have undefined behavior if they don't happen (which they don't): this would mean the second half of the sentence has no normative effect and can be struck
b) the program depends on the side effects if it would have different observable behavior if (in violation of the standard) the destructor were actually invoked by the implementation when the object's lifetime ended
c) something else

Also, during constant evaluation, an implementation is required to detect and diagnose all undefined behavior. What is the intended behavior for an implementation here? Under option (b), it would presumably need to fork its evaluation and see what would happen if the destructor did run, in case that resulted in some observable effect. See also core issue 2523, where someone  has concluded that option (b) is intended and reached this conclusion.

Suggested resolution: Change in [basic.life] paragraph 5:

>  In this case, the destructor is not implicitly invoked<ins>.</ins> <del>and any program that depends on the side effects produced by the destructor has undefined behavior.</del> <ins>[Note: It is common for the correct behavior of a class to depend on the destructor being invoked for each instance of the class.]</ins>

I'm not sure we want a note here at all, but discussion on the reflector suggested that people wanted *something* here.

**Comment by jensmaurer** [comment]
I've amended CWG2523 accordingly.

**Comment by xmh0511** [comment]
A friendly reminder and of course an off-topic. Consider this example
````cpp
using T = std::unique_ptr<int>;
auto ptr = new T(new int);  // manage a int object.
new(ptr) T;  // reuse the storage
````
 Here, the invocation of the destructor of `T` involves the release of the memory for `int`, does it mean even the memory leak of the resource `int`, the program at least is well-defined after CWG2523?

**Comment by jensmaurer** [comment]
> A friendly reminder

I don't know what you mean. I've create a core issue and I've linked to it. CWG will deal with the core issue in due course, which might take a decade or so, depending on priorities and workload.

The example you gave should be fine after CWG2523.

**Comment by xmh0511** [comment]
> I don't know what you mean. 

I just think the current wording (might)wants to express that the memory leak is a kind of UB, although "depend on the side effect" is not clear and can be freely read out several opinions. However, once after applying CWG2523, the pure memory leak seems to be fine(well-defined) in the program. It seems that you have confirmed this case and therefore is a deliberate intent of CWG2523.

**Comment by frederick-vs-ja** [comment]
> I just think the current wording (might)wants to express that the memory leak is a kind of UB, although "depend on the side effect" is not clear and can be freely read out several opinions.

Memory leak itself definitely doesn't result in UB.

I guess the original intent was to require programs to behave as if "ending of the lifetime of a class object" and "destructor call for that object" always happen together, even though the destructor call is not exactly always required.

**Comment by frederick-vs-ja** [comment]
This issue is strongly related to CWG2361. If we remove the UB in [basic.life] p5, then we should also resolve CWG2361 by removing the UB about destructor call in [csetjmp.syn].
