### ISSUE TITLE
CWG2733 [dcl.attr.unused] Applying `[[maybe_unused]]` to a label

### ISSUE THREAD

**Issue by brevzin** [cplusplus/CWG#325]
Reference (section label): [dcl.attr.unused]

Issue description: The wording in [dcl.attr.unused]/2 currently reads:

> The attribute may be applied to the declaration of a class, a [typedef-name](https://eel.is/c++draft/dcl.typedef#nt:typedef-name), a variable (including a structured binding declaration), a non-static data member, a function, an enumeration, or an enumerator[.](https://eel.is/c++draft/dcl.attr#unused-2.sentence-1)

Missing from that list is a label. But it appears that gcc and clang both accept [[maybe_unused]] on a label too, and do silence the associated unused warning.

Suggested resolution:

> The attribute may be applied to <ins>labels or</ins> the declaration of a class, a [typedef-name](https://eel.is/c++draft/dcl.typedef#nt:typedef-name), a variable (including a structured binding declaration), a non-static data member, a function, an enumeration, or an enumerator[.](https://eel.is/c++draft/dcl.attr#unused-2.sentence-1)

**Comment by jensmaurer** [comment]
"label"s are not "declared" in the sense of declarations.

In any case, I'm not seeing this as a wording defect; did the paper introducing [[maybe_unused]] talk about labels at all?

**Comment by brevzin** [comment]
> Well, namespaces can be unused, too, but aren't covered, I guess.

Nobody seems to warn on unused namespaces tho. We could add it to the list anyway tho?

**Comment by frederick-vs-ja** [comment]
FYI the missing piece is added in C23 by [WG14 N2662](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2662.pdf).

**Comment by jensmaurer** [comment]
Thanks for the pointer. So, the WG14 paper also believes labels are "declared", which they aren't.

Oh, and the rest of [dcl.attr.unused] also talks about "name or entity", but a label is neither, so more edits are needed.

**Comment by jensmaurer** [comment]
CWG2733; note expanded suggested resolution

**Comment by brevzin** [comment]
Thank you Jens!
