### ISSUE TITLE
[expr.unary.op] Why make an exception of operator precedence with pointer to member function syntax

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#329]
Full name of submitter (unless configured in github; will be published with the issue): Anoop Rana

Reference (section label): [expr.unary.op]

Link to reflector thread (if any):

**Issue description:**

The standard makes an exception to precedence rules when it comes to member function pointer syntax. For example, in the below shown program, the syntax `&(C::Bar)` is explicitly forbidden(disallowed) by [expr.unary.op#4]. Is there a reason why the normal operator precedence rules are not applied here. I mean I would expect that `&C::Bar` is grouped as(or equivalent to writing) `&(C::Bar)` and so the latter should be allowed(since the former is allowed and since they are equivalent in form). There doesn't seem to be a good reason to disallow the latter by making an exception to the normal precedence rules. 

This exception also makes the language(this part of the language to be specific) little inconsistent and unintuitive in my understanding. Here is the example for which we notice [implementation divergence](https://godbolt.org/z/PdYsv4T3n):

```
struct C
{
    void Bar(int);
};
int main()
{
    void (C::*ptr)(int) = &(C::Bar); //compiles with msvc but both gcc and clang rejects this
} 
```

<h3>Suggested resolution:</h3>

Allow the use of `&(C::Bar)` and make this part of the language more consistent and intuitive.

**Comment by jensmaurer** [comment]
I think the standard is clear as written, in particular considering [expr.unary.op] p4, including the note. Feel free to submit a bug report for the implementation that disagrees.

This is a long-standing rule (including the apparent inconsistency), and I'm not seeing a CWG-level defect here.
If you wish for a change to happen, please write a paper to EWG.
