### ISSUE TITLE
CWG2775 [except.throw] Wording about "the thrown object" needs overhauling

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/CWG#332]
Full name of submitter (unless configured in github; will be published with the issue): Jiang An

Reference (section label): [except.throw]

Link to reflector thread (if any):

Issue description:

The wording in [[except.throw] p5](https://eel.is/c++draft/except.throw#5) is out of sync. It predated [P0135R1](https://wg21.link/p0135r1) which made the thrown operand of a class type not necessarily an object, and [P0848R3](https://wg21.link/p0848r3) which made the selected constructor for a copy-initialization possibly non-existent. Some of its contents will be covered by CWG2711.

It seems that all mainstream implementations lack the checking required by CWG1863.

Additionally, it's unclear in which context the access checking is performed when the checking is needed for a constructor. It might be better to clarify that the exception object is always of a cv-unqualified object type, even if it is generated by the implementation in a way other than a throw-expression.

Suggested resolution:

Change [except.throw] p3 as indicated:
> Throwing an exception copy-initializes ([dcl.init], [class.copy.ctor]) a temporary object <ins>**of a _cv_-unqualified type**</ins>, called the _exception object_. <ins>**Let `T` denote the type of the exception object.**</ins> If ~the type of the exception object~ <ins>**`T`**</ins> would be an incomplete type, an abstract class type ([class.abstract]), or a pointer to an incomplete type other than _cv_ `void` the program is ill-formed. <ins>**Copy-initialization of an object of the type `T` from an lvalue of type `T`, where the access checking for the selected constructor (if any) is performed in a context unrelated to any class, shall be well-formed. When `T` is a class type, the destructor for `T` is potentially invoked ([class.dtor]).**</ins>
> <ins>**[_Note_ ?: Copyability of the exception object may be needed for standard library functions `current_exception` and `rethrow_exception` ([propagation]). — _end note_]**</ins>

Delete the whole [except.throw] p5 (the contents are moved to p3, modulo CWG2711).
> ~When the thrown object is a class object, the constructor selected for the copy-initialization as well as the constructor selected for a copy-initialization considering the thrown object as an lvalue shall be non-deleted and accessible, even if the copy/move operation is elided ([class.copy.elision]). The destructor is potentially invoked ([class.dtor]).~

Add a paragraph after [propagation] p8:
> <ins>**?. _Remarks_: If the exception object is copied, the source is treated as a _cv_-unqualified lvalue and copy-initialization is performed.**</ins>

Add a paragraph after [propagation] p10:
> <ins>**?. _Remarks_: If the referred-to object is copied, the source is treated as a _cv_-unqualified lvalue and copy-initialization is performed.**</ins>

Drafting notes: It's not clear to me whether access checking is wanted. Also, given LWG3843 requires `is_copy_constructible_v<E>` to be `true`, perhaps we should consider the source as const-qualified instead of cv-unqualified.

**Comment by xmh0511** [comment]
Together with the discussions in https://github.com/cplusplus/draft/issues/5238.

**Comment by jensmaurer** [comment]
CWG2711 is currently in flight. I'd like to avoid any editing conflicts, so I'll deal with this post-Varna.

**Comment by jensmaurer** [comment]
CWG2775
