### ISSUE TITLE
[intro.defs] Rename the term "initial function" to "associated function" and add it's missing definition

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#333]
Full name of submitter (unless configured in github; will be published with the issue): Anoop Rana

Reference (section label): [intro.defs]

Link to reflector thread (if any): https://github.com/cplusplus/CWG/issues/241

**Issue description:**

[Issue](https://github.com/cplusplus/CWG/issues/241) noted that the term _initial_function_ has not been defined while it is used at various places in the standard. Further, I think the term should be changed/renamed to be called **associated function**. This term(i.e associated function) seems more appropriate given that there are term like _associated namespaces_ already in use in the standard. 

<h3>Suggested resolution:</h3>

Change the term "initial function" to "associated function" and add the corresponding definition to [intro.defs].

**Comment by jensmaurer** [comment]
There is a clear "first" function that is invoked in a thread, so I personally think "initial function" is a fine name, and "associated function" is strictly worse.

**Comment by ranaanoop** [comment]
I see, so as long as that "clear first function" gets defined(which
currently is not), it's fine. Though I would prefer the term  "associated
function" over terms like "initial function" or "first function". But
again, that is only my opinion/preference.

**Comment by tahonermann** [comment]
My preferences align with Jens'. As a thread continues execution it will acquire additional "associated" functions, but there will only ever be one "initial" function; the one passed to the `std::thread` constructor.

**Comment by frederick-vs-ja** [comment]
> the one passed to the `std::thread` constructor

There may be arguably no such a function, since we can pass a pointer to data member to the constructor.

**Comment by tahonermann** [comment]
> There may be arguably no such a function, since we can pass a pointer to data member to the constructor.

In either case, per [\[thread.thread.constr\]p5](https://eel.is/c++draft/thread.thread.constr#5), `std::invoke()` is arguably the initial function.

**Comment by jensmaurer** [comment]
There seem to be no additional issues left beyond those discussed in #241, thus closing this item.
