### ISSUE TITLE
CWG2572 [over.over] resolution in context with no target

### ISSUE THREAD

**Issue by jicama** [cplusplus/CWG#34]
Reference (section label): [over.over]

Issue description:

After P1787 removed the [temp.arg.explicit] handling of template-ids in non-deduced context, the operative wording is [over.over]:

> The specialization, if any, generated by template argument deduction for each function template named is added to the set of selected functions considered....
> Any given function template specialization F1 is eliminated if the set contains a second function template specialization whose function template is more specialized than the function template of F1 according to the partial ordering rules of [[temp.func.order]].

This seems to mean that for

```
template <class T> T f(T); // 1
template <class T> T* f(T*); // 2
auto p = &f<int>;
```

We're supposed to unambiguously choose 2, because the template is more specialized. This seems surprising, and differs from existing practice: GCC, Clang, EDG reject the above as ambiguous.

Suggested resolution:

In the case where there is no target, I think we should only consider whether one template is more constrained than the other.

**Comment by jensmaurer** [comment]
CWG2572

Please have a look. I've added suggested wording.

**Comment by jicama** [comment]
Looks good to me, thanks.
