### ISSUE TITLE
CWG2751 [stmt.dcl] Destruction order of parameter objects of operator functions

### ISSUE THREAD

**Issue by t3nsor** [cplusplus/CWG#346]
**Full name of submitter**: Brian Bi

**Reference (section label)**: [stmt.dcl]

**Issue description**: [stmt.dcl]/2 requires that when a function has multiple by-value parameters, the parameter objects are destroyed in reverse order of construction when they become inactive (e.g. when the function returns).

At the same time, since C++17, we also guarantee evaluation order for arguments to operator functions that is the same as the evaluation order for the corresponding built-in operator, e.g., `a += b` evaluates `b` and then `a`, even if that is different from the evaluation order in `operator+=(a, b)`.

For callee-destroy ABIs, this poses a difficulty: if `operator+=(a, b)` would evaluate `a` and then `b`, then the implementation must emit a second version of `operator+=` that destroys its parameters in the other order (perhaps by reversing the declaration order of the parameters). At least one major ABI is currently non-conforming and we should clarify whether we actually require callee-destroy implementations to use such a strategy.

**Suggested resolution**: Solicit EWG feedback on a direction, which should be a choice between:
1) Re-affirm the current wording, e.g., require that in `a += b`, the parameter that is initialized from `a` is destroyed before the parameter that is initialized for `b`, or
2) Add an exception that permits the destructor calls for parameters to be indeterminately sequenced relative to each other when operator syntax is used, e.g., `a += b`.

(Edit: since we say "[it] is implementation-defined whether the lifetime of a parameter ends when the function in which it is defined returns or at the end of the enclosing full-expression" in order to permit but not require callee-destroy, the exception should perhaps only apply in the case where the implementation has specified that it uses callee-destroy.)

**Comment by languagelawyer** [comment]
Reflector thread https://lists.isocpp.org/core/2020/06/9318.php

**Comment by jensmaurer** [comment]
CWG2751, forwarded to EWG.

**Comment by jensmaurer** [comment]
EWG closed as NAD.
