### ISSUE TITLE
CWG2760 [expr.const] immediate escalating expressions and default member initializers

### ISSUE THREAD

**Issue by cor3ntin** [cplusplus/CWG#354]
It is unclear whether default constructors of classes with immediate escalating default member initializers are immediate functions

```cpp
consteval int f(int);
struct S {
  int x = f(0);
  S() = default;
};

int main() {
    S s;
}
```

In the above example

 * `f()`  is immediately escalating (f is an immediate function which is not a constant expression as it is not defined) [expr.const] /p16.2
 * `S::S()` is immediate-escalating (it is a defaulted special member function) [expr.const]/p17.2
 
But is `S::S()` an immediate function?

It is unclear that p18.2 applies (and p15 is irrelevant because S is not an aggregate)

> An immediate function is a function or constructor that is
> an immediate-escalating function F whose function body contains an immediate-escalating expression E such that E's innermost enclosing non-block scope is F's function parameter scope.

It would be inconsistent for it not to be, so this is either an oversight or me missing something again!

### Proposed resolution

Modify [expr.const] /p18

An [immediate function](http://eel.is/c++draft/expr.const#def:function,immediate) is a function or constructor that is
-  declared with the consteval specifier, <del>or</del>
- an immediate-escalating function F whose function body contains an immediate-escalating expression E such that E's innermost enclosing non-block scope is F's function parameter scope<del>.</del><ins>, or</ins>
- <ins>an immediate-escalating default constructor of a class which has at least one non-static data member with an _immediate-escalating_ default member initializer.  </ins>

**Comment by cor3ntin** [comment]
Similarly 

> An aggregate initialization is an immediate invocation if it evaluates a default member initializer that has a subexpression that is an immediate-escalating expression[.](http://eel.is/c++draft/expr.const#15.sentence-3)

> An immediate-escalating expression shall appear only in an immediate-escalating function[.](http://eel.is/c++draft/expr.const#17.sentence-2)

Is the intent that aggregate initialization constitute an immediate-escalating context?

**Comment by cor3ntin** [comment]
The more I try to think about it, the less it makes sense to me.
Maybe we just want to say that

> An aggregate initialization is an immediate-escalating expression if it evaluates a default member initializer that has a subexpression that is an immediate-escalating expression.

**Comment by jensmaurer** [comment]
CWG2760

**Comment by cor3ntin** [comment]
Thanks a lot, i think your complete proposed resolution makes sense to me.
