### ISSUE TITLE
[temp.dep.type] p5 The lookup result for a qualified-name that is not dependent

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#357]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[basic.lookup.general] p1 says:
> Unless otherwise specified, the program is ill-formed if no declarations are found.

The "otherwise specified" presumably refers to [temp.res.general] p1
> If **the name is dependent** (as specified in [temp.dep]), **it is looked up for each specialization (after substitution)** because the lookup depends on a template parameter.

Consider this example:
````cpp
template<class T>
struct A{
    void fun(){
        this->show();  // #1
    }
};
````
The name `show` is qualified-name and whose lookup context is `A<T>`, as per [temp.dep.type] p5, and **is not a dependent name** 
> A qualified name ([basic.lookup.qual]) is dependent if 
>> - [...]
>> - its lookup context is dependent and **is not the current instantiation**, or

The lookup context is `A<T>` that is the current instantiation. So, the "otherwise specified" principle does not apply to this case. However, this example can be compiled by GCC, Clang and MSVC. See https://godbolt.org/z/GaPxobTTe. 

So, which rule in the current standard supress [basic.lookup.general] p1? Is it [temp.dep.type] p6? However, that rule just intend to determine whether the name would be ambiguous(in both context).

### Suggested Resolution

The implementations seem to not act as the as that defined in the standard.

**Comment by jensmaurer** [comment]
The program is ill-formed, no diagnostic required, per temp.res.general p6.1 ("no valid specialization can be generated").

**Comment by xmh0511** [comment]
> The program is ill-formed, no diagnostic required, per temp.res.general p6.1 ("no valid specialization can be generated").

However, [basic.lookup.general] p1 explicitly says: the program is ill-formed, which asks the diagnosis, anyway.

**Comment by jensmaurer** [comment]
IFNDR trumps ill-formed; see [intro.compliance.general] p2 and in particular the "otherwise" in bullet 2.3.

**Comment by xmh0511** [comment]
> IFNDR trumps ill-formed; see [intro.comliance.general] p2 and in particular the "otherwise" in bullet 2.3.

However, the program contains both of them(i.e. [basic.lookup.general] p1 and [temp.res.general] p6.1), it is not clear that [temp.res.general] p6.1 has a high priority to trump [basic.lookup.general] p1, that is, [temp.res.general] p6.1 is the "otherwise part" mentioned by [basic.lookup.general] p1. Moreover, the "if" and "otherwise" in [intro.compliance.general] p2 does not mean that there is a mutual exclusion relationship **for the same construct**.

>  IFNDR trumps ill-formed
If the program obeyed this meaning, the following example wouldn't emit a diagnosis
````cpp
template<class T>
struct A{
   void show(){
       this->fun();  // #1
   }
};
int main(){
    void* p = 1; // #2
}
````
The program contains `IFNDR`(at `#1`) and `ill-formed`(at `#2`), according to [intro.comliance.general] p2, IFNDR trumps ill-formed, the program wouldn't emit an error. 

The wording should be phrased as
> For the same construct, if the construct contains a violation of a rule for which no diagnostic is required...
> 
> Otherwise...

this may be correct to convey the intent, I think.

**Comment by jensmaurer** [comment]
Absolutely.

Once you have a program with `#1`, the behavior of the compiler (or the program) is no longer governed by the rules of the standard. Note that "no diagnostic required" means exactly that: No diagnostic is required, but there is no requirement that diagnostics are forbidden. (In fact, an implementation can issue diagnostics for a well-formed program, too; those are usually called "warnings".)

**Comment by xmh0511** [comment]
Confirming that, the implementation can choose to not emit an error for the ill-formed construct at `#2` due to the IFNDR at `#1`, in other words, IFNDR trumps ill-formed in any case.

**Comment by frederick-vs-ja** [comment]
The intent of relaxing for IFNDR first seems to be allowing silent extensions, especially those introduced by __ugly names (`__attribute__`, `__declspec`, etc.). It's unclear to me whether it's intended not to tell extensions from errors. Perhaps we want to allow extensions, but not NDR errors, to trump ill-formedness.

**Comment by t3nsor** [comment]
> The intent of relaxing for IFNDR first seems to be allowing silent extensions, especially those introduced by __ugly names (`__attribute__`, `__declspec`, etc.). It's unclear to me whether it's intended not to tell extensions from errors. Perhaps we want to allow extensions, but not NDR errors, to trump ill-formedness.

But the nature of NDR *errors* is that the program is nonsensical in some way that is not easily detected. That being the case, upon encountering such a program, an implementation can behave unpredictably and may not be in a state where it's capable of generating diagnostics for constructs that would normally require them.
