### ISSUE TITLE
CWG2586 [class.copy.assign] and [class.compare.default]: Explicit object assignment operators and comparisons 

### ISSUE THREAD

**Issue by brevzin** [cplusplus/CWG#37]
Reference (section label): [class.copy.assign] and [class.compare.default]

Issue description: Deducing this allows you to declare assignment operators and comparisons as explicit object member functions. That wording is all there. However, such an assignment operator can never be a copy or move assignment operator, which means it always conflicts with the implicitly-defined one:

```cpp
struct C {
    C& operator=(this C&, C const&); // error: can't overload with the copy assignment operator
};
```

Similarly, you can declare `operator==` or `operator<=>` with an explicit object parameter but you can't default it, simply because the wording happens to not allow that. 

```cpp
struct D {
    bool operator==(this D const&, D const&) = default; // error: not a kind of comparison that can be defaulted
};
```

In both cases, I'm not sure there's much value in allowing that but I'm also not sure there's any reason to disallow that if people prefer writing all of their members using the deducing this style. 

Suggested resolution:

[class.copy.assign]/1:

> A user-declared assignment operator `X​::​operator=` is a non-static non-template member function of class `X` with exactly one <ins>non-object</ins> parameter of type `X`, `X&`, `const X&`, `volatile X&`, or `const volatile X&`.

[class.copy.assign]/3:

> A user-declared move assignment operator `X​::​operator=` is a non-static non-template member function of class `X` with exactly one <ins>non-object</ins> parameter of type `X&&`, `const X&&`, `volatile X&&`, or `const volatile X&&`.

[class.compare.default]/1:

> A defaulted comparison operator function for some class `C` shall be a non-template function that is
> 
> * a non-static <del>const non-volatile</del> member of `C` having <ins>an implicit or explicit object parameter of type `const C&`</ins> and <del>one</del> <ins>a non-object</ins> parameter of type `const C&` <del>and either no ref-qualifier or the ref-qualifier `&`</del>, or
> * a friend of `C` having either two parameters of type `const C&` or two parameters of type `C`.

**Comment by frederick-vs-ja** [comment]
Should we also allow the following style?
```C++
struct X {
    bool operator==(this X, X) = default;
};
```

Suggested addition to [class.compare.default]/1:
> * <ins>a non-static member of `C` having an explicit object parameter and a non-object parameter, both of which are of type `C`, or</ins>

**Comment by brevzin** [comment]
Yes we should! That's a good point. Basically, we want a function that either has both parameters of type `C` or both parameters of type `const C&`. There's probably a nice way to phrase that without having to list all four options separately. Maybe something like:

> A defaulted comparison operator function for some class `C` shall be a non-template function that is:
> * either a non-static member of `C` or a friend of `C`, and
> * either has two parameters (including the implicit or explicit object parameter, if any) of type `const C&` or two parameters of type `C`.

?

**Comment by jensmaurer** [comment]
CWG2586

For the assignment operators, I'm wondering whether we should restrict the explicit object parameter somehow. Right now, it seems we can take a parameter that has unrelated type. But we don't want conversions for the left-hand side of `operator=`, I think.
