### ISSUE TITLE
CWG2777 [temp.param.note] p3 lacks the formal wording to define the type of the id-expression denoting the template parameter object

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#374]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[temp.param.note] p3 says:
> [Note 3: If an id-expression names a non-type non-reference template-parameter, then it is a prvalue if it has non-class type.
Otherwise, if it is of class type T, it is an lvalue and **has type const T ([expr.prim.id.unqual])**. — end note]

Then, in [expr.prim.id.unqual], there is still only a note that says the type of the id-expression, [expr.prim.id.unqual.note] p4
> [Note 4: If the entity is a template parameter object for a template parameter of type T ([temp.param]), the type of the expression is const T. — end note]

If there is no extra formal rule, then [temp.param] p8 just trumps any note, which says: 
> An id-expression naming a non-type template-parameter of **class type T** denotes a static storage duration object of 

`T` is the declared type of the id-expression. 

### Suggested Resolution
When an id-expression that denotes the template parameter object appears in a context other than `decltype(id-expression)` , we should define its type with a formal rule. 

In this `decltype(id-expression)`, GCC and Clang have divergence, GCC says the type is `const T` while Clang says it is `T`.

````cpp
struct A{};
template<auto const a>
void show(){
   decltype(a) b;
   A& rf = b;
}
int main(){
    show<A{}>();
}
````
https://godbolt.org/z/9jqhYn3vd

**Comment by xmh0511** [comment]
"denote" in [expr.prim.id.unqual] p3 merely means it denotes the entity that is introduced by the declaration that declares the name(i.e. id-expression) for which name lookup finds the declaration, which is static. Since the id-expression is introduced by the **parameter-declaration**(i.e. `A a`), its declared type should be `A`.

Moreover, "denote an object" does not mean the lvalue is required to be that type of object, for example:
````cpp
int a;
const int& ref = a;
````
According to [expr.type] p1
> The expression designates the object or function **denoted by the reference**, and the expression is an lvalue or an xvalue, depending on the expression.

The object denoted by the reference is a non-const object, by your logic, the id-expression `ref` thereof has type `int`?

**Comment by frederick-vs-ja** [comment]
> "denote" in [expr.prim.id.unqual] p3 merely means it denotes the entity that is introduced by the declaration that declares the name(i.e. id-expression) for which name lookup finds the declaration, which is statically determined.

But a template parameter is arguably not itself an entity (although the term "value" in [[basic.pre] p3](https://eel.is/c++draft/basic.pre#3) is not very clear), while a template parameter object is definitely an entity.

> Moreover, "denote an object" does not mean the lvalue is required to be that type of object, for example:
> 
> ```c++
> int a;
> const int& ref = a;
> ```

Hmm... it is far less than ideal to use the ambiguous verb "denote", which you should have noticed for many times, (cplusplus/draft#5346).

While "denote" is ambiguous, I think we can say a template parameter is not a thing that can be denoted by an id-expression (in the meaning of denoting an entity), so [temp.param] p8 should be considered unambiguously meaning that the id-expression only denotes the template parameter object, and thus have the same type as that object.

I think we should have an omnibus issue that clarifies "denoting", "naming", "designating", and "referring to".

**Comment by xmh0511** [comment]
> But a template parameter is arguably not itself an entity (although the term "value" in [[basic.pre] p3](https://eel.is/c++draft/basic.pre#3) is not very clear), while a template parameter object is definitely an entity.

The template parameter introduces an object that is an entity, whose declaration is a *parameter-declaration*, and if there is any other specification, the type of the *parameter-declaration* is specified by [dcl.meaning], regardless of what actual object it denotes. The declaration just declares the name should denote a certain object, rather than specify which object it denotes.

**Comment by frederick-vs-ja** [comment]
> The template parameter introduces an object that is an entity

Not obviously true to me. I think it's still unclear whether a template parameter object is introduced by a template parameter. Perhaps we can say a template parameter object is introduced and created in some way other than declaration (there're some other objects created in unclear ways, see CWG2334).

IMO a template parameter object is very similar to a variable, but the current wording seemingly intends to distinguish between a template parameter object and a variable. (Perhaps we should continue the discussion in #148.)

**Comment by xmh0511** [comment]
A declaration that introduces an object does not necessarily mean the declaration **creates** the object. Consider this example:
````cpp
extern A a; // introduces an object but not create it. 
````

**Comment by jensmaurer** [comment]
CWG2777

Note that decltype is handled specially for non-type template parameters.
