### ISSUE TITLE
CWG2587 [intro.races] visible side effect and initial value of an object

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/CWG#38]
**Full name of submitter**: Andrey Erokhin

**Reference (section label)**: [intro.races]

**Link to reflector thread (if any)**:

**Issue description**:
> A [visible side effect](http://eel.is/c++draft/intro.races#def:side_effects,visible) _A_ on a scalar object or bit-field _M_ with respect to a value computation _B_ of _M_ satisfies the conditions:
> - _A_ happens before _B_ and
> - there is no other side effect _X_ to _M_ such that _A_ happens before _X_ and _X_ happens before _B_.
>
> The value of a non-atomic scalar object or bit-field _M_, as determined by evaluation _B_, shall be the value stored by the visible side effect _A_[.](http://eel.is/c++draft/intro.races#13.sentence-1)

The issue is that the initialization of an object, or its absence, are not [side effects](http://eel.is/c++draft/intro.execution#def:side_effects), only assignment is.

**Comment by jensmaurer** [comment]
Created CWG2587
