### ISSUE TITLE
[expr.prim.lambda.closure] p16 All major implementations don't adhere the rule

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#396]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[expr.prim.lambda.closure] p16
> A member of a closure type shall not be explicitly instantiated, explicitly specialized, or named in a friend declaration.

IIUC, this rule just prohibit the user-defined specialization for the function call operator template of a lambda-expression. Consider  this example:
````cpp
auto f(){
    return [](auto c)->void{};
}

using Closure = decltype(f());

template<>
void Closure::operator()<int>(int) const{ }
````
All major implementations(i.e. Clang, GCC, and MSVC) accept this example, see https://godbolt.org/z/WsGsGWv6c. Is this a bug of these vendor implementations, or the wording is outdated?

**Comment by frederick-vs-ja** [comment]
The prohibition is intended, see CWG1780. And I think it's better to report this as compiler bugs.

**Comment by frederick-vs-ja** [comment]
See
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69309
- https://llvm.org/PR26166
- https://developercommunity.visualstudio.com/t/10438990

I think this issue can be closed as completed.

**Comment by xmh0511** [comment]
Thanks. The issue has been confirmed to be a bug in vendor implementations.
