### ISSUE TITLE
[atomics.types.operations] p7 What if the supplied arguments does not denote any enumerator? 

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#398]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

> void store(T desired, memory_order order = memory_order::seq_cst) volatile noexcept;
> void store(T desired, memory_order order = memory_order::seq_cst) noexcept;
>
> Preconditions: The order argument is neither memory_order​::​consume, memory_order​::​acquire, nor memory_order​::​acq_rel.

Consider this case:
````cpp
#include <atomic>
int main(){
   std::atomic<int> v{0};
   auto invented_ordering = static_cast<std::memory_order>(1024);
   v.store(1,invented_ordering);
}
````
[enum.dcl.enum] p8 says:
> It is possible to define an enumeration that has values not defined by any of its enumerators.

The `invented_ordering` does not violate the preconditions of `store`. This may be a LWG issue.

**Comment by frederick-vs-ja** [comment]
Almost all _Preconditions_ in the whole [[atomic]](https://eel.is/c++draft/atomics) seem to be broken.

**Comment by jensmaurer** [comment]
The underlying type of `std::memory_order` might not be able to represent 1024. Maybe it's more prudent to use 7 here.

In any case, this concerns library wording, not core wording, so please report it as an LWG issue.

**Comment by xmh0511** [comment]
> Almost all _Preconditions_ in the whole [[atomics]](https://eel.is/c++draft/atomics) seem to be broken.

They are not broken because they just list the cases that are not expected, and the converted value does not fall in that cases.
