### ISSUE TITLE
CWG2534 [expr.ref] Value category of expression representing pseudo-destructor

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/CWG#4]
Full name of submitter (unless configured in github; will be published with the issue): Andrey Erokhin

Reference (section label): [expr.ref]

Issue description:
[expr.ref] says:
> Abbreviating [_postfix-expression_](http://eel.is/c++draft/expr.post.general#nt:postfix-expression).[_id-expression_](http://eel.is/c++draft/expr.prim.id.general#nt:id-expression) as `E1.E2`, `E1` is called the [_object expression_](http://eel.is/c++draft/expr.mptr.oper#def:object_expression)[.](http://eel.is/c++draft/expr.ref#3.sentence-1) If the object expression is of scalar type, `E2` shall name the pseudo-destructor of that same type (ignoring cv-qualifications) and `E1.E2` is an lvalue of type “function of `()` returning `void`”.

Lvalues should denote objects or functions, but a class member access expression with pseudo-destructor just can't. It should have always been prvalue. Now, after the resolution of CWG2458, there is also assymmetry between pseudo-destructor and a class destructor cases (which is a prvalue).

Suggested resolution:
`E1.E2` is <s>an lvalue</s> **a prvalue** of type “function of `()` returning `void`”

**Comment by jensmaurer** [comment]
CWG2534
