### ISSUE TITLE
CWG2591 [class.union.general] Implicit change of active union member for anonymous union in union

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/CWG#41]
Full name of submitter (unless configured in github; will be published with the issue): 

Reference (section label): class.union.general

Link to reflector thread (if any):

Issue description:

[class.union.general]/6 describes how union member subobjects are implicitly created by certain assignment operations that assign to union members. However, this description does not appear to properly handle the case of an anonymous union appearing within a union:

```
union A {
  int x;
  union {
    int y;
  };
};
void f() {
  A a = {.x = 1};
  a.y = 2;
}
```

Here, the expectation is that the assignment to `a.y` starts the lifetime of the anonymous union member subobject within `A` and also the `int` member subobject of the anonymous union member subobject. But the algorithm for computing S(`a.y`) determines that it is {`a.y`} and does not include the anonymous union member subobject.

Suggested resolution:

Change in [class.union.general]/6:

> In an assignment expression of the form `E1 = E2` that uses either the built-in assignment operator ([expr.ass]) or a trivial assignment operator ([class.copy.assign]), for each element X of S(E1) <ins>and each anonymous union member X ([class.union.anon]) that is a member of a union and has such an element as an immediate subobject (recursively)</ins>, if modification of X would have undefined behavior under [basic.life], an object of the type of X is implicitly created in the nominated storage; no initialization is performed and the beginning of its lifetime is sequenced after the value computation of the left and right operands and before the assignment.

(Adding this rule into the definition of S would be more logical, but S(`E`) is a set of subexpressions of `E` and there is no form of expression that names an anonymous union member. Redefining S(`E`) to be a set of objects might be a better option.)

**Comment by jensmaurer** [comment]
CWG2591
