### ISSUE TITLE
CWG1935 [expr.new] p29 Implementations have different behavior from what the rule says

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#42]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[expr.new] p29 says
> If the implementation **is allowed to introduce a temporary object or make a copy of any argument as part of the call to the allocation function**, it is unspecified whether **the same object** is used in the call to both the allocation and deallocation functions[.](https://eel.is/c++draft/expr.new#29.sentence-3)

Consider this example
````cpp
struct B{
    B(){
        std::cout<<"construct B at: "<<this<<std::endl;
    }
    B(B const& obj){
        std::cout<<"copy from address: "<< &obj<<std::endl;
    }
    ~B(){
        std::cout<<"destroy at: "<<this<<std::endl;
    }
};
struct A{
    void* operator new(std::size_t N,  B obj1){
        std::cout<<"address in new: "<<&obj1<<std::endl;
        return malloc(N);
    }
    void operator delete(void* ptr,  B obj2){
        std::cout<<"address in delete: "<<&obj2<<std::endl;
        free(ptr);
    }
    A(){
        throw 0;
    }
};
int main(){
  try{
    new (B{}) A;
  }catch(...){

  }
}
````
First, class `B` does not satisfy the requirement specified in [class.temporary] p3
> When an **object of class type X** is passed to or returned from a function, if X has at least one eligible copy or move constructor ([special]),** each such constructor is trivial**, and the destructor of X is either **trivial** or deleted, implementations are permitted to create a temporary object to hold the function parameter or result object. 

Moreover, `B{}` in the **new-initializer** is not an object but a prvalue(of course, this is another issue). The corresponding parameter is not a reference type, so neither a temporary object should be introduced nor make a copy of the argument. That means [expr.new] p29 should not apply to this case, which means the usual rules should be applied to this example. At least, we expect that `obj1` and `obj2` will be destroyed at their respective function call is ended. Since [expr.new] p24 says
> The invocation of the allocation function **is sequenced before** the evaluations of expressions in the new-initializer. Initialization of the allocated object is sequenced before the value computation of the new-expression.  

[expr.new] p26 says
> If **any part of the object initialization** described above65 terminates by throwing an exception and a suitable deallocation function can be found, **the deallocation function is called** to free the memory in which the object was being constructed

[expr.new] p24 together with [expr.new] p26 are less or more to imply that the invocation of the allocation function is sequence before the invocation of the deallocation function, I think. However, Both GCC and Clang give the [result](https://godbolt.org/z/Tqa99GqrK) like the following:
````
construct B at: 0x7fff59c06fc8
address in new: 0x7fff59c06fc8
address in delete: 0x7fff59c06fc8
destroy at: 0x7fff59c06fc8  
````
They first create a temporary object, `obj1` and `obj2` are different ways to refer to the same temporary object, and the temporary object is destroyed after the invocation of the deallocation function. This behavior is totally different from the above analysis.

**Comment by languagelawyer** [comment]
Isn't stmt.dcl about block declarations?
http://eel.is/c++draft/expr.call#7.sentence-10

**Comment by xmh0511** [comment]
Even though, we agree that the parameter `obj1` and `obj2` can be destroyed at the end of the full-expression(i.e. the new expression), there is no evidence that can prove `obj1` and `obj2` can refer to the same object. According to [intro.object] p1
> An object is created by a definition

`obj1` and `obj2` can occupy the same memory address but they cannot be the same object. Where is the rule that specify they refer to the same object?

**Comment by languagelawyer** [comment]
> [stmt.dcl] p2 applies to the variable with automatic storage duration

stmt.dcl applies to _declaration-statements_, of which function parameter declarations are not. The laters are introduced by _parameter-declarations_

**Comment by languagelawyer** [comment]
> there is no evidence that can prove that `obj1` and `obj2` can refer to the same object

Looks like a missing case for [class.copy.elision]

**Comment by jensmaurer** [comment]
This is CWG1935.

CWG1880 clarified that parameter objects may be destroyed at the end of the full-expression containing the function invocation. This means a parameter object created for the invocation of the allocation function can survive until and be reused for the invocation of the deallocation function. I'll ask whether an additional clarifying note is desirable as the resolution of CWG1935.

**Comment by xmh0511** [comment]
> Looks like a missing case for [class.copy.elision]

Yes, I expect that we have such a provision in [class.copy.elision], which looks like:
> In an [new-expression](https://eel.is/c++draft/expr.new#nt:new-expression), the copy/move operations for the parameter with type `cv T` where `T` is a class type,  in the allocation function and the matched deallocation function can be omitted by introducing a temporary object of type `cv T` that is copy-initialized from the corresponding argument, the corresponding parameter of the allocation and matched deallocation are different ways to refer to the temporary object.

**Comment by xmh0511** [comment]
> This is [CWG1935](https://cplusplus.github.io/CWG/issues/1935.html).

I think CWG1925 still only concerns what the current wording says. In simple, the wording can be read as:
> if [class.temporary] p3 is satisfied, the implementation is allowed to create a temporary object `o1` to hold the function parameter, then the parameter is copy-initialized from `o1`
>  
> For the matched deallocation function, a temporary object `o2` can be introduced in a similar manner, and the parameter is copy-initialized from `o2`, or the parameter is copy-initialized from `o1`, which way to choose is unspecified. 


Regardless of which way to choose, the parameters of the two functions are not specified to refer to the same object. This issue even doesn't matter with [class.temporary] p3 since the requirement is not satisfied.

**Comment by jensmaurer** [comment]
> the parameters of the two functions are not specified to refer to the same object

Yes, and that's exactly what CWG1935 talks about:

>  as it allows reuse of a parameter object

(It also discusses timing of destruction, but the reuse part alone is surprising.)

**Comment by xmh0511** [comment]
> as it allows reuse of a parameter object

I think the "parameter object" refers to the object introduced by *parameter-declaration*. However, in [expr.new] p29, the object refers to the created temporary object per [class.temporary] p3 to hold the value or the temporary object produced by materialization conversion, not the "parameter object". Anyway,  the "parameter object" is copy-initialized from the temporary object.

**Comment by jensmaurer** [comment]
No. There is no extra temporary object, in general. [class.temporary] p3 allows (but does not require) the implementation to create a temporary object in certain circumstances, but your example is not one of those cases (the copy constructor is not trivial). Note "If the implementation is allowed to introduce a temporary object"; in your case, the implementation is not allowed to introduce a temporary object.

In general, parameter objects are copy-initialized from their arguments, and brace-initialization and guaranteed copy elision (prvalue rvamp) (at least) have made it possible to initialize a parameter without any temporaries involved. The rules need to work for that case.

**Comment by xmh0511** [comment]
Attaching the two contrast examples.   

> When class `B` is trivially copyable:

### example 1
````cpp
struct B{
    B(){
        std::cout<<"construct B at: "<<this<<std::endl;
    }
    B(B const& obj){
        std::cout<<"copy from address: "<< &obj<<std::endl;
    }
    ~B(){
        std::cout<<"destroy at: "<<this<<std::endl;
    }
    int a;
};
struct A{
    void* operator new(std::size_t N,  B obj1){
        std::cout<<"obj1.a = "<< obj1.a<<std::endl;  // #1
        obj1.a = 10;  // modification to the subobject
        return malloc(N);
    }
    void operator delete(void* ptr,  B obj2){
        std::cout<<"obj2.a = "<< obj2.a<<std::endl; // #2
        free(ptr);
    }
    A(){
        throw 0;
    }
};
int main(){
  try{
    new (B{}) A;
  }catch(...){

  }
}
````
See [example 1](https://godbolt.org/z/49vEGMPzq), the numbers printed at `#1` and `#2`  are both `0`. `B` is trivially copyable, the implementations are allowed to introduce a temporary object to hold the function parameter per [class.temporary] p3. The implementation can introduce each temporary object for the allocation and deallocation function, and the parameters are copy-initialized from the corresponding temporary object. Or, the implementation introduces one temporary object in the call of the allocation function and uses the same temporary object to initialize the parameter of the deallocation function. Which way to choose is unspecified per [expr.new] p29. It does not matter which way to choose, we have **two parameter objects** in this case(i.e. `obj1` and `obj2`), and they do not impact each other.

> When class `B` is not trivially copyable:

### example 2
````cpp
struct B{
    B(){
        std::cout<<"construct B at: "<<this<<std::endl;
    }
    B(B const& obj){
        std::cout<<"copy from address: "<< &obj<<std::endl;
    }
    ~B(){
        std::cout<<"destroy at: "<<this<<std::endl;
    }
    int a;
};
struct A{
    void* operator new(std::size_t N,  B obj1){
        std::cout<<"obj1.a = "<< obj1.a<<std::endl;  // #1
        obj1.a = 10;  // modification to the subobject
        return malloc(N);
    }
    void operator delete(void* ptr,  B obj2){
        std::cout<<"obj2.a = "<< obj2.a<<std::endl; // #2
        free(ptr);
    }
    A(){
        throw 0;
    }
};
int main(){
  try{
    new (B{}) A;
  }catch(...){

  }
}
````
See [example 2](https://godbolt.org/z/5KrhjdbK6). Be surprising that the value of `obj2.a` printed at `#2` is `10`. The modification to `obj1.a` after `#1` impacts the value of `obj2.a`.  GCC, Clang, and MSVC all have the same behavior. The behavior looks like the implementations only **creates a single object** `o` and `obj1` and `obj2` behave as if they were **references** and **were bound to the object `o`**.

**Comment by jensmaurer** [comment]
> The behavior looks like the implementations only creates a single object o and obj1 and obj2 behave as if they were references and were bound to the object o.

Exactly, and that's what the normative wording apparently tries to say: The same object is used as a parameter object for both the allocation and deallcoation functions; it's unspecified if it's the same object for those "copy allowed" cases. And that's what CWG1935 should clarify.

**Comment by xmh0511** [comment]
> The same object is used as a parameter object for both the allocation and deallcoation functions

This point is not clear in the current wording. Consider the current wording
> If the implementation is allowed to introduce a temporary object or make a copy of any argument as part of the call to the allocation function, it is unspecified whether the same object is used in the call to both the allocation and deallocation functions[.](https://eel.is/c++draft/expr.new#29.sentence-3)

First of all, what does the following rule intend to mean?
> it is unspecified whether **the same object is used in the call** to both the allocation and deallocation functions

Does it mean the object is used as the argument in the function call or something else? The "use" is not clear here. We should clarify how "use" the object. Presumably, "use" means to make the corresponding parameters of the allocation and matched deallocation function be different ways to refer to the object. This is the intent of "use", I think. Anyway, the object is the aforementioned temporary object. 


I think "introduce a temporary object" corresponds to the case: the parameter is of reference type and is bound to a **prvalue** such that a temporary object should be introduced. "make a copy of any argument" should correspond to the case defined in [class.temporary] p3

**Comment by xmh0511** [comment]
The subject of CWG1935 mainly concerns the lifetime of the parameter object, which is basically clarified by [expr.call] p7 but is not complete(this is another issue). The subject of this issue complains that the meaning of "reuse the parameter object" is not well conveyed in [expr.new] p29. As pointed out in the above comment. 
> it is unspecified whether the same **object** is used in the call to both the allocation and deallocation functions

In this rule, what object does it mean? Does it mean "temporary object" appeared in the before part sentence? or "parameter object"? This is hazy. Another unclear point is what "use" means in the rule? Specifically, how use the object? Maybe, "use" means that let the parameter of an object type refer to that object as if the parameter were a reference to that object type, at least according to the implementations' behavior, I think. These unclear points should be clarified.

**Comment by jensmaurer** [comment]
CWG has reviewed CWG1935 and believes it is clear enough to require the "same parameter object" interpretation.

**Comment by xmh0511** [comment]
> This issue is resolved by issues 1880 and 2177. Reusing the parameter objects of the placement-new call for the placement-delete invocation is intentional.

I would say this point is unclear in the current wording. For example, if the implementation is **not** allowed to introduce a temporary object and is not allowed to make a copy of any argument, what will happen? This is the case of the example in this issue.
