### ISSUE TITLE
CWG2807 [class.dtor] Destructors can, and shall not be consteval

### ISSUE THREAD

**Issue by cor3ntin** [cplusplus/CWG#420]
Issue description:

In [dcl.constexpr]/p2 we say,

> A destructor, an allocation function, or a deallocation function shall not be declared with the consteval specifier[.](https://eel.is/c++draft/dcl.constexpr#2.sentence-3)

Which seems entirely reasonable.

But in [class.dtor]/p1.2 we say

> Each [decl-specifier](https://eel.is/c++draft/dcl.spec.general#nt:decl-specifier) of the [decl-specifier-seq](https://eel.is/c++draft/dcl.spec.general#nt:decl-specifier-seq) of a prospective destructor declaration (if any) shall be friend, inline, virtual, constexpr, **or consteval**[.](https://eel.is/c++draft/class.dtor#1.sentence-3)

This is not as reasonable, and it is contradictory.

Suggested resolution:

Each decl-specifier of the decl-specifier-seq of a prospective destructor declaration (if any) shall be friend, inline, virtual, <ins>or</ins> constexpr<del>, or consteval</del>.

**Comment by jensmaurer** [comment]
CWG2807
