### ISSUE TITLE
CWG2810 [temp.res.general] Templates should not silence diagnostics

### ISSUE THREAD

**Issue by Eisenwave** [cplusplus/CWG#428]
Reflector thread: https://lists.isocpp.org/core/2022/01/11929.php

Reference (section label): [temp.res.general]

### Issue Description

In [[temp.res.general] p6](https://eel.is/c++draft/temp.res.general#6), it is stated that the program is ill-formed, no diagnostic required as the result of invalid constructs in templates, and:

> Otherwise, no diagnostic shall be issued for a template for which a valid specialization can be generated.

The latter sentence serves no apparent purpose because the reader would not expect a diagnostic to be required if the program does not violate any of the listed conditions. Furthermore, it could be misinterpreted to mean that diagnostic messages such as optional warnings are required to be suppressed:
```cpp
template <int N> int foo(float x) {
    return j; // warning: conversion from float to int [-Wconversion]
}
```
Issuing a `-Wconversion` warning in this example could be seen as not conforming. Of course, an implementation could simply not treat `-Wconversion` as a diagnostic as per [[defns.diagnostic]](https://eel.is/c++draft/defns.diagnostic). However, this interpretation means that some warnings are diagnostics and some aren't, which is a contrived, and complicated for the reader.

### Suggested resolution

Update [[temp.res.general] p6](https://eel.is/c++draft/temp.res.general#6) as follows:
```diff
 [...]
-Otherwise, no diagnostic shall be issued for a template
-for which a valid specialization can be generated.
 [...]
```

**Comment by Eisenwave** [comment]
Note that I think that the intention of "subset" in [[defns.diagnostic]](https://eel.is/c++draft/defns.diagnostic) is to say that informative messages or notes which are output aren't considered diagnostics; not to establish that only a subset of warnings or errors is a diagnostic.

**Comment by languagelawyer** [comment]
Reflector thread https://lists.isocpp.org/core/2022/01/11929.php

**Comment by jensmaurer** [comment]
CWG2810
