### ISSUE TITLE
CWG2822 [basic.stc.general] Side-effect-free pointer zap

### ISSUE THREAD

**Issue by opensdh** [cplusplus/CWG#457]
Reference (section label): [basic.stc.general]

Link to reflector thread (if any): [main proposal](https://lists.isocpp.org/core/2020/06/9427.php)

Issue description:

[basic.stc.general]/4 seems to suggest that the end of the duration of a region of storage causes modifications to pointer objects, raising questions about data races (in the abstract machine) and complicating ongoing discussions about the compatibility of the standard with certain concurrent algorithms.

Suggested resolution:

Per reflector discussion, separate inherently invalid pointer values (as from `reinterpret_cast` of arbitrary integers) from circumstantially invalid pointer usage (that does not happen before the destruction of the relevant storage), by making the wording changes below.

Change in [basic.stc.general]/4:

> <ins>[_Note_:</ins> <del>When</del> <ins>After</ins> the end of the duration of a region of storage is reached, the values of all pointers representing the address of any part of that region of storage <del>become</del> <ins>behave as if they were</ins> invalid pointer values&nbsp;([basic.compound]).<ins>  &mdash;&nbsp;_end note_]</ins>
>
> <del>Indirection through an invalid pointer value and passing an invalid pointer value to a deallocation function have undefined behavior.  Any other use of an invalid pointer value has implementation-defined behavior.<sup>[&hellip;]</sup></del>

Change in [basic.compound]/3:

> [&hellip;]  Every value of pointer type is one of the following:
> * a _pointer to_ an object or function (the pointer is said to _point_ to the object or function), or
> * a _pointer past the end of_ an object&nbsp;([expr.add]), or
> * the _null pointer value_ for that type, or
> * an _invalid pointer value_.
>
> A value of a pointer type that is a pointer to or past the end of an object _represents the address of_ the first byte in memory&nbsp;([intro.memory]) occupied by the object<sup>[&hellip;]</sup> or the first byte in memory after the end of the storage occupied by the object, respectively.
>
> [_Note_: A pointer past the end of an object&nbsp;([expr.add]) is not considered to point to an unrelated object of the object's type, even if the unrelated object is located at that address.  <del>A pointer value becomes invalid when the storage it denotes reaches the end of its storage duration; see [basic.stc].</del>  &mdash;&nbsp;_end note_]
>
> [&hellip;]

Insert a new paragraph after /3, including the deleted text from [basic.stc.general]/4:

> A pointer value _P_ is _valid in the context of_ an evaluation _E_ if _P_ is a null pointer value, or if it is a pointer to or past the end of an object _O_ and _E_ happens before the end of the duration of the region of storage for _O_. If a pointer value _P_ is used in an evaluation _E_ and _P_ is not valid in the context of _E_, then the behavior is undefined if _E_ is an indirection or an invocation of a deallocation function, and implementation-defined otherwise.<sup>[&hellip;]</sup>
>
> [_Note_: _P_ can be valid in the context of _E_ even if it points to a type unrelated to that of _O_ or if _O_ is not within its lifetime, although further restrictions apply to such pointer values&nbsp;([basic.lval], [expr.add], [basic.life]).  &mdash;&nbsp;_end note_]

For clarity, add cross reference in [expr.static.cast]/14:

> A prvalue of type "pointer to _cv1_ `void`" can be converted to a prvalue of type "pointer to _cv2_ `T`", where `T` is an object type and _cv2_ is the same cv-qualification as, or greater cv-qualification than, _cv1_.  If the original pointer value represents the address `A` of a byte in memory and `A` does not satisfy the alignment requirement of `T`, then the resulting pointer value<ins>&nbsp;([basic.compound])</ins> is unspecified.
>
> [&hellip;]

and similarly in [expr.reinterpret.cast]/5:

> A value of integral type or enumeration type can be explicitly converted to a pointer.  A pointer converted to an integer of sufficient size (if any such exists on the implementation) and back to the same pointer type will have its original value<ins>&nbsp;([basic.compound])</ins>; mappings between pointers and integers are otherwise implementation-defined.

**Comment by jensmaurer** [comment]
CWG2822
