### ISSUE TITLE
CWG2845 [temp.param] Make the type of lambda with no capture a structural type

### ISSUE THREAD

**Issue by RungeCC** [cplusplus/CWG#459]
Full name of submitter (unless configured in github; will be published with the issue): Runge C.

Reference (section label): [expr.prim.lambda.closure] and [temp.param]

Link to reflector thread (if any):

Issue description:

After CWG2542 was adopted, closure type is not a structural type as specified directly in [expr.prim.lambda.closure]/3:

> The closure type is not an aggregate type ([[dcl.init.aggr]](https://eel.is/c++draft/dcl.init.aggr)) and not a structural type ([[temp.param]](https://eel.is/c++draft/temp.param)).

However, there's no good reason why we should make all closure types non-structural since a closure object with no capture has already perfectly met the original definition of structural type. Notice closure type with generic lambda is not convertible to some function pointer (if did not specialize it) so IMO allowing them could improve the expressiveness (and/or, usability) of NTTP, especially in the current situation that we have accepted a facility proposal related to NTTP callable (P2714).

Suggested resolution:

### Resolution 1

In [expr.prim.lambda.closure]/3:

> The closure type is not an aggregate type ([dcl.init.aggr]) <del>and not a structural type ([temp.param])</del>.

Then in [temp.param]/7:

> - a literal class type with the following properties:
>   - all base classes and non-static data members are public and non-mutable and
>   - the types of all bases classes and non-static data members are structural types or (possibly multidimensional) array thereof<del>.</del>**and,**
>   - **if the type of is a closure type ([expr.prim.lambda.closure]), the _lambda-expression_ it is associated with has no _lambda-capture_.**

Or:

### Resolution 2

In [expr.prim.lambda.closure]/3:

> The closure type is not an aggregate type ([dcl.init.aggr]) <del>and not a structural type ([temp.param])</del>. The closure type is not a structural type ([temp.param]) if the _lambda-expression_ it is associated with has a _lambda-capture_.

**Comment by frederick-vs-ja** [comment]
FWIW, the status quo is not so that broken IMO - e.g. we can still write `std::bind_front([](auto){}, 42)` (since C++20) instead of intended `std::bind_front<[](auto){}>(42)` (invalid now, but may become valid in the future, possbily still in C++26). Given every lambda expression has a unique closure type, the closure object can always occupy zero byte in the resulted wrapper object, and thus the overhead (if any) of both forms can be considered equal.

**Comment by frederick-vs-ja** [comment]
CWG2845
