### ISSUE TITLE
[intro.defs] Adding definition for the term function lvalue

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#469]
Full name of submitter: Anoop Rana 

Reference (section label): [intro.defs]

Issue description: The standard uses the term "function lvalue" at multiple places but doesn't have a formal definition for the same. Here are 5 occurrences for the same:

Two references in [dcl.init](https://eel.is/c++draft/dcl.init#ref-5.3.1)
One reference in [over.ics.ref](https://eel.is/c++draft/over.ics.ref#3.sentence-1)
Two references in [over.ics.rank](https://eel.is/c++draft/over.ics.rank#3.2.4)

**Suggested resolution:**

Add a definition for the same in [intro.defs] saying something like:

> **function lvalue**
>     an lvalue expression of a function type

**Comment by frederick-vs-ja** [comment]
The proposed wording looks very asymmetric. If it makes sense to add a particular definition for function lvalue, why don't we define object lvalue (and object xvalue, object prvalue, etc.) together?

**Comment by jensmaurer** [comment]
I think we should just say "lvalue of function type" ("expression" is implied) wherever we use "function lvalue", instead of trying to define this rather awkward term.
