### ISSUE TITLE
CWG2596 [temp.inst]/17 Instantiation of constrained non-template friends 

### ISSUE THREAD

**Issue by dfrib** [cplusplus/CWG#47]
**Full name of submitter**: David Friberg

**Reference (section label):** [temp.inst]

**Link to reflector thread (if any):** -

**Issue description:**

As per US115 of [P2103R0](http://open-std.org/JTC1/SC22/WG21/docs/papers/2020/p2103r0.html) hidden non-template friends may also use requires-clauses:

```.cpp
struct Base {};

template<int N>
struct S : public Base {
    friend int foo(Base&) requires (N == 1) { return 1; }
    friend int foo(Base&) requires (N == 2) { return 3; }
};

int main() {
    S<1> s1{};
    S<2> s2{};  // #1
    auto const foo1 = foo(s1);
    auto const foo2 = foo(s2); // #2 
}
```

The current wording doesn't seem to cover what should happen at `#1` above: requires-clauses take effect during overload resolution, but what about instantiation of constrained (hidden) friends whose requires-clauses are not satisfied for the particular enclosing class template specialization being instantiated? Particularly [\[temp.inst\]/17](https://eel.is/c++draft/temp.inst#17) doesn't cover friends as they are neither template specializations nor member functions:

> The [type-constraint](https://eel.is/c++draft/temp.param#nt:type-constraint)s and [requires-clause](https://eel.is/c++draft/temp.pre#nt:requires-clause) of a template specialization or member function are not instantiated along with the specialization or function itself, even for a member function of a local class; substitution into the atomic constraints formed from them is instead performed as specified in [[temp.constr.decl]](https://eel.is/c++draft/temp.constr.decl) and [[temp.constr.atomic]](https://eel.is/c++draft/temp.constr.atomic) when determining whether the constraints are satisfied or as specified in [[temp.constr.decl]](https://eel.is/c++draft/temp.constr.decl) when comparing declarations[.](https://eel.is/c++draft/temp.inst#17.sentence-1)

Implementation variance: 
* GCC and MSVC both currently reject the program at `#1` for ODR-violations
* Clang fails at `#2`, and generates the same mangled name for two different definitions

For the latter, the Itanium C++ ABI currently does not allow unambiguously mangling these kind of friends. See https://github.com/itanium-cxx-abi/cxx-abi/issues/24#issuecomment-934713719

**Suggested resolution:**
To be discussed. Should be program above be well-formed?

**Comment by xmh0511** [comment]
IMO, "in any other scope" in [temp.friend] p9 is not sufficiently clear.
> Such a constrained friend function or function template declaration does not declare the same function or function template as **a declaration in any other scope**.

Does it mean 
> a declaration inhabits any other scope

or
> a declaration whose target scope is any other scope

Furthermore, "any other scope" means different scope or includes the same scope?

**Comment by jensmaurer** [comment]
@erichkeane , "scope" per C++ is lexical (and yes, "other" means "not the same").
The temp.friend p9 clause just means that you can't (re)declare just a constrained friend outside of the class; any attempt at such redeclaration would declare a different entity.

**Comment by jensmaurer** [comment]
@erichkeane , "scope" per C++ is lexical (and yes, "other" means "not the same").
The temp.friend p9 clause just means that you can't (re)declare just a constrained friend outside of the class; any attempt at such redeclaration would declare a different entity.

**Comment by jensmaurer** [comment]
CWG2596

**Comment by jensmaurer** [comment]
This particular issue is about the instantiation question primarily.

In order to fix [temp.friend] properly, the rule should simply be moved to the definition of "corresponds" in [basic.scope.scope] p4, but that's not in scope for CWG2596 (which is talking about instantiations, not about declaration correspondence).

If the simple drive-by "inhabits" is not considered an improvement, it should simply be omitted.
