### ISSUE TITLE
[intro.races] p10 Augment the list to complete the definition 

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#471]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

To be a definition, it has an obligation to tell the complete story to cover all the cases that belong to it. Since, we say whenever `A` strong happens before `B` or `A` simply happens before `B` is true, `A` happens before `B` is true, the definition of "happens before" should cover these cases. 

### Suggested Resolution
Augment the definition for [intro.races] p10
> An evaluation A happens before an evaluation B (or, equivalently, B happens after A) if: 
>> - A is sequenced before B, or
>> - A inter-thread happens before B, or
>> -  A simply happens before  B, or
>> - A strongly happens before B.

**Comment by jensmaurer** [comment]
Rejected; see the other discussion. Unless you can show a specific example that satisfies "strong happens before", but not "happens before".

**Comment by xmh0511** [comment]
> Rejected; see the other discussion. Unless you can show a specific example that satisfies "strongly happens before", but not "happens before".

As is that we cannot find an example that satisfies "strongly happens before", but not "happens before", which means, "strongly happens before" can be subsumed to "happens before", so the definition of "happens before" should cover "strongly happens before", which is similar to that "is sequence before" is "happens before".
