### ISSUE TITLE
[intro.execution] p4 The potentially-evaluated subexpressions of an empty initializer list 

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#473]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

Consider this case:
````cpp
#include <any>
template<class T>
struct B{T b;};

struct C{
    std::any v = B<C>{};  // #1
};
````
[dcl.init.aggr] p13 says:
> If a member has a default member initializer and **a potentially-evaluated subexpression thereof** is an aggregate initialization that would use that default member initializer, the program is ill-formed.  

[intro.execution] p4 says:
>  The potentially-evaluated subexpressions of an expression, conversion, or initializer E are 
>> - the constituent expressions of E and
>> - the subexpressions thereof that are not subexpressions of a nested unevaluated operand ([expr.context]).

[intro.execution] p2 says:
> A constituent expression is defined as follows: 
>> - [...]
>> - The constituent expressions of a braced-init-list or of a (possibly parenthesized) expression-list are the constituent expressions of the elements of the respective list.
>> - The constituent expressions of a brace-or-equal-initializer of the form = initializer-clause are the constituent expressions of the initializer-clause.

` B<C>{}` at `#1` cause the aggregate initialization of `B<C>` as per  [expr.type.conv] p2, which is a default member initializer
> Otherwise, the expression is a prvalue of the specified type whose result object is direct-initialized with the initializer.  

That is, the initializer is as if it was `{}`, however, this is an empty initialization list, which **has an empty elements**, that is, there is no subexpression of `{}`. However, [the major implementations](https://godbolt.org/z/66WMez6GK) say the example is ill-formed, which most likely is regulated by [dcl.init.aggr] p13. 

Moreover, [dcl.init.aggr] p5 says:
> For a non-union aggregate, each element that is not an explicitly initialized element is initialized as follows: 
>> - If the element has a default member initializer ([class.mem]), the element is initialized from that initializer.
>> - Otherwise, if the element is not a reference, the element is copy-initialized from an empty initializer list ([dcl.init.list]).

That is, `B<C>::b` is copy-initialized from `{}`. The whole default member initializer, as per current wording, is at best `{{}}`. 

### Suggested Resolution
In this example, we may want to expect `C{}` as the thereof subexpression of the default member initializer `B<C>{}`, and `C{}` cause the aggregate initialization that would use `B<C>{}`.

**Comment by jensmaurer** [comment]
No.

> If a member has a default member initializer and a potentially-evaluated subexpression thereof is an aggregate initialization that would use that default member initializer, the program is ill-formed.

The default member initializer is `= B<C>{}`, and the subexpression `B<C>{}` is an aggregate initialization, and that subexpression would use the default member initializer because of the default initialization of `C b`. The "would use" part doesn't talk about (syntactic) subexpressions anymore.

**Comment by xmh0511** [comment]
> The "would use" part doesn't talk about (syntactic) subexpressions anymore.

Consider this counter-example:
````cpp
#include <any>
template<class T>
struct B{T b;};

struct C{
    C(){}  // introduce a user-declared constructor
    std::any v = B<C>{};
};

int main(){
    //C c{};
}
````
In this example, the class `C` is not a aggregate due to the user-declared constructor, however, `B<C>` is still an aggregate, [all implementations](https://godbolt.org/z/E33xorEMr) just accept this example.

**Comment by jensmaurer** [comment]
Sure, but that's because the default initialization of `C b` doesn't (directly) use the default member initializer; it uses the user-provided default constructor of C. I'm not seeing a problem with the definition of "subexpression" here, as originally claimed.
