### ISSUE TITLE
CWG2593 [expr.mptr.oper] Dynamic type/most derived type wording not enough to prevent dereferencing using wrong base class subobject

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [cplusplus/CWG#48]
Full name of submitter (unless configured in github; will be published with the issue): Hubert Tong

Reference (section label): [expr.mptr.oper]

Link to reflector thread (if any): N/A

### Issue description:
Consider:
```
struct A {};
struct AA : A { int y; };
struct B : A { int x; };
struct C : AA, B {};

constexpr int f(const A &a) {
  int A::*mp = static_cast<int A::*>(&B::x);
  return a.*mp;
}

extern char x[f(static_cast<const AA &>(C{{{}, 13}, {{}, 42}}))];
extern char x[13];
```

The wording that is meant to prevent the pointer-to-member dereference above from having defined behaviour fails to do so: The dynamic type of `a` is `C`, which does have a `B::x`.

The specified behaviour would require the call to `f` to resolve to a value of `42`; however, both Clang and GCC produce `13`: https://godbolt.org/z/vYhaTEeW8

### Suggested resolution:
Where the type of E2 is "pointer to member of T", C is the (unique) class of which the member to which E2 refers is a direct member, and B is the object of type T that either is the result of E1 or is the uniquely so-typed base subobject thereof, if B is neither of type C nor a base class subobject of an object of type C, then the behavior is undefined.

**Comment by jensmaurer** [comment]
CWG2593
