### ISSUE TITLE
CWG2846 [dcl.fct] Out-of-line definitions of explicit object member functions

### ISSUE THREAD

**Issue by sdkrystian** [cplusplus/CWG#493]
Full name of submitter: Krystian Stasiowski

Reference (section label): [dcl.fct]

Link to reflector thread (if any): N/A

Issue description:

According to [[dcl.fct] p6](http://eel.is/c++draft/dcl.fct#6):
> An _explicit-object-parameter-declaration_ is a _parameter-declaration_ with a `this` specifier. An explicit-object-parameter-declaration shall appear only as the first _parameter-declaration_ of a _parameter-declaration-list_ of either:
> - a _member-declarator_ that declares a member function, or
> - a _lambda-declarator_.

> A _member-declarator_ with an explicit-object-parameter-declaration shall not include a _ref-qualifier_ or a _cv-qualifier-seq_ and shall not be declared `static` or `virtual`.

In the following example:
```cpp
struct A
{
    void f(this A&);
};

void A::f(this A&) { }
```
The out-of-line definition of `A::f` is not a _member-declarator_, therefore it cannot contain an _explicit-object-parameter-declaration_. However, this is accepted by clang, GCC, EDG, and MSVC. 

Suggested resolution:

Replace the first subbullet of [[dcl.fct] p6](http://eel.is/c++draft/dcl.fct#6) with:
> - a declaration of a non-static member function, or

Change the final sentence of [[dcl.fct] p6](http://eel.is/c++draft/dcl.fct#6) as follows (note: this affects some of the wording touched by [CWG2553](https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#2553):
> A ~_member-declarator_~**non-static member function** with an explicit-object-parameter-declaration shall not include a _ref-qualifier_ or a _cv-qualifier-seq_ and shall not be declared ~`static` or~ `virtual`.

**Comment by sdkrystian** [comment]
@jensmaurer I'm not sure the proposed wording in the issue is quite correct. Consider the following:
```cpp
struct A 
{
    template<typename T> 
    void f(this T);
};
template<>
void A::f(this int);
```
The explicit specialization of `A::f` is neither a `member-declarator` nor a `function-definition`.

**Comment by sdkrystian** [comment]
Now that I think about it, the `declaration` of a `template-declaration` or `explicit-specialization` is _never_ a `member-declaration`... should I open another issue for this?

**Comment by jensmaurer** [comment]
I've generalized the wording.
