### ISSUE TITLE
[namespace.udecl] How can we use the term "names a constructor" when a constructor doesn't have a name

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#498]
Full name of submitter: Anoop Rana 

Reference (section label): [namespace.udecl]

Issue description:

The phrase *"names a constructor"* is used multiple times(6) in [N4950] but since constructors do not have names([class.ctor.general](https://eel.is/c++draft/class.ctor.general#1.sentence-2)), this phrase do not make much sense. 

For example, the note in [namespace.udecl](https://eel.is/c++draft/namespace.udecl#4.sentence-1) says:

> [Note [2](https://eel.is/c++draft/namespace.udecl#note-2): Since destructors do not have names, a [using-declaration] cannot refer to a destructor for a base class[.](https://eel.is/c++draft/namespace.udecl#4.sentence-1)
— end note]

But the same thing applies to constructors([class.ctor.general](https://eel.is/c++draft/class.ctor.general#1.sentence-2)) and so if destructors not having names implies that a using-declaration cannot refer to a destructor for a base class, the same should be true for constructors. 

---

[namespace.udecl](https://eel.is/c++draft/namespace.udecl#2) also states:

> **If the [using-declarator](https://eel.is/c++draft/namespace.udecl#nt:using-declarator) names a constructor**, it declares that the class [inherits](https://eel.is/c++draft/namespace.udecl#def:constructor,inherited) the named set of constructor declarations from the nominated base class[.](https://eel.is/c++draft/namespace.udecl#2.sentence-1).

Similarly, there are other uses of the phrase like in [class.qual](https://eel.is/c++draft/class.qual#1.2):

> if N is dependent and is the terminal name of a [using-declarator](https://eel.is/c++draft/namespace.udecl#nt:using-declarator) ([[namespace.udecl]](https://eel.is/c++draft/namespace.udecl)) **that names a constructor**,

**Comment by cpplearner** [comment]
[namespace.udecl]:

> If the terminal name of the [using-declarator](https://eel.is/c++draft/namespace.udecl#nt:using-declarator) is dependent ([[temp.dep.type]](https://eel.is/c++draft/temp.dep.type)), the [using-declarator](https://eel.is/c++draft/namespace.udecl#nt:using-declarator) is considered to name a constructor if and only if [...].

[class.qual]:

> In [...], N is instead considered to name the constructor of class C.

IIUC these are supposed to define what "name the constructor" means. Maybe they should be rephrased to look more like a definition?

**Comment by ranaanoop** [comment]
> Maybe they should be rephrased to look more like a definition?

@cpplearner  Yeah but note that the specific part of the quote [namespace.udecl#1](https://eel.is/c++draft/namespace.udecl#1.sentence-3) you provided is talking about "dependent" terminal name case but in a example such as `struct A{A(int);}; struct B: public A{using A::A;};`, the terminal name is not dependent so the specific part of the quote([namespace.udecl#1](https://eel.is/c++draft/namespace.udecl#1.sentence-3)) you mentioned doesn't apply. 

But I did find [basic.general.lookup#3](https://eel.is/c++draft/basic.lookup#general-3.sentence-2) that seems to talk about "not dependent" terminal name case:

> If any such declaration is a [using-declarator](https://eel.is/c++draft/namespace.udecl#nt:using-declarator) whose terminal name ([[expr.prim.id.unqual]](https://eel.is/c++draft/expr.prim.id.unqual)) is **not dependent** ([[temp.dep.type]](https://eel.is/c++draft/temp.dep.type)), it is replaced by the declarations named by the [using-declarator](https://eel.is/c++draft/namespace.udecl#nt:using-declarator) ([[namespace.udecl]](https://eel.is/c++draft/namespace.udecl))[.](https://eel.is/c++draft/basic.lookup#general-3.sentence-2).

But the part *"replaced by the declarations named by the [using-declarator](https://eel.is/c++draft/namespace.udecl#nt:using-declarator)"* in the above quote seems odd/cyclic to me.

**Comment by ranaanoop** [comment]
Additionally perhaps the note [namespace.udecl#4.sentence-1](https://eel.is/c++draft/namespace.udecl#4.sentence-1) can be removed/revised.

**Comment by cpplearner** [comment]
`using A::A;` is subject to [class.qual]/1. `A::A` is a injected-class-name, and [class.qual]/1 says it's considered to name the constructor of `A`.

**Comment by jensmaurer** [comment]
"X having a name" and "to name a constructor" are distinct concepts in C++.  [class.qual] seems rather explicit when we "name a constructor".  I'm not seeing a core issue here.
