### ISSUE TITLE
[temp.inst] p3 Is the instantiated declaration considered a grammatical component?

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#50]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[temp.inst] p3 says
> However, for the purpose of determining whether an instantiated redeclaration is valid according to **[basic.def.odr] and [class.mem]**, **a declaration** that corresponds to a definition in the template is considered to be a definition.  

According to the example following this rule
````cpp
template<class T, class U>
struct Outer {
  template<class X, class Y> struct Inner;
  template<class Y> struct Inner<T, Y>;         // #1a
  template<class Y> struct Inner<T, Y> { };     // #1b; OK, valid redeclaration of #1a
  template<class Y> struct Inner<U, Y> { };     // #2
};
Outer<int, int> outer;
````
The emphasized declaration presumably means the instantiated declaration. However, the term declaration and definition in  [basic.def.odr] and [class.mem] both refers to the grammatical *declaration* and *definition*, which is defined in [basic.def]. Is the instantiated declaration or definition considered to be the grammatical component? Moreover, consider this example:
````cpp
template<class T>
struct S{
   template<class X, class Y> struct Inner;
   template<class Y> struct Inner<T, Y> { };
};
S<int> s1; // #1
S<int> s2;  // #2
````
Both `#1` and `#2` requires `S<int>` to be the completely-defined object type, Is the more than one implicitly instantiation of `S<int>` causes that `template<class Y> S::Inner<int, Y>` has more than one definition when determining whether the instantiated redeclaration is valid?  In simple, the standard is not clear whether a specialization that has been implicitly instantiated will be later again instantiated in the same TU.

Suggestion resolution:

the suggestion might be:
> However, for the purpose of determining whether an instantiated redeclaration is valid according to [basic.def.odr] and [class.mem], a declaration that corresponds to a definition in the template is considered to be a definition for all same class template specializations.

````cpp
template<class T>
struct S{
    friend void fun(){}
};
S<int> s0;
S<int> s1;  //ok
S<float> s2; //error
````

***
Another issue is  
> the standard is not clear whether a specialization that has been implicitly instantiated will be later again instantiated in the same TU.

Since we only say 
> Unless ... is a declared specialization, ...

That means as long as the specialization is not declared specialization, the implicit instantiation will apply to the specialization regardless of how many times the specialization appears in a TU.

**Comment by jensmaurer** [comment]
Regarding the question of multiple instantiations, see [temp.point] p7 (i.e. that doesn't happen).

**Comment by jensmaurer** [comment]
[basic.def.odr] does not refer to the grammar non-terminal _declaration_, it says "declaration" throughout (and that's intentional).

**Comment by xmh0511** [comment]
> [basic.def.odr] does not refer to the grammar non-terminal declaration, it says "declaration" throughout (and that's intentional).

If it is the intent, consider this example
````cpp
// file a
template<class T>
void fun(T){}

// file b
fun<int>(0); // #1

// file c
fun<int>(2); // #2
````
if each translation units comprise one instantiated definition for specialization `fun<int>`, the program would comprise two such definitions, which violate [basic.def.odr] since the function `fun<int>` is non-inline. The relevant question is https://stackoverflow.com/questions/62789153/what-about-the-odr-rule-for-specialization-that-instantiated-from-a-template, the subject of the question is whether [basic.def.odr] only applies to the stuff written in TUs?

**Comment by jensmaurer** [comment]
This is getting increasingly confused. The distinction between _declaration_ (grammar non-terminal) and "declaration" exists to properly handle e.g.
```
int f(), g();
```
which is a single _declaration_, but two "declarations".

And no, the stuff instantiated from a template is not subject to the ODR, but the template is subject to the ODR. The ODR is an almost source-level construct ("same tokens with same meaning").

For the specific issue of the phrasing in [temp.inst] p3 mentioned in the title, this will be fixed by editorial pull request cplusplus/draft#5538. If you believe there are other issues, please create a new issue.
