### ISSUE TITLE
CWG2594 [basic.start.main] A function template named main is not prohibited by the current draft

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#51]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[basic.start.main] p3 says
> A program that declares a variable main that belongs to the global scope, or that declares a function main that belongs to the global scope and is attached to a named module, or that declares an entity named main with C language linkage (in any namespace) is ill-formed. The name main is not otherwise reserved.

Consider this example
````cpp
template<class T>
void* main(T,T){}

struct S{
template<class T>
friend void* main(T,T);
};

int main() {

}
````
This [example](https://godbolt.org/z/MrW795Gr8) is rejected by both GCC and Clang. However, the example does not violate the above rule. If GCC and Clang implement the right way, [basic.start.main] p3 might be changed to
> A program that declares a variable main that belongs to the global scope, or that declares a function main that belongs to the global scope and is attached to a named module, or **that declares a function template `main` that belongs to the global scope**, or that declares an entity named main with C language linkage (in any namespace) is ill-formed. The name main is not otherwise reserved.

**Comment by jensmaurer** [comment]
CWG2594
