### ISSUE TITLE
CWG2871 [class.default.ctor] p1 should cover the constructor template 

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#510]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[class.default.ctor] p1 says:
>If there is **no user-declared constructor** for class X, a non-explicit constructor having no parameters is implicitly declared as defaulted ([dcl.fct.def]).

Consider this example:
````cpp
struct X{
  template<class U> X(U){} // #2
};
int main(){
   X x;  // #1
}
````
`#1` is ill-formed since no matching function for call to 'X::X()'. [class.default.ctor] p1 should cover this example, however, `#2` is a user-declared **constructor template**, and the implicitly instantiated declaration is not user-declared anyway. 

### Suggested Resolution
> If there is **no user-declared constructor or constructor template** for class X, a non-explicit constructor having no parameters is implicitly declared as defaulted ([dcl.fct.def]).

**Comment by jensmaurer** [comment]
CWG2871

**Comment by frederick-vs-ja** [comment]
> There are plenty of other uses of the undecorated term 'constructor' in the standard that are clearly meant to include templates: [[basic.scope.scope]/4](https://eel.is/c++draft/basic.scope.scope#def:correspond), [[dcl.init.aggr]/1.1](https://eel.is/c++draft/dcl.init.aggr#1.1), [[namespace.udecl]/2](https://eel.is/c++draft/namespace.udecl#2.sentence-1) and [/13](https://eel.is/c++draft/namespace.udecl#13), [[class.mem.general]/22](https://eel.is/c++draft/class.mem.general#22), various subclauses of [[over.match.funcs]](https://eel.is/c++draft/over.match.funcs), etc. Why is it a problem in this particular case?

Most are about inheriting constructors. I think there should be a concentrated issue on this.
