### ISSUE TITLE
[temp.res.general] Dependent and type-only context terminal name without typename considered type?

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#512]
Full name of submitter: Anoop Rana

Reference (section label): [temp.res.general]

Issue description:

Currently, [temp.res.general](https://eel.is/c++draft/temp.res.general#5.sentence-1) says:

> **A [qualified-id](https://eel.is/c++draft/expr.prim.id.qual#nt:qualified-id) whose terminal name is dependent and that is in a type-only context is considered to denote a type[.](https://eel.is/c++draft/temp.res.general#5.sentence-1)**
A name that refers to a [using-declarator](https://eel.is/c++draft/namespace.udecl#nt:using-declarator) whose terminal name is dependent is interpreted as a [typedef-name](https://eel.is/c++draft/dcl.typedef#nt:typedef-name) if the [using-declarator](https://eel.is/c++draft/namespace.udecl#nt:using-declarator) uses the keyword typename[.](https://eel.is/c++draft/temp.res.general#5.sentence-2)
> ```
> [Example 6:
>  template <class T> void f(int i) {
>  T::x * i;         // expression, not the declaration of a variable i
> }
> ... end example]
> ```

The [highlightted](https://eel.is/c++draft/temp.res.general#5.sentence-1) part(in bold) quoted above seems to imply that `T::x` is considered to denote a type. This means that `T::x *i;` should be a declaration not an expression as per the first part of quoted reference. But the comment in the example code says otherwise.

**Comment by jensmaurer** [comment]
Why do you believe this is a type-only context? Your situation doesn't fit any of the categories in [temp.res.general] p4.

**Comment by ranaanoop** [comment]
> Why do you believe this is a type-only context?

@jensmaurer  Because the qualified name `x` is the terminal name of *nested-name-specifier*. So as per [temp.res.general#4.1](https://eel.is/c++draft/temp.res.general#4.1), this is type-only context.

**Comment by jensmaurer** [comment]
The `T::x` in your example is not a /nested-name-specifier/, it's a /qualified-id/ whose /nested-name-specifier/ is `T::`.
