### ISSUE TITLE
[temp.pre] requires-clause grammar doesn't allow for use of operator with template id

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#513]
Full name of submitter: Anoop Rana

Reference (section label): [temp.pre]

Link to reflector thread (if any): https://stackoverflow.com/questions/78155107/requires-compile-with-msvc-but-rejected-by-gcc

Issue description:

The `!std::is_enum_v<T>` without the parentheses in the below program is ill-formed as per the grammar rules. We see [implementation divergence](https://godbolt.org/z/cjKaPKTjz).

```
#include <type_traits>

template<typename T> requires !std::is_enum_v<T>  //invalid per grammar rules
void foo(T)
{
}

template<typename T> requires std::is_enum_v<T>  //valid per grammar rules
void bar(T)
{
} 
```

I don't see any reason why ` !std::is_enum_v<T>` is disallowed but `std::is_enum_v<T>` is allowed. Note that all compilers accept the program if we remove the `!` from ` std::is_enum_v<T>`. [Demo](https://godbolt.org/z/b3373G1en). That is, I think ` !std::is_enum_v<T>` should also be allowed.

**Comment by t3nsor** [comment]
Isn't this a feature request?

**Comment by ranaanoop** [comment]
> Isn't this a feature request?

Looks more like an oversight to me. I can write a proposal to EWG etc if thats where this should be submitted.

**Comment by jensmaurer** [comment]
I don't think there is a question what the standard says in this situation; the grammar in [temp.pre] is pretty obvious.

Also, the grammar as we have it correctly maps to the decomposition yielding atomic constraints.  For example, `!x` is an atomic constraint by itself.

From a design perspective, negated constraints should be rare (and are expensive to implement), so I'm not seeing an urgent need for change.

Extension requests go to EWG via paper, please.

**Comment by AlanVoore** [comment]
Looking at [this comment](https://stackoverflow.com/questions/78166688/expression-without-parentheses-works-in-one-case-but-not-in-other/78166731#comment137804975_78166688), it seems that it does make sense to allow omitting parentheses for other operators also. 

Note c++ allows omitting parentheses for `||` and `&&` but not for any other operator.

**Comment by jensmaurer** [comment]
> Note c++ allows omitting parentheses for || and && but not for any other operator.

Yes, because stuff connected via || and && is dissected into atomic constraints. Not so for any other operator.

Any changes in this area need a paper to EWG with rationale and analysis of the resulting grammar ambiguities, in particular since contracts are arriving soon.
