### ISSUE TITLE
Defining static const member as const constinit outside class template while inside declaration contain constinit keyword valid or not

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#524]
Full name of submitter:  Anoop Rana

Link to reflector thread (if any): https://stackoverflow.com/questions/78248691/static-data-member-of-template-class-type-constexpr-vs-const-constinit

Issue description:

Currently we can define a const static data member outside the class as `constexpr` as also noted in [CWG 2800](https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#2800).

The problem is that all compilers seems to compile the following invalid(afaik) program, even though the declaration of `ZeroVector` inside the class template uses `const constinit` instead of just `const`. [Demo](https://godbolt.org/z/7PGEqTW4h)

```
#include <array>

template<class T, std::size_t N>
    requires std::is_arithmetic_v<T> && (N >= 1)
class Vector 
{   
public:
    constexpr Vector() noexcept {}
    constexpr ~Vector() = default;
    //-----vvvvvvvvvvvvvvv-------------------->note this should be rejected but all 3 compilers accepts this
    static const constinit Vector ZeroVector;
};  
template<class T, std::size_t N> requires std::is_arithmetic_v<T> && (N >= 1)
const constinit Vector<T, N> Vector<T, N>::ZeroVector{};
int main()
{
    Vector<float, 7> boo = Vector<float, 7>::ZeroVector;
} 
```

The correct way to do this would be to remove the `const constinit` from the declaration that is inside the class and replace it with `const`. That is, the `const constinit` should only be in the definition outside the class as shown below:

```
#include <array>

template<class T, std::size_t N>
    requires std::is_arithmetic_v<T> && (N >= 1)
class Vector 
{   
public:
    constexpr Vector() noexcept {}
    constexpr ~Vector() = default;
    //-----vvvvv---------------------------NOTE ONLY THE CONST HERE
    static const Vector ZeroVector;
};  
template<class T, std::size_t N> requires std::is_arithmetic_v<T> && (N >= 1)
const constinit Vector<T, N> Vector<T, N>::ZeroVector{};
int main()
{
    Vector<float, 7> boo = Vector<float, 7>::ZeroVector;
}  
```

So, is snippet 1 supposed to be ill-formed or well-formed? Afaik snippet 1 is intended to be ill-formed and only snippet 2 is well-formed.

**Comment by ranaanoop** [comment]
Compilers do have some problem when using class template with `const static` data members that are later defined as `constexpr`. Another related question/thread: [Why class templates don't allow const static data member to be defined outside the class as constexpr](https://stackoverflow.com/questions/78254460/why-class-templates-dont-allow-const-static-data-member-to-be-defined-outside-t).

**Comment by frederick-vs-ja** [comment]
I'm not seeing any issue here except for those addressed in CWG2800.

It's clear in [[dcl.constinit] p1](https://eel.is/c++draft/dcl.constinit#1) that `constinit` can be applied to a non-initializing declaration, so the type of the variable doesn't need to be complete at that point. On the other hand, [[dcl.constexpr] p6](https://eel.is/c++draft/dcl.constexpr#6) indicates that `constexpr` requires the declaration of variable to be initializing.

**Comment by ranaanoop** [comment]
> It's clear in [[dcl.constinit] p1](https://eel.is/c++draft/dcl.constinit#1) that constinit can be applied to a non-initializing declaration

@frederick-vs-ja  [dcl.constinit.sentence-2](https://eel.is/c++draft/dcl.constinit#1.sentence-2) seems to suggest the opposite to what you're saying. It says:

> The constinit specifier shall be applied only to a declaration of a variable with static or thread storage duration[.](https://eel.is/c++draft/dcl.constinit#1.sentence-1)
**If the specifier is applied to any declaration of a variable, it shall be applied to the initializing declaration**[.](https://eel.is/c++draft/dcl.constinit#1.sentence-2)
No diagnostic is required if no constinit declaration is reachable at the point of the initializing declaration[.](https://eel.is/c++draft/dcl.constinit#1.sentence-3)

Note the emphasis on "initializing declaration" which means `static const constinit Vector ZeroVector;` in [snippet 1](https://godbolt.org/z/7PGEqTW4h) is invalid. Did you misread this perhaps?

**Comment by ranaanoop** [comment]
@frederick-vs-ja  I see. So both of the snippets in the original issue are well-formed.
