### ISSUE TITLE
[dcl.ptr] No normative wording prohibiting use of pointer to ref-qualified function type

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#525]
Full name of submitter: Anoop Rana

Reference (section label): [dcl.ptr]

Issue description:
Consider the following program:
```
template <class Signature>
struct Decompose;

template <class T>
struct Decompose<void(T)> {
    using Type = T;
};

template <class T>
using FTDecay = typename Decompose<void(T)>::Type;

FTDecay<int()&> x{}; //all 3 compilers accepts this although note in dcl.ptr#4 make this ill-formed
```
Note that  `int()&` is allowed in `FTDecay<int()&>` as per [dcl.fct#10.5](https://timsong-cpp.github.io/cppwp/n4950/dcl.fct#10.5)

> A function type with a [cv-qualifier-seq](https://timsong-cpp.github.io/cppwp/n4950/dcl.decl.general#nt:cv-qualifier-seq) or a [ref-qualifier](https://timsong-cpp.github.io/cppwp/n4950/dcl.decl.general#nt:ref-qualifier) (including a type named by [typedef-name](https://timsong-cpp.github.io/cppwp/n4950/dcl.typedef#nt:typedef-name) ([[dcl.typedef]](https://timsong-cpp.github.io/cppwp/n4950/dcl.typedef), [[temp.param]](https://timsong-cpp.github.io/cppwp/n4950/temp.param))) shall appear only as:
> * the [type-id](https://timsong-cpp.github.io/cppwp/n4950/dcl.name#nt:type-id) of a [template-argument](https://timsong-cpp.github.io/cppwp/n4950/temp.names#nt:template-argument) for a [type-parameter](https://timsong-cpp.github.io/cppwp/n4950/temp.param#nt:type-parameter) ([[temp.arg.type]](https://timsong-cpp.github.io/cppwp/n4950/temp.arg.type))[.](https://timsong-cpp.github.io/cppwp/n4950/dcl.fct#10.sentence-1)

Now, `FTDecay<int()&>` is `int(*)()&` because when we wrote `FTDecay<int()&>` you're explicitly specifying `T` as the *function-type* `int()&`. Next, since a function-type **decays** to a pointer to a function(in many contexts including this), `T` **will be adjusted to** `int(*)()&`. 
Thus, `void(T)` is actually `void (int (*)() &)` and `Type=T` is `int(*)()&`.

But [dcl.ptr#4](https://timsong-cpp.github.io/cppwp/n4950/dcl.ptr#4.sentence-2) says:

> [Note [1](https://timsong-cpp.github.io/cppwp/n4950/dcl.ptr#note-1): Forming a pointer to reference type is ill-formed; see [[dcl.ref]](https://timsong-cpp.github.io/cppwp/n4950/dcl.ref)[.](https://timsong-cpp.github.io/cppwp/n4950/dcl.ptr#4.sentence-1)
**Forming a function pointer type is ill-formed if the function type has [cv-qualifier](https://timsong-cpp.github.io/cppwp/n4950/dcl.decl.general#nt:cv-qualifier)s or a [ref-qualifier](https://timsong-cpp.github.io/cppwp/n4950/dcl.decl.general#nt:ref-qualifier);** see [[dcl.fct]](https://timsong-cpp.github.io/cppwp/n4950/dcl.fct)[.](https://timsong-cpp.github.io/cppwp/n4950/dcl.ptr#4.sentence-2)
Since the address of a bit-field ([[class.bit]](https://timsong-cpp.github.io/cppwp/n4950/class.bit)) cannot be taken, a pointer can never point to a bit-field[.](https://timsong-cpp.github.io/cppwp/n4950/dcl.ptr#4.sentence-3)
— end note]

This seems to make `FTDecay<int()&> x{};` ill-formed. But all compilers accept the code [Demo](https://godbolt.org/z/9fdjE4vje). Bug for all the compilers have been reported. 

I would also like to suggest to make the note a part of the normative wording to make it more authoritative. Maybe this can be done editorially. 
**Suggested resolution:**

Make the [note](https://timsong-cpp.github.io/cppwp/n4950/dcl.ptr#4) a part of the normative wording.

**Comment by jensmaurer** [comment]
I think we agree that compilers are buggy here, because the T in the function parameter type decays to a pointer-to-function, at which point a ref-qualified function type is ill-formed.

I think [dcl.fct] is clear enough in this regard: "shall appear only as".

And no, the note is doing the right thing: it's pointing to [dcl.fct], where the normative restriction already appears.

**Comment by t3nsor** [comment]
The wording of [dcl.fct]/10 is a bit suboptimal in that it refers to both syntactic and non-syntactic constructs, but I agree that there's no doubt that this particular case is ill-formed under the existing wording.

**Comment by ranaanoop** [comment]
@jensmaurer  Btw [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114569) gcc bug. Note in the gcc bug, user Marek pointed out that he thinks the program should compile.

**Comment by jensmaurer** [comment]
I've commented in the gcc bug.
