### ISSUE TITLE
CWG2595 [special] Wording for eligible special member functions is missing a requirement

### ISSUE THREAD

**Issue by brevzin** [cplusplus/CWG#54]
Reference (section label): [special]

Link to reflector thread (if any):

Issue description: The wording in [special]/6 currently reads:

> An eligible special member function is a special member function for which:
> 
> * the function is not deleted,
> * the associated constraints ([temp.constr]), if any, are satisfied, and
> * no special member function of the same kind is more constrained ([temp.constr.order]).

But consider this example (from [StackOverflow](https://stackoverflow.com/q/72540612/2069064) user YurkoFlisk):

```cpp
#include <type_traits>

template<typename T>
concept Int = std::is_same_v<T, int>;

template<typename T>
concept Float = std::is_same_v<T, float>;

template<typename T>
struct Foo
{
    Foo() requires Int<T> = default; // #1
    Foo() requires Int<T> || Float<T> = default; // #2
};
```

Per the wording, for `Foo<float>`, `#1` isn't an eligible default constructor because its constraints aren't satisfied. But `#2` also isn't an eligible default constructor because `#1` is more constrained. But the intent is very much that that `#2` is eligible.

Suggested Resolution: Change the 3rd bullet to:

> no special member function of the same kind <ins>whose associated constraints, if any, are satisfied</ins> is more constrained ([temp.constr.order]).

**Comment by jensmaurer** [comment]
CWG2595
