### ISSUE TITLE
[class.pre] p5 which `final` does the wording refer

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#540]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[class.pre] p5: 
> Whenever a class-key is followed by a class-head-name, the identifier final, and a colon or left brace, **final is interpreted as a class-virt-specifier**.

Consider this example:
````cpp
struct final final{};
````
`final` in the wording `final is interpreted as a class-virt-specifier` is unclear. 

### Suggested resolution
the final that is not a class-head-name is interpreted as a class-virt-specifier

**Comment by jensmaurer** [comment]
Since the wording talks about the "final" after the class-head-name, it's clear enough that a "final" inside the class-head-name is not intended.
