### ISSUE TITLE
CWG2901 [basic.lval] Accessing an object through a different type through which it is type-accessible has undefined semantics

### ISSUE THREAD

**Issue by Eisenwave** [cplusplus/CWG#548]
**Reference (section label):** [basic.lval]

## Issue description

```cpp
int x = -1;
auto y = *reinterpret_cast<unsigned*>(&x);   // read value through different type
*reinterpret_cast<unsigned*>(&x) = UINT_MAX; // modify value through different type
```
An object of type `int` is [type-accessible](https://eel.is/c++draft/basic.lval#def:type-accessible) through a glvalue of type `unsigned`. 

However, [[conv.lval] p3.4](https://eel.is/c++draft/conv.lval#3.4) states:
> Otherwise, the object indicated by the glvalue is read ([[defns.access]](https://eel.is/c++draft/defns.access)), and the value contained in the object is the prvalue result.

We obviously require a prvalue of `unsigned` type for the initialization of `y`, and the `-1` value contained in the `int` object has the wrong type and and cannot be represented as `unsigned`.

Similarly, [[expr.ass] p2](https://eel.is/c++draft/expr.ass#2) states:

> In simple assignment (`=`), the object referred to by the left operand is modified ([[defns.access]](https://eel.is/c++draft/defns.access)) by replacing its value with the result of the right operand.

This cannot be done because it would require storing a `UINT_MAX` value of `unsigned` type in an object of type `int`.

## Suggested resolution

In [[basic.lval] p11](https://eel.is/c++draft/basic.lval#11), add the following sentence:

> When an object of dynamic type <code>T<sub>obj</sub></code> is accessed through a glvalue of type <code>T<sub>ref</sub></code>, <code>T<sub>obj</sub></code> is type-accessible through <code>T<sub>ref</sub></code>, and <code>T<sub>ref</sub></code> is not the same type as <code>T<sub>obj</sub></code>, an unspecified conversion from the stored value to <code>T<sub>ref</sub></code> takes place when the object's value is read, and an unspecified conversion from the to-be-stored value to <code>T<sub>obj</sub></code> takes place when the object is modified.

**Comment by Eisenwave** [comment]
FWIW this feels like yet another big fish and could possibly be blocked by https://github.com/cplusplus/papers/issues/592

**Comment by Eisenwave** [comment]
> Again, I think we ought to say that you just get the value with the same value representation.

I'm tiptoeing around such a solution because while it makes sense for signed/unsigned integers, it needs to work for accessing `int` through `char` glvalues as well, and those don't necessarily have the same object representation.

I'm just getting us from UB by omission to unspecified. Not sure with what wording this could really be fixed up, if any. Perhaps this needs a paper.

> Your interpretation "0u is not a valid value for int" contradicts current wording such as http://eel.is/c++draft/basic.fundamental#6 "Further, each value has the same representation in both types" which implies that two objects of different type can actually have a common value.

Hmm yeah, fair point. I think the current wording doesn't strictly attach a type to a value for fundamental types, but it's more mathematical. `0` is literally the same value no matter which integral type or floating-point type stores zero. Negative numbers are a good example of where it breaks though; I'll update the issue.

**Comment by Eisenwave** [comment]
There's also a pretty good chance that this is NAD, everything is working as intended, and you are not permitted to type pun `int` as `unsigned` except for where the value is the same.

However, if so, we should have some examples that demonstrate that, such as:
```cpp
int p = 0;
auto up = *reinterpret_cast<unsigned*>(&p);   // OK, up has value 0

int n = -1;
auto un = *reinterpret_cast<unsigned*>(&n);   // undefined behavior
```

**Comment by jensmaurer** [comment]
The "char, unsigned char, std::byte" case in [basic.lval] p11 is the object representation case. Let's not try to fix this here, but defer to [P1839](https://wg21.link/p1839).

For the signed/unsigned case, I think that's clearly an (isolated) hole in the specification: We say access is allowed, but we don't say what the result is.  For sure after we moved to a mandatory two's complement representation, it seems abundantly clear that you get the congruent value per [basic.fundamental] p3 and p5.  That's a CWG issue; wording suggestion welcome.

**Comment by frederick-vs-ja** [comment]
I guess the following resolution may be wanted. Given that the static and dynamic types of a scalar object is always the same, perhaps we shouldn't say "dynamic type" in [conv.lval] p3.4 and [expr.ass] p2.

> Let's not try to fix this here, but defer to [P1839](https://wg21.link/p1839).

I guess this is OK, but it's somehow weird to me to just skip the object representation parts.

## Suggested resolution

Modify [conv.lval] as indicated
> (3.4) - Otherwise, <ins>**let `U` and `V` be the _cv_-unqualified version of `T` and the type of the object, repectively.**</ins> ~t~<ins>**T**</ins>he object indicated by the glvalue is read ([defns.access]), and <ins>**the prvalue result is**</ins>
>   - the value contained in the object ~is the prvalue result~ <ins> **if `U` is same as `V`,**</ins>
>   - <ins>**otherwise, the value whose value representation ([basic.types.general]) is same as the value contained in the object if `U` is a signed or unsigned version of `V`,**</ins>
>   - <ins>**otherwise, the value of the first element of the object representation of the object**</ins>.
>
> If the result is an erroneous value ([basic.indet]) and the bits in the value representation are not valid for the object's type, the behavior is undefined.

Modify [expr.ass] as indicated
> 2. In simple assignment (`=`), <ins>**let `U` and `V` be the _cv_-unqualified version of the type of the left operand and the object referred to by it, repectively, and let `x` be the result of the right operand.**</ins> ~t~<ins>**T**</ins>he object referred to by the left operand is modified ([defns.access])<ins>**.**</ins> ~by replacing its value with the result of the right operand.~ <ins>**If `U` is same as `V`, the value of the object is replaced with `x`. Otherwise, if `U` is a signed or unsigned version of `V`, the value of the object is replaced with the `V` value whose value representation ([basic.types.general]) is same as  `x`. Otherwise, the first element of the object representation of the object is replaced with  `x`.**</ins>

**Comment by Extra-Creativity** [comment]
> The "char, unsigned char, std::byte" case in [basic.lval] p11 is the object representation case. Let's not try to fix this here, but defer to [P1839](https://wg21.link/p1839).

It seems that P1839 has completely stopped though previously I think it's already accepted as DR in C++23. See https://github.com/cplusplus/papers/issues/592. So what happened?

**Comment by t3nsor** [comment]
> > The "char, unsigned char, std::byte" case in [basic.lval] p11 is the object representation case. Let's not try to fix this here, but defer to [P1839](https://wg21.link/p1839).
> 
> It seems that P1839 has completely stopped though previously I think it's already accepted as DR in C++23. See [cplusplus/papers#592](https://github.com/cplusplus/papers/issues/592). So what happened?

This is not really the right forum to discuss this, but basically the paper was reviewed by CWG, and certain issues were found that have no known resolution, which are described in the last section of the paper.

**Comment by jensmaurer** [comment]
CWG2901
