### ISSUE TITLE
CWG2074 [temp.res] Is a local class defined in template declaration considered as a dependent type

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#55]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

Consider this example:
````cpp
template<class T>
auto show(T){
    struct S{};
    fun(S{});
}
int main(){}
````
GCC and Clang both accept this example. the name `fun` is looked up from where it appears and nothing can be found. Only if `fun` is a dependent name will the lookup be performed in the instantiation context, according to [temp.res.general] p1. [temp.dep.general] p2 says that `fun` is a dependent name only if the expression `S{}` is [type-dependent](https://eel.is/c++draft/temp.res#temp.dep.expr). First, [temp.dep.expr] lack the details about **explicit type conversion expressions**. Second, it is not clear whether such a local class is a dependent type.

**Comment by JohelEGP** [comment]
> Second, it is not clear whether such a local class is a dependent type.

According to https://eel.is/c++draft/temp.res#temp.dep.type-7, `S` isn't dependent.

**Comment by xmh0511** [comment]
Yes, the type `S` is clearly not a dependent type in the current wording. I just meant could such a templated entity(type) be a dependent type? Observing the behavior of implementations, they all consider `S{}` as a type-dependent expression, whose type is associated with type `S`.

The one bullet that specifies whether an id-expression is type-dependent is defined as the following:
> associated by name lookup with one or more declarations declared with a dependent type

Analogy, an explicit type conversion expression might be type-dependent if its specified type is a dependent type.

**Comment by jensmaurer** [comment]
What exactly is the problem here? The example given above is ill-formed, no diagnostic required, because there cannot possibly be a valid specialization ("fun" is not declared).

The one issue I noticed is that [temp.dep.expr] p3 covers S(), but does not cover S{}. That's a defect.

**Comment by xmh0511** [comment]
> The example given above is ill-formed, no diagnostic required, because there cannot possibly be a valid specialization ("fun" is not declared).

Yes, I omitted [temp.res.general] p6.4
> a hypothetical instantiation of a template immediately following its definition would be ill-formed due to a construct that does not depend on a template parameter, or


***
> The one issue I noticed is that [temp.dep.expr] p3 covers S(), but does not cover S{}. That's a defect.

Yes, however, Is `S` considered as a dependent type?

**Comment by jensmaurer** [comment]
> Yes, however, Is S considered as a dependent type?

It seems the answer is "no". [temp.dep.type] p7 doesn't make it dependent.

Why is that state of affairs a defect? (As a rule of thumb, something is dependent if there would be a way to create a template specialization such that the "something" might refer to something else due to the specialization. I'm not seeing this for a local class of a function template.)

**Comment by xmh0511** [comment]
[temp.dep.type] p7.5 seems to admit this example  
> A type is dependent if it is
>> - a template parameter,
>> - [...]
>> - a compound type constructed from any dependent type,  

Consider this example:
````cpp
template<class T>
void fun(T){
    struct B:T{};
    struct A{
      T a;
      operator T(){
         return a;
      }
    };
    show(B{});
    show(A{});
}
struct C{};
void show(C);
int main(){
   fun(C{});
}
````

Yes, in consensus, `S` in my first example is not a dependent type. The only defect in this post, as you noticed: [temp.dep.expr]
 should cover *simple-type-specifier braced-init-list*.   

***  

BTW, since [temp.dep.expr] has covered simple-type-specifier ( expression-list <sub>opt</sub> ), why doesn't it mentione ***typename-specifier** ( expression-list <sub>opt</sub>)*

**Comment by jensmaurer** [comment]
The missing cases in [temp.dep.expr] is CWG2405.
The concern about local classes of function templates is CWG2074.
