### ISSUE TITLE
CWG2905 [temp.dep.constexpr] value-dependence of `noexcept` `(` *expression* `)`

### ISSUE THREAD

**Issue by MitalAshok** [cplusplus/CWG#554]
Full name of submitter: Mital Ashok 

Reference: [temp.dep.constexpr]

Issue description: Whether the operand of a `noexcept` operator is type-dependent is not enough to know if the `noexcept` operator is value-dependent. There are plenty of non-type-dependent expressions where whether or not it is potentially-throwing is dependent.

For example:

```c++
template<typename T>
void f() {
    noexcept(new int(T{}));
    noexcept(static_cast<int>(T{}));
    noexcept(typeid(*T{}));
    noexcept(delete T{});
}
```

GCC already treats all of these as value-dependent. Clang treats `noexcept(new int(T{}))` as a not value-dependent `false` but the rest of them as value-dependent.

Suggested resolution:

Remove `noexcept` from [temp.dep.constexpr]p2 so it becomes value-dependent if its operand is value-dependent according to [temp.dep.constexpr]p1

> Expressions of the following form are value-dependent if the *unary-expression* or *expression* is type-dependent or the *type-id* is dependent:  
> 	`sizeof` *unary-expression*
> 	[...]
> 	<del>`noexcept` `(` *expression* `)`

**Comment by jensmaurer** [comment]
CWG2905

**Comment by MitalAshok** [comment]
Actually this seems this is at odds with [CWG1074](https://cplusplus.github.io/CWG/issues/1074.html).

Also value-dependence is only for constant expressions, which `noexcept` doesn't require (esp. since throwing an exception is not a constant expression)

Also some cases are missing from value-dependence still,

```c++
struct X {
    virtual void f();
};

template<typename T>
void g() {
    X value;
    noexcept(dynamic_cast<T&>(value));
}
```

(I think these are all caught by [CWG2066](https://cplusplus.github.io/CWG/issues/2066.html) / [CWG2109](https://cplusplus.github.io/CWG/issues/2109.html))

Perhaps `noexcept` should not rely on value-dependence at all and be:

> <ins>`noexcept` `(` *expression* `)` is value-dependent if *expression* is an expression involving a template parameter<ins>

(See also: [CWG1172](https://cplusplus.github.io/CWG/issues/1172.html), making this easier if "instantiation-dependent" was defined)

**Comment by jensmaurer** [comment]
Yeah.  Updated.
