### ISSUE TITLE
CWG2910 [basic.def.odr] Effect of requirement-parameter-lists on odr-usability

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [cplusplus/CWG#561]
Full name of submitter (unless configured in github; will be published with the issue): Hubert Tong

Reference (section label): basic.def.odr

Link to reflector thread (if any): N/A

Issue description:
Consider
```cpp
bool f() {
  constexpr int z = 42;
  return requires {
    sizeof(int [*&z]);
  } && requires (int x) {
    sizeof(int [*&z]);
  };
}
```

According to https://wg21.link/basic.scope.param, a function parameter scope is produced for the second _requires-expression_.

This means that, under https://wg21.link/basic.def.odr#10, there is an intervening function parameter scope that prevents `z` from being odr-usable in the context where it is named in the second _requires-expression_. There does not appear to be a good reason for the two _requires-expression_&zwnj;s to behave differently.

Suggested resolution:
Insert in https://eel.is/c++draft/basic.def.odr#10.2.2:
> - the intervening scope is the function parameter scope of <ins>a _requires-expression_ or </ins>a _lambda-expression_ [...]

**Comment by jensmaurer** [comment]
CWG2910
