### ISSUE TITLE
CWG2911 [expr.prim.req.general] Unclear meaning of expressions "appearing within" versus subexpressions

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [cplusplus/CWG#562]
Full name of submitter (unless configured in github; will be published with the issue): Hubert Tong

Reference (section label): expr.prim.req.general

Link to reflector thread (if any): N/A

Issue description:
According to https://wg21.link/expr.prim.req.general#2:
> Expressions appearing within a _requirement-body_ are unevaluated operands

It is clearly meant to not encompass, e.g., _constant-expression_&zwnj;s, appearing within the _requirement-body_ but the unfriendly reading is possible.

It is also unclear what this means, e.g., with respect to expressions that appear within a _requirement-body_ as part of the body of a lambda expression.

For example, does `x` in the lambda below refer to a `const int` capture? Implementations agree that it does.
```cpp
void q(int *);
int &q(const int *);

template <typename T>
constexpr bool f() {
  T x;
  constexpr bool v = requires {
    [=] { ++q(&x); };
  };
  return v;
}

static_assert(f<int>());  // OK
```

Suggested resolution:
Strike in https://wg21.link/expr.prim.req.general#2:
> A _requires-expression_ is a prvalue of type `bool` whose value is described below.<s> Expressions appearing within a _requirement-body_ are unevaluated operands.</s>

Modify in https://wg21.link/expr.prim.req.simple#1:
> A _simple-requirement_ asserts the validity of an _expression_.<ins> The _expression_ is an unevaluated operand ([expr.context]).</ins>
[Note: The enclosing _requires-expression_ will evaluate to `false` if substitution of template arguments into the
_expression_ fails.<del> The _expression_ is an unevaluated operand ([expr.context]).</del> —_end note_]

Modify in https://wg21.link/expr.prim.req.compound#1:
> A _compound-requirement_ asserts properties of the expression _E_.<ins> The _expression_ is an unevaluated operand ([expr.context]).</ins> [...]

Modify in https://wg21.link/expr.context#1:
> In some contexts, unevaluated operands appear (<del>[expr.prim.req], </del><ins>[expr.prim.req.simple], [expr.prim.req.compound], </ins>[expr.typeid], [expr.sizeof], [expr.unary.noexcept], [dcl.type.decltype], [temp.pre], [temp.concept]). An unevaluated operand is not evaluated.

**Comment by jensmaurer** [comment]
CWG2911
