### ISSUE TITLE
[dcl.fct.default] Does evaluation of lambda used as default argument means to create different closure types each time the function is called without argument

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#565]
Full name of submitter: Anoop Rana 

Reference (section label): [dcl.fct.default]

Link to reflector thread (if any): https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115722

Issue description:

The following program produced the output `12`  in all three major compilers but current wording seems to make the output `11`. [Demo](https://godbolt.org/z/cq6fd8oK4)

```
#include <iostream>

int foo(int x = [](){ static int x = 0; return ++x; }()) { return x; };

int main() {
    std::cout << foo() << foo(); // prints "12", not "11"
}
```

Currently, [dcl.fct.default](https://eel.is/c++draft/dcl.fct.default#9) says:

> A **default argument is evaluated each time the function is called with no argument for the corresponding parameter.** A parameter shall not appear as a potentially-evaluated expression in a default argument

And [expr.prim.lambda.closure](https://eel.is/c++draft/expr.prim#lambda.closure-1) says:

> The **type of a lambda-expression (which is also the type of the closure object) is a unique, unnamed non-union class type**, called the closure type, whose properties are described below.

From the above quoted references it seems that the output should be `11`. But all three compilers produce `12`. So it should be made clear if the lambda type in a default argument gets defined once even if it is evaluated twice.

**Suggested Resolution**:

Maybe something like following in [expr.prim.lambda.closure] would be more clear:

> The type of a lambda-expression (which is also the type of the closure object) **while being definition(not during evaluation)** is a unique, unnamed non-union class type, called the closure type, whose properties are described below.

Note the added "while being defined(not during evaluation)" in the above modified reference.

**Comment by jensmaurer** [comment]
Evaluation never creates new types (absent reflection), so why should this differ here?

Your question becomes a bit more interesting for instantiations of a template, but that's not what this issue talks about.

**Comment by ranaanoop** [comment]
@jensmaurer  But if this is used in a multiple header project(like we usually declare the function in header and then include that header in multiple source files giving us multiple TUs), then there will be unique types for each TUs and the program will have undefined behavior no diagnostic required, right? 

So is the standard clear that this doesn't happen in single TU. That is, in single TU the program is well-formed but in multiple TUs including and using the said function it will have undefined behavior no diagnostic required.

**Comment by t3nsor** [comment]
As Jens often says, this issue tracker is not a tutorial forum for the standard.

**Comment by AlanVoore** [comment]
> As Jens often says, this issue tracker is not a tutorial forum for the standard.

You're no one to discourage people from having a discussion. People can and should openly talk/ask about what they think is right or wrong. Just because you don't like the question asked or you think it is too primitive/basic to be asked here doesn't mean everyone else thinks the same. More importantly, anyone can and should expression their view/doubts and asks question(if any) without thinking of things like this is not a forum etc. I clearly gave the references from the standard which I think explains the behavior. And then I asked if I was right or not. People are allowed to answer it. 

The issue is already closed, so what is the problem in providing a reference and simply asking. I accept that there is also the `std-discussion` mailing list for this but I came across this issue and just asked about it in the current issue instead of creating a new thread in the `std-discussion`. I also like the formatting option that github provide as opposed to gmail.

**Comment by t3nsor** [comment]
This issue tracker exists for a very narrow topic. You can report core issues here and Jens, as chair of CWG, can then schedule them for discussion by CWG. Jens, who has many responsibilities within the committee and is a busy man, has to read all the posts here to make sure he doesn't miss any core issues or any details relevant to core issues. When people post off-topic, they generate email that he then has to read despite it being off-topic.

If you feel that your question is on-topic, please rephrase it as a potential core issue. Would you like wording to be added to the example in the standard to clarify that the program is well-formed if it has only a single translation unit?

For questions about the meaning of the standard, there are many other places to ask, where everyone can participate as much or as little as they please.
