### ISSUE TITLE
[expr.prim.id] No normative wording that makes the program ill-formed but only a note exists

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#568]
Full name of submitter: Anoop Rana

Reference: [expr.prim.id]

Link to reflector thread (if any): https://stackoverflow.com/questions/78707693/msvc-rejects-program-with-member-function-call-while-gcc-and-clang-accept

Issue description:  

While answering a [question](https://stackoverflow.com/questions/78707693/msvc-rejects-program-with-member-function-call-while-gcc-and-clang-accept) I noticed that currently there is no normative wording that makes the below modified program ill-formed. In fact, we see [compiler divergence](https://godbolt.org/z/4Gnf955e6) for the modified program. Note that the below given program is different from the [question](https://stackoverflow.com/questions/78707693/msvc-rejects-program-with-member-function-call-while-gcc-and-clang-accept) in that here `g` is a static member function. 

```
struct C  
{
  void f(this C self);  
  static void g() 
  {
       C::f();      //#1: gcc accepts but clang and msvc rejects
    // (C::f)();    //#2: all three compilers rejects

  }
};
int main()
{ 

}
```

Gcc accepts `#1` while clang and msvc rejects it. OTOH, all three compilers reject `#2`. I think the intention is to make both `1#` and `#2` ill-formed as can be seen from **non-normative note** in [expr.prim.id](https://eel.is/c++draft/expr.prim.id#general-note-2) saying:

> [Note [2](https://eel.is/c++draft/expr.prim.id#general-note-2): If C is not X or a base class of X, the class member access expression is ill-formed[.](https://eel.is/c++draft/expr.prim.id#general-2.sentence-2)
Also, **if the [id-expression](https://eel.is/c++draft/expr.prim.id#nt:id-expression) occurs within a static or explicit object member function, the class member access is ill-formed[.](https://eel.is/c++draft/expr.prim.id#general-2.sentence-3)**
— end note]

As we can see the note intend to make `#1` and `#2` ill-formed afaik. So this note should be made normative by changing it from a note to a bullet point in [expr.prim.id]. 

<h4>Suggested Resolution</h4>

Make the note normative by changing it to a bullet etc point.

**Comment by frederick-vs-ja** [comment]
The sentence was added by CWG2771.

I guess the suggestion would be normatively redundant and it's better to keep the sentence in a note. Given [[expr.prim.id.general] p2.3](https://eel.is/c++draft/expr.prim.id.general#2.3) reads
> if _E_ is a _qualified-id_, _E_ is not the un-parenthesized operand of the unary `&` operator ([expr.unary.op]),

`C::f` needs to be transformed into `(*this).C::f` in `#1`, which is clearly ill-formed in a static or explicit object member function.

This is already reported as the bug of GCC (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113388). The standard wording and other compilers ([Godbolt link](https://godbolt.org/z/PaW9P6oxo)) are fine here.

**Comment by t3nsor** [comment]
The "missing" normative wording is [[expr.prim.this]/3](https://eel.is/c++draft/expr.prim.this#3), which makes it illegal to mention `this` in a static member function.

Also note that [CWG2902](https://cplusplus.github.io/CWG/issues/2902.html) may make the wording easier to read for this case. It attempts to reorganize the specification so that it either directly tells you that the program is ill-formed, or tells you where to look (via cross-reference).
