### ISSUE TITLE
CWG2913 [temp.deduct.guide] *requires-clause* in the wrong position in the grammar for *deduction-guide*

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/CWG#576]
Reference (section label): [temp.deduct.guide]

Issue description: CWG2707 added the missing *requires-clause* to the grammar for *deduction-guide*, but added it in a position that is inconsistent with function declarations. Since the grammar for deduction guides is supposed to match that of other declarator-based declarations, the *requires-clause* should be at the end.

Suggested resolution:

Change in [temp.deduct.guide]/1:

> *deduction-guide*: 
> * *explicit-specifier*<sub>opt</sub> *template-name* `(` *parameter-declaration-clause* `)` <del>*requires-clause*<sub>opt</sub></del> `->` *simple-template-id* <ins>*requires-clause*<sub>opt</sub></ins> `;`

**Comment by jensmaurer** [comment]
CWG2913
