### ISSUE TITLE
[basic.scope.scope] Is void adjustment and cv-qualifier adjustment applied when considering corresponding overload

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#577]
Full name of submitter: Anoop Rana

Reference (section label): [basic.scope.scope]

Issue description: 
Consider the following program for which we see [compiler divergence](https://godbolt.org/z/4b93z46MK) but which seems to be **well-formed** as per current wording. Out of the 4 major compilers only gcc accept the code while all other three(clang, edg and msvc) rejects it.

```

struct A {
    void f(this void);
    void f();          //gcc: OK, EDG:Nope, Clang: Nope, MSVC:Nope
};
```

As per my understanding this is well-formed for the reason explained below.

From [basic.scope.scope#3](https://eel.is/c++draft/basic.scope.scope#3) and [basic.scope.scope#4.4](https://eel.is/c++draft/basic.scope.scope#4.4):

> Two non-static member functions have corresponding object parameters if: 
> * **exactly one is an implicit object member function with no ref-qualifier and the types of their object parameters ([dcl.fct]), after removing top-level references, are the same**, or
> * their object parameters have the same type.
>
> **Two function** or function template **declarations declare corresponding overloads if**: 
> * both declare functions with the same non-object-parameter-type-list,17 equivalent ([temp.over.link]) trailing requires-clauses (if any, except as specified in [temp.friend]), **and, if both are non-static members, they have corresponding object parameters**, or

Now let's apply this our example.  First, here exactly one of the declarations is an implicit object member function with no ref-qualifier and the type of object parameter of `void f(this void);` is `void` which is different from the type of the object parameter of `void f();` which is `A&`. That is, the former has `void` as its object parameter while the latter has `A&`.

Thus both [basic.scope.scope#3](https://eel.is/c++draft/basic.scope.scope#3) and [basic.scope.scope#4.4](https://eel.is/c++draft/basic.scope.scope#4.4) are violated and hence the program is well-formed. As of now gcc is the only compiler accepting this and other three compilers rejects this. 

I think the rejecting compiler are incorrectly taking [dcl.fct#4.sentence-4](https://timsong-cpp.github.io/cppwp/n4950/dcl.fct#4.sentence-4) into account which says:

> A parameter list consisting of a single unnamed parameter of non-dependent type void is equivalent to an empty parameter list[.](https://timsong-cpp.github.io/cppwp/n4950/dcl.fct#4.sentence-4)

To my understanding this [dcl.fct#4](https://timsong-cpp.github.io/cppwp/n4950/dcl.fct#4.sentence-4) cannot be used here in our program because the object parameters are compared directly without any void or cv-qualifier adjustments. I mean in [basic.scope.scope#3](https://eel.is/c++draft/basic.scope.scope#3) we're not comparing the _parameter-type-list_  but instead comparing the object parameters directly(with reference removal). 

So it should be made clear if, void adjustment, cv-qualifer adjustment are also supposed to be applied here along with reference removal. To my understanding [dcl.fct#4](https://timsong-cpp.github.io/cppwp/n4950/dcl.fct#4.sentence-4) is not to be used here because [basic.scope.scope#3](https://eel.is/c++draft/basic.scope.scope#3) explicitly only mentioned reference removal.

**Comment by ranaanoop** [comment]
There is a similar situation. Consider the example:

```
struct C
{
    void j(this const C);
    void j() const ;             //#1: Clang:Nope, gcc:OK, msvc:OK
};
```
This seems to be ill-formed because the former has `const C` as object parameter and the latter also has `const C` as the object parameter(implicit) after removing reference. Thus these two declare corresponding overloads and hence the latter is a redeclaration of the former. 

Now, again the accepting compilers(gcc and msvc here) are incorrectly taking into account [dcl.fct#5](https://timsong-cpp.github.io/cppwp/n4950/dcl.fct#5.sentence-4) that says:

> After producing the list of parameter types, any top-level [cv-qualifier](https://timsong-cpp.github.io/cppwp/n4950/dcl.decl.general#nt:cv-qualifier)s modifying a parameter type are deleted when forming the function type[.](https://timsong-cpp.github.io/cppwp/n4950/dcl.fct#5.sentence-4). 

The above seems to imply that after removing top-level cv-qualifer the former has parameter of type `C` while the latter has parameter of type `const C` which will make the program well-formed.

But to my understanding this [dcl.fct#5](https://timsong-cpp.github.io/cppwp/n4950/dcl.fct#5.sentence-4) cannot be used here because [basic.scope.scope#3](https://eel.is/c++draft/basic.scope.scope#3) is not comparing _parameter-type-list_ but instead object parameters directly. Hence this is ill-formed. 

So it s should be made clear(since many compilers are diverging) say by adding a note or some clause that object parameters are directly compared(after removing reference) and not the parameter-type-list.

**Comment by jensmaurer** [comment]
Superseded by #579
