### ISSUE TITLE
CWG2915 [dcl.fct] Make "this void" invalid as explicit object parameter

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#578]
Full name of submitter: Anoop Rana

Reference (section label): [dcl.fct]

Issue description:

Currently there is no restriction on the type of the explicit object parameter. Consider the following example for which we observe [compiler divergence](https://godbolt.org/z/64rvWTsTP):

```
struct A {
    void f(this void);

};
int main() 
{
    A a;
    a.f(); //gcc: Nope, msvc:Nope, clang:OK, EDG:OK
}
```

If [dcl.fct] is applied here, then it will turn the explicit object member function into an implicit object member function with no non-object parameter(which I don't think is intended). If so, then `a.f();` is well-formed. But turning an explicit object member function to an implicit object member function may be unexpected and surprising and I don't think it should be valid. 

So we can just disallow the use of `void` in the explicit object parameter. That is, make `this void` invalid altogether. 

Note that there is also issue [Is void adjustment and cv-qualifier adjustment applied when considering corresponding overload](https://github.com/cplusplus/CWG/issues/577) that explains that overloading explicit member function with `this void` with implicit object member function with no non-object parameter, is well-formed as per current wording. With the suggestion of this current issue(by making `this void` ill-formed), the program given in that [issue](https://github.com/cplusplus/CWG/issues/577) will also become ill-formed. 

**Suggested resolution:**

Make `this void` invalid as explicit object parameter.

**Comment by jensmaurer** [comment]
CWG2915

**Comment by ranaanoop** [comment]
@jensmaurer I think you mistyped(made a typo). In the CWG's resolution, shouldn't _non-object parameter_ be replaced by _object parameter_?

**Comment by ranaanoop** [comment]
@jensmaurer In the CWG, the term _non-object parameter_ should be replaced by _object parameter_ since we're dealing with `this void` which is an explicit **object parameter** not a non-object parameter.

**Comment by t3nsor** [comment]
Read the proposed resolution more carefully.

"A parameter list consisting of a single unnamed non-object parameter of non-dependent type void is equivalent to an empty parameter list."

So `(void)`, which has a non-object parameter, is equivalent to `()`. But `(this void)` is not equivalent to `()`, so the next sentence makes it ill-formed.
