### ISSUE TITLE
[dcl.fct] Stale reference to two forms of function declarator

### ISSUE THREAD

**Issue by t3nsor** [cplusplus/CWG#588]
**Full name of submitter:** Brian Bi

**Reference (section label):** [dcl.fct]

**Issue description:** After [CWG2476](https://cplusplus.github.io/CWG/issues/2476.html) we no longer have two allowable forms of a function declarator, one with a *trailing-return-type* and one without. We have a single form that has an optional *trailing-return-type*. So, paragraph 2, which says "A type of either form is a function type", no longer makes sense.

**Suggested resolution:** Will be provided later. Ideally, the resolution should also move up the definition of "function type" to before the point where it is first used in this section.

**Comment by jensmaurer** [comment]
This feels editorial to me.
