### ISSUE TITLE
[over.match.ctor] Make initializer list constructor that is also a default ctor preferrable over non-initializer list ctor that is also a default ctor when braced init list is used

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#591]
Full name of submitter: Anoop Rana

Reference (section label): [dcl.init#list]

Issue description:

Usually a initializer list constructor is preferred for a braced init list. But this does not seem to be the case when the initializer list constructor is also a default constructor. Consider the following example for instance: [Demo](https://godbolt.org/z/K71Ys1MKe)

```
#include <initializer_list>

struct C
{ 
    C(){}
    C(std::initializer_list<int> i = {3})
    {
    }  
};

int main()
{
    C d{};   //clang:Ok, gcc:No, MSVC: No, EDG: No
}
```

As we can see only clang accepts the above code choosing the initializer_list ctor, while all other three compilers reject the program. This seems to be ill-formed afaik because none of the ctors is a better match than the other. But intuitively I think the initializer_list constructor should be preferred here for the braced init list instead of the `C::C()` as is usually the case when non-default ctors are considered. This will make the behavior more consistent.  

There can also be defective wording here. We go to [dcl.init#list-3.5](https://eel.is/c++draft/dcl.init#list-3.5) which will lead to value initialization but [dcl.init#general](https://eel.is/c++draft/dcl.init#general-9.1) seem to not specify the ctor that will be selected here.

**Comment by t3nsor** [comment]
I think it would be very unintuitive if `C d{};` calls an initializer-list constructor in some manner other than using `{}` to initialize the `std::initializer_list`. I think you need stronger motivation for this change and you need to present it to EWG

**Comment by ranaanoop** [comment]
@t3nsor  But all compilers already use initializer list ctor for `C d{};` if you remove the default constructor. See [demo](https://godbolt.org/z/WWG7hb4dj)

```
struct C
{
    
    
    C(std::initializer_list<int> i ={3})
    {
std::cout << "init";
    }
};

int main()
{
    C d{};   //all compilers use initializer list ctor
}
```
So I don't think it is unintuitive. It is consistent instead.

**Comment by ranaanoop** [comment]
I am closing this in light of the [new issue](https://github.com/cplusplus/CWG/issues/592) I created. It covers more cases with explanation. Thank you for the time and effort.
