### ISSUE TITLE
[dcl.init] Inconsistencies in list initialization syntax when initializer list ctor is also a default constructor 

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#592]
Full name of submitter: Anoop Rana

Reference (section label): [dcl.init]

Link to reflector thread (if any): https://stackoverflow.com/q/78836456/12002570

**tldr**: The main problem is that `D d{};` seems to be well-formed as per current wording/[example](https://eel.is/c++draft/dcl.init#list-example-4) because a default ctor with no parameter is preferred over an initializer list ctor even in list-initialization. 

Issue description:

The `S s4 = {};`example given in [dcl.init#list-example-4](https://eel.is/c++draft/dcl.init#list-example-4) seem to imply that a default ctor with no parameter is to be preferred over an initializer list ctor that is **not also a default ctor even though the initializer `()` can match both ctors** in the [example](https://eel.is/c++draft/dcl.init#list-example-4). Here is the [Demo](https://godbolt.org/z/6a3sz9Wvb). For the same reason I think `D::D()` should be preferred over `D::D(initializer_list<int>)` in the below shown contrived example. That is to say, I think `D d{};` is also well-formed as per current wording but only clang accepts it while gcc and msvc rejects it. To show all the issues, below is a snippet that tries to cover all cases:

```
#include <initializer_list>
#include <iostream>

struct A
{
   A(std::initializer_list<int> i){std::cout << "A's init\n";}
};
struct B
{
   //                                         vvv note this is also a default ctor
   B(std::initializer_list<int> i = {3}){std::cout << "B's init\n";}
};
struct C
{
    
    C(){std::cout << "C's parenthesized\n";}
    C(std::initializer_list<int> i)
    {
        std::cout << "C's init\n";
    }  
};
struct D
{
    
    D(){std::cout << "D's parenthesized\n";}
   //                                          vvv    again this is also a default ctor
    D(std::initializer_list<int> i = {3})
    {
        std::cout << "D's init\n";
    }  
};
int main()
{
    A a{};   //this uses A::A(initializer_list<int>) as expected
    B b{};  //uses B::B(initializer_list) as expected
    C c{};  //uses C::C() over C::C(initializer_list) meaning it is a better match for the initializer ()
    D d{};  //clang uses D::D(initializer_list) over D::D() while GCC and MSVC rejects this 
}
```
Now, let's start covering each case one by one separately so that we don't mix things together. 

<h4>Case 1</h4>

Here we consider the validity of `A a{};` 

This is well-formed because  `A` don't have a default ctor meaning we go to [dcl.init#list-3.7](https://eel.is/c++draft/dcl.init#list-3.7):

> Otherwise, **if T is a class type, constructors are considered[.](https://eel.is/c++draft/dcl.init#list-3.7.sentence-1)
The applicable constructors are enumerated and the best one is chosen through overload resolution** ([[over.match]](https://eel.is/c++draft/over.match), [[over.match.list]](https://eel.is/c++draft/over.match.list))[.](https://eel.is/c++draft/dcl.init#list-3.7.sentence-2)
If a narrowing conversion (see below) is required to convert any of the arguments, the program is ill-formed[.](https://eel.is/c++draft/dcl.init#list-3.7.sentence-3)

So we move onto [over.match.list](https://eel.is/c++draft/over.match.list):

> If the initializer list is not empty or **T has no default constructor, overload resolution is first performed where the candidate functions are the initializer-list constructors** ([[dcl.init.list]](https://eel.is/c++draft/dcl.init.list)) of the class T and the argument list consists of the initializer list as a single argument[.](https://eel.is/c++draft/over.match.list#1.1.sentence-1)

This means that the initializer_list ctor `A::A(initializer_list<int>)` will be used here which is what we see. This was the simplest and cleanest to understand of the four cases imo. 

<h4>Case 2</h4>

Here we consider the validity of `B b{};` In this case, _we do have a default ctor_ which is the`B::B(initializer_list<int>)` itself. So this time [dcl.init#list-3.5](https://eel.is/c++draft/dcl.init#list-3.5) is applicable:

> Otherwise, if the initializer list has no elements and T is a class type with a default constructor, the **object is value-initialized**[.](https://eel.is/c++draft/dcl.init#list-3.5.sentence-1)

The above means the object will be [value-initialized](https://eel.is/c++draft/dcl.init#general-9):

> If T is a (possibly cv-qualified) class type ([[class]](https://eel.is/c++draft/class)), then let C be the constructor selected to default-initialize the object, if any[.](https://eel.is/c++draft/dcl.init#general-9.1.sentence-1)
If C is not user-provided, the object is first zero-initialized[.](https://eel.is/c++draft/dcl.init#general-9.1.sentence-2)
In all cases, the **object is then default-initialized**[.](https://eel.is/c++draft/dcl.init#general-9.1.sentence-3)

This means that the object will be default initialized. So we go to [default initialization](https://eel.is/c++draft/dcl.init#general-7):

> If T is a (possibly cv-qualified) class type ([[class]](https://eel.is/c++draft/class)), constructors are considered[.](https://eel.is/c++draft/dcl.init#general-7.1.sentence-1)
The applicable constructors are enumerated ([[over.match.ctor]](https://eel.is/c++draft/over.match.ctor)), and the best one **for the [initializer](https://eel.is/c++draft/dcl.init#nt:initializer) `()`** is chosen through overload resolution ([[over.match]](https://eel.is/c++draft/over.match))[.](https://eel.is/c++draft/dcl.init#general-7.1.sentence-2)
The constructor thus selected is called, with an empty argument list, to initialize the object[.](https://eel.is/c++draft/dcl.init#general-7.1.sentence-3)

Note the emphais on _**for the initializer `( )`**_ in the above quoted reference. Now as per [over.match.ctor](https://eel.is/c++draft/over.match.ctor) the initializer list ctor that is also a defalt ctor here is enumerated as a candidate and finally through [over.match](https://eel.is/c++draft/over.match) this initializer list ctor wil be used for the initializer `()`. I am emphasizing _initializer `()`_ again and again because I want to highlight that a initializer list ctor can be used with initializer `()`. This will come handy in next case 3.

So `B b{};` is also well-formed. 

**Case 3**

Here we consider the validity of `C c{};` 

This is well-formed because **a)** there is an example in the standard [dcl.init#list-example-4](https://eel.is/c++draft/dcl.init#list-example-4) that says the same and **b)** as per my understanding we reach [default initialization](https://eel.is/c++draft/dcl.init#general-7) here just like we did in case 2 above and this time both `C::C()` and `C::C(initializer_list<int>)` are candidated using [over.match.ctor] but this time even though the initializer `()` can be used with initializer list ctor, **we still prefer a normal default ctor `C::C()` over the initializer list ctor `C::C(initializer_list<int>)` in default initialization**. 

So this `C c{};` is also well-formed. 

**Case 4**

Here we consider the validity of `D d{};`. 

Now we come to the issue that I wanted to highlight since all compilers seem to be incorrect for this case. In particular, as per my understanding here again we reach to [default initialization](https://eel.is/c++draft/dcl.init#general-7) and here also we should prefer the normal default ctor `D::D()` over the initializer list ctor `D::D(initializer_list<int>)` even though the initializer list ctor is also a default ctor and even though initializer `()` is valid for both the ctors just like in case 3,  `()` was valid for both ctors . I think this(`D::D()`) should be preferred because **here also we're doing default initialization** just like in case 3 where also `C::C()` was preferred over `C::C(initializer_list<int>)` for the initializer `()` in default initialization. 

So afaik, `D d{};` is also well-formed but gcc and msvc reject it while clang uses the initializer list ctor for some reason.

<h4>Suggested Resolution</h4>

It should be clarified if `D d{};` is indeed intended to be well-formed  and whether `D::D()` should be preferred over `D::D(initializer_list<int>)`  just like we do for `C c{};`. Doing so will also make the behavior more consistent?

**Comment by ranaanoop** [comment]
Turns out there is a slight difference between case 3 and case 4 which makes case 3 well-formed and case 4 ill-formed. In particular, in case 3 the initializer list ctor is not viable for the initializer `()` so the only viable option is `C::C()` which is used but in case 4 both `C::()` and `C::C(initializer_list<int> = {3})` are viable for initializer `()` because this time the latter has a default argument for its parameter. And so in case 4, since neither is better match than other, case 4 is ill-formed.

So we reach to the same conclusion(that this is ill-formed) as in the [old closed issue](https://github.com/cplusplus/CWG/issues/591) which brings me back to the proposal in that old issue which is that 

> does it make sense to prefer the initializer list ctor over the `C::C()` in case 4 just like in other contexts[over.match.list] initializer list are preferrable. IMO preferring the initializer list ctor `C::C(initializer_list<int> = {3})` over `C::C()` does make some sense atleast.

**Comment by jensmaurer** [comment]
We've massaged the rules around when default constructors are to be preferred over initializer-list constructors a few times in the past. I think the wording is clear as written (you get an ambiguity); if you want a different outcome, please write a paper for EWG.

**Comment by ranaanoop** [comment]
@jensmaurer  Yeah, the current wording does make Case 4 ill-formed due to ambiguity. I agree this is better suited for EWG.
