### ISSUE TITLE
[class.conv.fct] Revisiting `operator auto` template

### ISSUE THREAD

**Issue by MitalAshok** [cplusplus/CWG#594]
Full name of submitter: Mital Ashok

Reference (section label): [class.conv.fct]

Issue description: CWG1878 disallowed `operator auto` conversion templates citing that they have "very limited utility". However, with C++23 explicit object parameters, there is a parameter that can be deduced:

```c++
struct X {
  int i;
  template<typename T>
  operator auto&&(this T&& self) { return (std::forward<T>(self).i); }
};
```

Suggested resolution:

[class.conv.fct]p8:

A<ins>n implicit object</ins> conversion function template shall not have a deduced return type ([dcl.spec.auto]).

*or*

<del>A conversion function template shall not have a deduced return type ([dcl.spec.auto]).</del>

Depending on if vendors can fix the difficulties they were having before CWG1878.

**Comment by jensmaurer** [comment]
Requiring instantiation of a function body to form a conversion sequence seems at least ambitious.

The standard wording, however, is clear as written, so I'm not taking this request as a core issue.

Please submit a paper to WG21/EWG suggesting an extension. This is also a good spot to review implementability with implementers. https://isocpp.org/std/submit-a-proposal
