### ISSUE TITLE
[dcl.init#list] Make int&& ref{1.1}; ill-formed as current wording seems to make it well-formed

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#598]
Full name of submitter: Anoop Rana

Reference (section label): [dcl.init#list]

Issue description:
It seems that the current wording allows `int&& ref{1.1};`. Consider the following contrived example:

```
struct S {
    operator double();
};
// int&& ref{1};         //well-formed as per current wording. Allowed by all compilers
// int&& ref2{1.1};   //well-formed as per current wording. Rejected by all compilers
int&& r{S()};          //well-formed as per current wording. GCC:Ok, EDG:OK, clang:Nope, msvc:Nope 
```
The current wording seems to make all of these well-formed as explained case by case below.

**Case 1**

Here we consider `int&& ref{1};` and see why this is well-formed. 

First we see that it is direct initialization which brings us to [dcl.init#general-16.1](https://eel.is/c++draft/dcl.init#general-16.1):

> If the initializer is a (non-parenthesized) [braced-init-list](https://eel.is/c++draft/dcl.init#nt:braced-init-list) or is = [braced-init-list](https://eel.is/c++draft/dcl.init#nt:braced-init-list), the object or reference is list-initialized ([[dcl.init.list]](https://eel.is/c++draft/dcl.init#list))[.](https://eel.is/c++draft/dcl.init#general-16.1.sentence-1)

Basically this is also list initialization. Now, we reach [dcl.init#list-3.9](https://eel.is/c++draft/dcl.init#list-3.9) which is applicable here because the **referenced type** `int` is reference related to `E=int`:

> Otherwise, if the initializer list is not a [designated-initializer-list](https://eel.is/c++draft/dcl.init#nt:designated-initializer-list) and has a single element of type E and either T is not a reference type or its **referenced type is reference-related to E**, the object or reference is initialized from that element (by copy-initialization for copy-list-initialization, or by direct-initialization for direct-list-initialization); **if a narrowing conversion (see below) is required to convert the element to T, the program is ill-formed**[.](https://eel.is/c++draft/dcl.init#list-3.9.sentence-1) 

As there is no narrowing conversion here, this is **well-formed**. So this case is well-formed. 

**Case 2**

Here we consider `int&& ref2{1.1};` and see why this is well-formed.

Here again this is direct initialization and list initialization(aka direct-list initialization), but this time [dcl.init#3.9](https://eel.is/c++draft/dcl.init#list-3.9) is **not applicable** because the **referenced type** `int` is not reference related to `E=double`. Thus [dcl.init#3.9] is not applicable.

And we reach [dcl.init#3.10](https://eel.is/c++draft/dcl.init#list-3.10):

> Otherwise, **if T is a reference type, a prvalue is generated**[.](https://eel.is/c++draft/dcl.init#list-3.10.sentence-1) The prvalue initializes its result object by copy-list-initialization from the initializer list[.](https://eel.is/c++draft/dcl.init#list-3.10.sentence-2) The **prvalue is then used to direct-initialize the reference**[.](https://eel.is/c++draft/dcl.init#list-3.10.sentence-3) **The type of the prvalue is the type referenced by T**, unless T is “reference to array of unknown bound of U”, in which case the type of the prvalue is the type of x in the declaration U x[] H, where H is the initializer list[.](https://eel.is/c++draft/dcl.init#list-3.10.sentence-4)

Note the emphasis one "the type of the prvalue is the type referenced by `T`" which means here in case 2, the type of the prvalue is `int`. **This prvalue `int` is then used to direct-initialize the reference** which means we're essentially direct initializing an `int&&` from an `int` not a `double`. So this case is also **well-formed**. 

**Case 3**

This case `int&& r{S()};` also seems to be well-formed for the same reason as case 2. 

So as we can see case 2 `int&& ref2{1.1};` is well-formed as per current wording but is rejected by all major compilers. This should probably be ill-formed afaik.

**Comment by jensmaurer** [comment]
I disagree with your analysis of case 2.

It seems the words say that we should rewrite
```
int&& ref{1.1};
```
as
```
int&& ref( int{1.1} );
```
because
"The prvalue initializes its result object by copy-list-initialization from the initializer list."

And that gets us the narrowing check one level down, I think.

It seems case 3 follows the same reasoning and thus should also be ill-formed.

**Comment by t3nsor** [comment]
Yes, it seems that I made a mistake when I came up with the example on the other thread, because when you have list-initialization of a reference, you start from [dcl.init.list] instead of [dcl.init.ref], and you get to the wording that tells you to use copy-list-initialization. I must have been stupidly applying [dcl.init.ref].

**Comment by ranaanoop** [comment]
@jensmaurer  Copy-list-initialization would mean `int&& ref = int{1.1};` instead of `int&& ref( int{1.1} );` afaik as the latter is direct-list-initialization. 

Next, as per copy-list-initialization we will reach [dcl.init#general-16.1](https://eel.is/c++draft/dcl.init#general-16.1) that says:

> If the initializer is a (non-parenthesized) [braced-init-list](https://eel.is/c++draft/dcl.init#nt:braced-init-list) or is = [braced-init-list](https://eel.is/c++draft/dcl.init#nt:braced-init-list), the object or reference is list-initialized ([[dcl.init.list]](https://eel.is/c++draft/dcl.init#list))[.](https://eel.is/c++draft/dcl.init#general-16.1.sentence-1)

which is applicable because here we'll have `=braced-init-list`. This means will again reach [dcl.init.list](https://eel.is/c++draft/dcl.init#list). So this  seems circular and will lead us to where we begin.

----

I think what [dcl.init#list-3.10-sentence-2](https://eel.is/c++draft/dcl.init#list-3.10.sentence-2) actually wanted to do was similar to:

```
int resultObject = {1.1};  //note this is for showing/explaining purposes only in reality resultObect is supposed to be a prvalue.
```
The above `int resultObject = {1.1};` would now be **ill-formed** because of narrowing conversion in [dcl.init#list-3.9](https://eel.is/c++draft/dcl.init#list-3.9) because narrowing conversion is not allowed for **non-reference type**. 

Thus, since `int resultObject = {1.1};` is ill-formed, we can't proceed further and `int&& ref{1.1};` is also supposed to be ill-formed. 

This is what I think happens if I understand the "result object is copy-initialized from prvalue" correctly. Let me know if I missed something.

**Comment by jensmaurer** [comment]
Yes, my rewrite was glossing over the direct-list-initialization vs. copy-list-initialization situation.

In any case, I'm not seeing a core issue here; if you believe some clarification is warranted (now that we've all read the existing wording), please make a specific suggestion.

**Comment by ranaanoop** [comment]
@jensmaurer  I think I do see a core issue. In particular, [dcl.init#list-3.10-sentence-2](https://eel.is/c++draft/dcl.init#list-3.10.sentence-2) says that "the type of the prvalue is the referenced type" which means the initialization of the result object is actually like:
```
int resultObject = {/*someintprvalue*/}; //this can never be a narrowing conversion because the prvalue has same type as resultObject
``` 
Basically, the "generated" prvalue has type same as referenced type(which is `int` here) so we don't reach [dcl.init#list-3.9](https://eel.is/c++draft/dcl.init#list-3.9). So in my previous comment `int resultObject = {1.1};` was not correct. It should've been `int resultObject = {someintprvalue};` which is **well-formed.** 

This means that `int&& ref{1.1};` is also well-formed.

Basically [dcl.init#list-3.10-sentence-2](https://eel.is/c++draft/dcl.init#list-3.10.sentence-2) is not clear in many ways.

**Comment by jensmaurer** [comment]
No, that's not what it says.

> Otherwise, if T is a reference type, a prvalue is generated. The prvalue initializes its result object by copy-list-initialization from the initializer list. The prvalue is then used to direct-initialize the reference. The type of the prvalue is the type referenced by T...

Let's take `int&& ref{1.2};` as the example.

We generate a prvalue of type "int", and that prvalue copy-list-initializes its result object from the initializer list.  So, we have something like `[] -> int { return {1.2}; }()`.

Then, we use that `int` prvalue to direct-initialize the reference:

`int&& ref(prvalue)`.

And that does exactly what we want: We get a narrowing conversion for the copy-list-initialization of the result object of the prvalue.

**Comment by ranaanoop** [comment]
@jensmaurer  You said:

> We generate a prvalue of type "int", and that prvalue copy-list-initializes its result object from the initializer list.

So why exactly are we getting a narrowing conversion when when both types are int? This is exactly what I am saying. The prvalue is of type int and is used to copy-list-initialize the result object which is well-formed as no narrowing conversion from `int` to `int`. Also note that you wrote `int&& ref(intprvalue);` which is also [well-formed](https://godbolt.org/z/b79E5axYM).

**Comment by jensmaurer** [comment]
We get a narrowing conversion because the copy-list-initialization of the result object of the int prvalue is narrowing, because it is `{1.2}`.  I showed the equivalent code using a lambda.  The entire equivalent expression is
```
int&& ref( [] -> int { return {1.2}; }() )
```

**Comment by ranaanoop** [comment]
@jensmaurer  [dcl.init#3.10](https://eel.is/c++draft/dcl.init#list-3.10) doesn't say the `1.1` prvalue is used to copy-list-initialize the result object. It says the prvalue which is of type `int` is used to copy-list-initialize the result. It is unclear in that it does not specify that the element of the original initializer list is used to copy-list-initialize the result object.

**Comment by jensmaurer** [comment]
> It says the prvalue which is of type int is used to copy-list-initialize the result. 

No, it doesn't say that. It says:

> The prvalue initializes its result object by copy-list-initialization from the initializer list.

And "the initializer list" is `{1.2}` in our example; that's the only initializer list we have here.

**Comment by ranaanoop** [comment]
If `{1.1}` is the initializer list where `1.1` is the prvalue involved then why does the clause says that "The type of the prvalue is the type referenced by T" ? The referenced type is `int` here. Also shouldn't the result object be used to direct initialize the reference.

**Comment by ranaanoop** [comment]
@jensmaurer  Basically, I am suggesting to change it to somethig  similar to as follows:

> Otherwise, if T is a reference type, **a prvalue result is generated from the initializer list using copy-list-initialization[.](https://eel.is/c++draft/dcl.init#list-3.10.sentence-1). This prvalue result is then used to direct-initialize the reference**[.](https://eel.is/c++draft/dcl.init#list-3.10.sentence-3) The type of the prvalue is the type referenced by T, unless T is “reference to array of unknown bound of U”, in which case the type of the prvalue is the type of x in the declaration U x[] H, where H is the initializer list[.](https://eel.is/c++draft/dcl.init#list-3.10.sentence-4).

**Comment by jensmaurer** [comment]
`1.1` is NOT the prvalue this section is talking about.  It's a new, invented prvalue that is `int{1.1}`, except using copy-list-initialization, not direct-list-initialization.

I don't like "prvalue results generated" from something. We know that prvalues carry instructions how to initialize their (eventual) target object, so what's wrong the current formulation?

**Comment by ranaanoop** [comment]
> what's wrong the current formulation?

It should say that the "result object" is used to direct initialize the reference. 

Also the current statement in the clause saying *"The prvalue initializes its result object..."* seems to imply that there are two distinct constructs/entities. First is the prvalue itself that is generated/invented which you described as `int{1.1}`. Second is the result object which seems to be copy-list-initialized from the prvalue `int{1.1}` which will be ill-formed. 

So perhaps the following would be more clear:

> Otherwise, if T is a reference type, a prvalue is generated[.](https://eel.is/c++draft/dcl.init#list-3.10.sentence-1) The prvalue initializes its result object by copy-list-initialization from the initializer list[.](https://eel.is/c++draft/dcl.init#list-3.10.sentence-2) **This result object** is then used to direct-initialize the reference[.](https://eel.is/c++draft/dcl.init#list-3.10.sentence-3) The type of the prvalue is the type referenced by T, unless T is “reference to array of unknown bound of U”, in which case the type of the prvalue is the type of x in the declaration U x[] H, where H is the initializer list[.](https://eel.is/c++draft/dcl.init#list-3.10.sentence-4).

Note I've changed "the prvalue" to "this result object".

**Comment by ranaanoop** [comment]
@jensmaurer I see. Now, since we're at it, there might be an additional problem(not in this post's example but in some other cases) of not specifying which form of direct initialization is used here. In particular, currently the clause says "prvalue is then used to direct initialize". It should be clarified if we're talking about "direct-non-list-initialization" etc. For example, you wrote `int&& ref(intprvalue)` so it should be the `()` form. This will effect which bullet point is applicable from [dcl.init#general-16](https://eel.is/c++draft/dcl.init#general-16) and may lead to problems like discussed in [old issue](https://github.com/cplusplus/CWG/issues/596).

**Comment by jensmaurer** [comment]
We should just say what @t3nsor suggested in the other issue: To direct-initialize something means to use an `(E)` initializer.

**Comment by ranaanoop** [comment]
@t3nsor Don't we already have a term for exactly this. I mean currently  there are more than 100 occurrences of the term _"direct-non-list-initialization"_ in the c++ draft for similar/same situations. So why should we add something  new instead of just using the already available specific term that describes the issue. Changing _direct initialization_ to _direct-non-list-initialization_ could even be done editorially.

**Comment by jensmaurer** [comment]
Those occurrences are exclusively in the library section. The term is a bit clumsy, but I appreciate we might need it because "direct/copy-initialization" and "non-list / list-initialization" are orthogonal concepts.

**Comment by jensmaurer** [comment]
The main thrust of this issue seems not a defect; what remains is the perceived missing clarity around "direct-initialization" meaning "direct-non-list-initialization".  If, after all this discussion, this is still a concern, please create a new issue focusing on exactly that concern.
