### ISSUE TITLE
CWG2522 [cpp.concat] Removing placemarker tokens and retention of whitespace

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/CWG#6]
Full name of submitter (unless configured in github; will be published with the issue): Hubert Tong

Reference (section label):15.6.4 [cpp.conat]

Link to reflector thread (if any): http://lists.isocpp.org/core/2018/04/4189.php

Issue description:
It appears that the replacement of a function-like macro following further rescanning and replacement may begin or end with whitespace when the leftmost or rightmost tokens were placemarker tokens.

GCC and MSVC preserve the whitespace in both the starting and ending positions.
Clang and ICC preserve only the trailing whitespace.

```
#define F( X )  X##X/**/>
#define G( X )  !/**/X##X
#define F0( X )  F(X)
#define G0( X )  G(X)
#define STR2( X )  #X
#define STR( X )  STR2(X)
#define Q
static_assert(STR(>F0(Q))[1] == '\u0020', STR(>F0(Q)));
    // ^ Works with GCC and MSVC; fails with Clang and ICC.
static_assert(STR(G0(Q)=)[1] == '\u0020', STR(G0(Q)=));
```

Suggested resolution:

**Comment by jensmaurer** [comment]
CWG2536

**Comment by hubert-reinterpretcast** [comment]
Maybe we want to add the observation about ISO C from the other draft:

> This appears to be an issue in C as well; see ISO C 6.10.3.

**Comment by jensmaurer** [comment]
Done.
