### ISSUE TITLE
[expr.await] p5 Return false from `await_suspend()`

### ISSUE THREAD

**Issue by ddvamp** [cplusplus/CWG#601]
Full name of submitter: Artyom Kolpakov

Reference (section label): [[expr.await]p5](https://eel.is/c++draft/expr.await#5)

Link to reflector thread (if any): [std-discussion](https://lists.isocpp.org/std-discussion/2024/07/2576.php), [clang-issues](https://github.com/llvm/llvm-project/issues/98740)

Issue description: gcc and clang use optimization in the implementation of `bool await_suspend()` so that when `false` is returned, the coroutine is resumed as if it had not been suspended (like a normal return from a function rather than a handle mechanism). As a consequence, if inside the call `await_suspend()` the coroutine was resumed via the passed handle, then when returning `false` we get UB, because the coroutine is resumed not from actual `suspend point`, but from cached. The clang developers believe that this behavior is justified, so they propose to define this case as UB.
Simple snippet:
```
bool await_suspend(auto h) {
  h.resume();
  return false;
}
```

Suggested resolution: Add new paragraph: If the result of await_suspend is false, and the coroutine was resumed by invoking a resumption member function of h before the await_suspend evaluation was completed, the behavior is undefined.

**Comment by jensmaurer** [comment]
The wording in the standard seems clear with respect to what happens for the example, so I'm not seeing a core issue here.  Also, WG21 has become more sensitive regarding introducing undefined behavior. Or can you make an argument that the behavior is already undefined in the status quo of the wording, but maybe it's not obvious?

If not, please submit a paper to WG21 to make a change.

**Comment by ddvamp** [comment]
> The wording in the standard seems clear with respect to what happens for the example, so I'm not seeing a core issue here. Also, WG21 has become more sensitive regarding introducing undefined behavior recently. Or can you make an argument that the behavior is already undefined in the status quo of the wording, but maybe it's not obvious?
> 
> If not, please submit a paper to WG21 to make a change.

I am sorry, English is not my native language, I didn't fully understand, I will describe in more detail.

Here is an example: https://godbolt.org/z/1jMMnn9aW
Strictly by standard in this example everything is fine, but in the current implementation of gcc and clang here is Bug or UB. I wrote bug reports, and clang replied me that they know about it, but they think that the `bool await_suspend()` version is the way it should be used. They don't want to remove the optimization and make the compiler conform to the standard description, advising me to write DR. So I ended up coming here.
There are two options: either fix the compilers, forcing them to follow the standard, or change the standard wording. If I have to keep saying that the standard should be changed, what does “submit a paper to WG21 to make a change” mean?

**Comment by jensmaurer** [comment]
>  fix the compilers, forcing them to follow the standard, or change the standard wording.

Right, that's the default approach when a bug in a compiler is discovered.

> submit a paper to WG21 to make a change

See here for instructions: https://isocpp.org/std/submit-a-proposal

**Comment by ddvamp** [comment]
> See here for instructions: https://isocpp.org/std/submit-a-proposal

Am I correct in understanding that by opening the issue I proposed DR? Just in my C++ community I was given a link here for that. Then I don't understand what closed issue means. That the proposed DR was rejected or what? So I should go back to clang and say, fix the compiler, it's a bug? Or according to the instructions on the link I will propose a DR? Just from the description it seemed to me that the link contains instructions for proposing new functionality, not DR. I just haven't figured out what I should do next.
Again, sorry for this.

**Comment by jensmaurer** [comment]
The particular link I gave does not discuss DRs.

Yes, this issue tracker is for submitting defects for the core language part of the C++ standard. Defects, in particular, are unclear wording, internal contradictions of the wording, or deviations from intent.

Your concern does not seem to fall into any of those categories (and you have not presented any argument relating to intent; possibly by referring to the original paper that brought us the feature); instead, you have shown two compiler bugs.

I am telling you that, absent further evidence to the contrary, your desire is a desire to change the intent of the C++ standard, which requires a proposal, not a mere defect submission. And yes, the new functionality you want is to introduce undefined behavior in a situation where the existing wording clearly specifies the behavior, as far as I can see. Your proposal might have good rationale along the lines of "nobody should write this code; and not allowing such code allows for better optimizations", but such concerns are generally beyond the scope for a defect submission.

**Comment by ddvamp** [comment]
I apologize very much. Not having figured out who the actual developer of clang is, I took third persons opinions as the organization's opinion and used that to create the further discussion. As it was pointed out to me, the only message from a clang member was that it was most likely a bug in the compiler. I will wait for further messages from the actual clang developers. Once again, I'm very sorry.

**Comment by iains** [comment]
for the record, the (compiler) bug is tracked for GCC as https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115905 which we intend to resolve.
