### ISSUE TITLE
[dcl.pre] Grammar disallows static int iarr2 alignas(16) ; but all compilers accept it

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#602]
Full name of submitter: Anoop Rana 

Reference (section label): [dcl.pre]

Link to reflector thread (if any): https://stackoverflow.com/questions/42692058/why-doesnt-alignas-compile-when-used-in-a-static-declaration-with-clang

Issue description:

Current grammar seems to make `static int iarr2 alignas(16) ;` invalid but all 3 major compilers accept it. Similarly, `static int alignas(16) one_s  = 1;` is grammatically allowed but only msvc accepts it. [Demo](https://godbolt.org/z/df95YbKW1)

```
//  static int alignas(16) one_s  = 1; //#1: MSVC: Ok, Clang: No, EDG: No, but current grammar allows this 
static int iarr2 alignas(16) ;              //#2: all 4 compilers accepts this but NOT ALLOWED as per current grammar
```

Clarify if the `#2` is intended to be ill-formed. 

Here is the [gcc bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116532) reported for the same.

**Comment by jensmaurer** [comment]
Why do you believe that

`static int iarr2 alignas(16) ; `

is not allowed by the grammar?  The _noptr-declarator_ production has an optional _attribute-specifier-seq_ following the _declarator-id_.

I agree that `static int alignas(16) one_s  = 1` is allowed by the grammar, and `alignas(16)` appertains to the `int` _decl-specifier_, but [dcl.align] p1 does not allow that position: "An alignment-specifier may be applied to a variable or to a class data member..."  `int` is neither a variable not a class data member. And the later class case obviously doesn't apply either.

**Comment by ranaanoop** [comment]
@jensmaurer  I must have missed that. 

Now shouldn't [dcl.align]p1 also make `alignas(16) static int one_s = 1;` invalid. This is like `const` instead of `alignas(16)` sometimes called east const vs west const and I would think this is valid for the same reason. But should `[dcl.align]` cross reference something to make this clear.  Note that this(`alignas(16) static int one_s = 1;`) is grammatically allowed.

**Comment by jensmaurer** [comment]
[dcl.pre] p4: "The attribute-specifier-seq appertains to each of the entities declared by the declarator s of the init-declarator-list."

Soi, the `alignas(16)` appertains to the "one_s", which is a variable, and thus it's fine per [dcl.align]p1.
