### ISSUE TITLE
[expr.const] Trivially copying a partially uninitialized array in a union in constant evaluation

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/CWG#603]
Full name of submitter (unless configured in github; will be published with the issue): Jiang An

Reference (section label): [expr.const], [class.copy.ctor], [class.copy.assign]

Link to reflector thread (if any):

Issue description:

Discovered in llvm/llvm-project#105932.

Consider the following `std::inplace_vector`-like type:

```C++
template<class T, std::size_t N> // assuming that T is trivial
struct inplace_vector_storage {
  union {
    T arr_[N];
  };
  std::size_t sz_;
};
```

It may be desired that given object `x` of type `inplace_vector_storage<T, N>`, when `x.sz_ < N`, the elements of `x.arr_` beyond `x.arr_[sz_ - 1]` is either out of lifetime or have indeterminate/erroneous values.

However, at least since CWG2658 got accepted, (trivially) copying such an `x` in constant evaluation causes copying `x.arr_`, where reading the element beyond `x.arr_[sz_ - 1]` is likely to results in UB/EB which in turn causes constant evaluation failure.

Should we be make trivially copying a union in constant evaluation skip non-living or uninitialized (scalar?) subobjects of the active member?

Suggested resolution:

**Comment by jensmaurer** [comment]
I'm not seeing a defect here; the wording is clear as written.

If you wish to change the rules for constant evaluation, write a paper for WG21.
