### ISSUE TITLE
[intro.races] The load part of a read-modify-write operation is less prone to reading stale value than a pure load

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#608]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

````cpp
std::atomic<int> v = {0};

// thread 1:
std::this_thread::sleep_for(std::chrono::milliseconds(100));
for(auto I = 0;i<99999;i++)
  v.load(std::memory_order::relaxed);  // #1

// thread 2:
v.store(1,std::memory_order::relaxed);  // #2
````

In this example, assuming we have the case that: `#1` **does not happen-before** `#2`, and the modification order of `v` is `{0, 1}` before the first `#1` is executed. Under this modification order, the load at `#1` may always only read `0`(a stale value in the modification order) in the whole loop even though [intro.races] p14 says the side effect produced by `#2` is a candidate, which result does not violate the rules from [intro.races] p14 to p18. 

However, with the same situation, if `#1` were a read-modify-write operation, such as `v.fetch_add(1,std::memory_order::relaxed)`, the read part of the RMW operation can guaranteed to read the value `1` as per [atomics.order] p10: 
> Atomic read-modify-write operations shall always read the last value (in the modification order) written before the write associated with the read-modify-write operation.

because the write part of the RMW operation will change the modification order to be `{0,1, 2}` such that the last value before the associated write is `1`, hence the read part of the RMW operation must read `1`, it cannot read the stale value `0`.

So, comparing the pure load with the load part of a RMW operation, the latter is less prone to reading stale value, is this the intended meaning of the current wording regarding modification order?

**Comment by jensmaurer** [comment]
Since there is no happens-before relationship between #1 and #2, it is very well possible for some or all read-modify-write operations at #1 to execute before the store at #2.

I'm not seeing a defect in the wording.

**Comment by xmh0511** [comment]
> Since there is no happens-before relationship between #1 and #2, it is very well possible for some or all read-modify-write operations at #1 to execute before the store at #2.
> 
> I'm not seeing a defect in the wording.

However, the modification order is assumed to be `{0,1}` before the first `#1` is executed, which means that `#2` has happened.

**Comment by jensmaurer** [comment]
There is no evidence in your code that the modification order would actually be like that.  But yes, if (big if) your assumption holds, then you're right.  Still no defect.

**Comment by xmh0511** [comment]
> There is no evidence in your code that the modification order would actually be like that.

Ok, The code is a bit misleading here. What I want to say is that: given an abstract modification order `{M0, M1, ..., Mn}`, such that the load operation **does not happen before** the store operation associated with every side effect in this order(i.e. obey [intro.races] p14 to imply every side effect is a candidate result of the load operation and assuming evey result does not violate other rules(i.e. from [intro.races] p15 to [intro.races] p18)), **under this big precondition**, a pure load, in a limited period, may always only read stale value(M0 ~ Mn-1), which is permitted by the current wording in the standard. Instead, an RMW operation, since its write part becomes `Mn+1` in the modification, its reading value must be `Mn` according to [atomics.order] p10, hence, a derived conclusion from the current wording is the read part of an RMW operation is less prone to reading stale value than a pure load operation. 

@jensmaurer  This seems the implied intention of the current wording, thanks for your confirmation.
