### ISSUE TITLE
[over.over]  Is CWG2369 supposed to change the order of subsitution or elimination

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#611]
Full name of submitter: Anoop Rana

Reference (section label): [over.over]

Link to reflector thread (if any): https://stackoverflow.com/questions/79016821/static-assertion-fires-from-return-type-when-leading-constraint-is-not-satisfied

Issue description:

Consider the following example for which we observe [implementation divergence](https://godbolt.org/z/PKMKzYGsc).

```
template<typename T>
constexpr int assert() {
    static_assert(sizeof(T) == 1);
    return 1;
}

template<auto I>
using Int = int;

template<typename T> requires (sizeof(T) == 1)
constexpr auto foo(T) -> Int<assert<T>()> {
    return 1;
}

template<typename T> requires (sizeof(T) > 1)
constexpr auto foo(T a) -> Int<1> {
    return 2;
}

static_assert(foo(2) == 2);
```

[over.over#5] seems/intented to make this well-formed but as pointed out in the [thread](https://stackoverflow.com/questions/79016821/static-assertion-fires-from-return-type-when-leading-constraint-is-not-satisfied#comment139323948_79016883), [over.over#3] seems to make this  ill-formed. 

Suggested resolution:

Clarify the order.

**Comment by frederick-vs-ja** [comment]
IIRC among these 3 major compilers, only GCC has implemented CWG2369. So I think it's too early to talk about implementation divergence at this moment.

**Comment by jensmaurer** [comment]
[over.over] is about address of overload sets.  There is no such situation in your example.

I'm therefore closing this submission.  If you wish to re-try, please take a moment and walk us through the wording (as amended by CWG2369), and why you believe there is still an open issue.  (As highlighted above, implementation divergence is probably not a good argument.)
