### ISSUE TITLE
[temp.deduct.partial] Make overloading function templates when explicitly passing reference argument well-formed

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#616]
Full name of submitter: Anoop Rana

Reference (section label): [temp.deduct.partial]

Link to reflector thread (if any): https://stackoverflow.com/questions/79034394/function-template-overloading-when-called-with-reference-type-rejected-by-clang

Issue description: 

Consider the following program for which we observe [implementation divergence](https://godbolt.org/z/4K7ErvWjh). Clang rejects this but gcc and msvc accepts. 

```
#include <utility>
#include <iostream>
template< class T > void f( T& t ){} ;
template< class T > void f( const T&& ) {};
int main()
{
    int i = 0;
    f<int&>(i); //clang:nope, gcc:ok, msvc:ok
} 
```

This seems to be ill-formed to me due to [temp.deduct.partial#9](https://timsong-cpp.github.io/cppwp/n4950/temp.deduct.partial#9) because [temp.deduct.partial#9.1](https://timsong-cpp.github.io/cppwp/n4950/temp.deduct.partial#9.1) 
seems to make the second overload not to be at least as specialized as the first and then [temp.deduct.partial#9.2](https://timsong-cpp.github.io/cppwp/n4950/temp.deduct.partial#9.2) seems to do the same for the first template. So neither overloads are more specialized as other as per current wording.

I may be missing something here.

**Comment by t3nsor** [comment]
Can you explain why you think this is a defect?

**Comment by t3nsor** [comment]
You should expect the behaviour to change when you explicitly specify a template argument that is different from what would be deduced. So, I don't see any rationale for calling this a defect.
