### ISSUE TITLE
CWG2598 [basic.types.general] unions should not require a non-static data member of literal type

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/CWG#62]
Full name of submitter (unless configured in github; will be published with the issue): 

Reference (section label): [basic.types.general]

Link to reflector thread (if any):

Issue description:

Per [basic.types.general]/10, a type is a literal type only if it satisfies the following:

> * if it is a union, at least one of its non-static data members is of non-volatile literal type, and (10.5.4)
> * if it is not a union, all of its non-static data members and base classes are of non-volatile literal types.
>
> [Note 4: A literal type is one for which it might be possible to create an object within a constant expression. ...]

But the rule disagrees with the note. Consider:

```
struct A { A(); };
union U {
    A a;
    constexpr U() {}
    constexpr ~U() {}
};
```

It certainly would be possible to create and destroy an instance of `U` in a constant expression; the only barrier is that `U` is not a literal type because it doesn't have any non-static data members of literal type. Indeed, we already require that:

> * it has a constexpr destructor ([dcl.constexpr]),
> * it is either a closure type ([expr.prim.lambda.closure]), an aggregate type ([dcl.init.aggr]), or has at least one constexpr constructor or constructor template (possibly inherited ([namespace.udecl]) from a base class) that is not a copy or move constructor,

... which between them cover nearly all of the "bad" cases.

Suggested resolution:

Change in [basic.types.general]/10:

> A type is a *literal type* if it is [...] a possibly cv-qualified class type that has all of the following properties:
> * it has a constexpr destructor ([dcl.constexpr]),
> * it <del>is</del> either
>     * <ins>is</ins> a closure type ([expr.prim.lambda.closure]),
>     * <ins>is</ins> an aggregate type ([dcl.init.aggr]) <ins>for which that type (if it is a union) or each of its anonymous union members (otherwise) either has at least one variant member of non-volatile literal type or has no variant members</ins>, or
>     * has at least one constexpr constructor or constructor template (possibly inherited ([namespace.udecl]) from a base class) that is not a copy or move constructor,
> * <del>if it is a union, at least one of its non-static data members is of non-volatile literal type, and (10.5.4)</del>
> * <del>if it is not a union,</del> all of its non-static <ins>non-variant</ins> data members and base classes are of non-volatile literal types.

The aggregate type rule is intended to capture the fact that it's not possible for aggregate initialization of a non-empty union to leave no active member (and similarly for each anonymous union member in a non-union union-like class). Though maybe we could drop that requirement, especially since the notion of "literal type" generally seems to be on the way out.

**Comment by jensmaurer** [comment]
CWG2598
