### ISSUE TITLE
CWG2944 [expr.throw] Throw expressions should be indivisible

### ISSUE THREAD

**Issue by Eisenwave** [cplusplus/CWG#626]
Reference (section label): [[expr.throw]](https://eel.is/c++draft/expr.throw)

## Issue description

It is unclear what happens when two *throw-expression*s are unsequenced, such as in:
```cpp
(throw /* ... */, 0) + (throw /* ... */, 0);
```
As per [[except.throw] paragraph 1](https://eel.is/c++draft/except.throw#1), this results in two unsequenced transfers of control to the caller, contrary to `co_await` expressions, which are indivisible and non-interleavable following CWG2466 ([[intro.execution] paragraph 11](https://eel.is/c++draft/intro.execution#11)).

## Suggested resolution

Update [[intro.execution] paragraph 11](https://eel.is/c++draft/intro.execution#11) as follows:
> For each function invocation<ins>, evaluation of a *throw-expression*,</ins> or evaluation of an *await-expression* **F**, each evaluation that does not occur within **F** but is evaluated on the same thread and as part of the same signal handler (if any) is either sequenced before all evaluations that occur within **F** or sequenced after all evaluations that occur within **F**;

Analogous to [[expr.await] Note 2](https://eel.is/c++draft/expr.await#note-2), append a note to [[expr.throw] paragraph 2](https://eel.is/c++draft/expr.throw#2) as follows:

> [...] from the (possibly converted) operand.
>
> <ins>[*Note:* With respect to sequencing, a *throw-expression* is indivisible ([intro.execution]). — *end note*]</ins>

**Comment by frederick-vs-ja** [comment]
Consider `(throw a() + b(), 0) + (throw c() + d(), 0)`, IIUC currently `a()`, `b()`, `c()`, and `d()` can be executed in arbitrary order. I'm not sure whether such reordering is desired, but if so, we may need to say that the transfer of control but not the whole throw-expression is indivisible.

I wonder whether the current wording even allows partial side effect on a memory location during throwing. Perhaps this also needs to be disallowed if it's not so.

**Comment by Eisenwave** [comment]
> I'm not sure whether such reordering is desired, but if so, we may need to say that the transfer of control but not the whole throw-expression is indivisible.

I have considered this, and similar to `co_await` being indivisible, I do think that *all of* `throw a()` should be indivisible. For virtually all use cases, it would be pointless to interleave another evaluation between the construction of the exception object and throwing it.

Once the program constructs an exception, it is already on a path towards throwing it, and little or nothing can be gained from doing something else first (nor does it seem like the user would ever except that to happen).

**Comment by jensmaurer** [comment]
CWG2944
