### ISSUE TITLE
CWG2600 [temp.dep.expr] Type dependency of `new auto(T())`

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [cplusplus/CWG#63]
Full name of submitter (unless configured in github; will be published with the issue): Hubert Tong

Reference (section label): [temp.dep.type], [temp.dep.expr]

Link to reflector thread (if any): N/A

Issue description:
N4910 subclause 13.8.3.2 [temp.dep.type] paragraph 7 has a list of types considered to be dependent. This list covers placeholder types only insofar as it has an entry about `decltype(expression)`. Subclause 13.8.3.3 [temp.dep.expr] paragraph 3 has a list of expression forms not considered dependent unless if specific types named by the expressions are dependent. This list includes forms where placeholder types are allowed.

For example, the wording does not appear to say that the _new-expression_ below is dependent (however, implementations treat it as such):
```cpp
template <typename T> struct A { A(bool, T); };

void g(...);

template <typename T>
auto f(T t) { return g(new A(t, 0)); }

int g(A<int> *);
int h() { return f<void *>(nullptr); }
```

Suggested resolution:
Add a definition of type dependency of the various initializer forms. Change [temp.dep.expr] to depend on the type dependency of the various initializer forms when a placeholder type is used. Even if some dependent types involved are not significant to the determination of the type represented by the placeholder (see the above example), the placeholder is considered to be a dependent type.

**Comment by hubert-reinterpretcast** [comment]
Apparently, there is implementation divergence for more simple cases:
```cpp
template <typename T, typename U> struct A { A(T, U); };

void g(...); // #1

template <typename T>
auto f() { return g(new A(0, 0)); } // Clang resolves this to #1; GCC to #2

int g(A<int, int> *); // #2
void h() { return f<void *>(); }
```

That is probably worth noting in the issue description.

Regarding the proposed wording:

I think the "it is the return type of a templated function" case is covered by other wording already (particularly [[temp.dep.expr] paragraph 3, bullet 3.4](https://eel.is/c++draft/temp.dep.expr#3.4)).

I think the "any default _template-argument_ of the primary class template named by the placeholder is dependent" case may be overly broad.

The default _template-argument_ is not used:
```cpp
template <typename T, typename U = T> struct A { A(T, U); };

void g(...);

template <typename T>
auto f() { return g(new A(0, 0)); }

int g(A<int> *);
void h() { return f<void *>(); }
```

The default _template-argument_ is dependent in the context of its primary template but is not substituted with a type that is dependent in the context of `f()`'s definition:
```cpp
template <typename T, typename U = T> struct A { A(T); };

void g(...);

template <typename T>
auto f() { return g(new A(0)); }

int g(A<int> *);
void h() { return f<void *>(); }
```

**Comment by hubert-reinterpretcast** [comment]
> gcc is the only outlier when handling your first example; #1 is obviously the right choice. [CWG2600](https://cplusplus.github.io/CWG/issues/2600.html) is updated with the example and the "auto return type" case removed.

Thanks and I agree that we probably want to go with the proposed direction (unless if the GCC behaviour has some interesting explanation that would make us change it).

> Regarding "any default template-argument of the primary class template named by the placeholder is dependent", I want to cover a case like this:
> 
> ```
> template<class T>
> struct S {
>   template<class U = T> struct A { A(int); };
> 
>   auto f() { return new A(0); }  // dependent return type
> };
> ```
> 
> but that is probably covered by a combination of the other rules talking about members of the current instantiation.
> 
> What would break if I dropped the default template-argument rule?

I am not sure that the rules talking about members of the current instantiation cover this. The [temp.dep.expr]/3 wording is not meant to cover type names, so we would be looking at [temp.dep.type] for this. The placeholder type is not named with a qualified name, so [bullet 7.2](https://eel.is/c++draft/temp.dep.type#7.2) does not apply. [Bullet 7.3](https://eel.is/c++draft/temp.dep.type#7.3) is close but would not cover alias template CTAD.

**Comment by jensmaurer** [comment]
Do you have any idea how to phrase this? Maybe "any used default template-argument of the primary class template named by the placeholder is dependent when considered in the enclosing scope"?

**Comment by xmh0511** [comment]
> A placeholder for a deduced class type (9.2.9.7 [dcl.type.class.deduct]) is dependent if
>> - it has a dependent initializer or
>> - any default template-argument of the primary class template named by the placeholder is dependent.

What if the default `template-argument` is not used? We might say
> any template argument of the primary class template named by the placeholder remains non-deduced or is dependent.  
 

Since if `U` obtains template argument from `T`, according to [temp.dep.type] p7 bullet 7.1, `T` is dependent, the template argument corresponds to `U` is dependent.

**Comment by jensmaurer** [comment]
"is dependent" is a template-parse-type determination, because it defines whether you need `typename` or not. We can't say "after class template deduction", because that's an instantiation-time activity.

**Comment by xmh0511** [comment]
> We can't say "after class template deduction", because that's an instantiation-time activity.

The deduction should be performed to check which template arguments are **used**, and further determine whether `A(0)` is a dependent type or not in the context of the template definition. Otherwise, how do we know whether the template-argument `T` is used or not in the context of the template definition?

**Comment by jensmaurer** [comment]
I agree with the intent, but we currently lack machinery to describe that. We certainly can't perform deduction at that point.

**Comment by xmh0511** [comment]
> but we currently lack machinery to describe that.

I think this part is similar to the deduction that occurred in partial ordering. We synthesized a type, or value for the deduction in partial ordering, which is **not any concrete** type, or value(arguably says the template parameter is so-called the synthesized type or value), and any instantiation won't perform in that context, which meaning is read from the source code of the implementations. We should augment the machinery to describe the deduction in these non-instantiation contexts to make it be clearer.
