### ISSUE TITLE
CWG2954 [intro.races] p4 total order vs. strict total order

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#636]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[intro.races] p4 says:
> All modifications to a particular atomic object M occur in some particular **total order**, called the modification order of M.

According to [Wikipedia](https://en.wikipedia.org/wiki/Total_order), The modification order is more like a **strict total order**. Their difference is:
![图片](https://github.com/user-attachments/assets/5a8aa858-f301-436c-88bc-61a5e1b55799)

Any two modifications in the modification order are distinct elements, so they cannot be `If a ≤ b and b ≤ a  then a = b`. In other words, either one precedes the other or after, they cannot overlap(i.e. equal). Moreover, saying a modification precedes itself(i.e. reflexive) in the order is meaningless. 

### Suggested Resolution: 
> All modifications to a particular atomic object M occur in some particular **strict total order**, called the modification order of M.

[atomics.order] p4
> There is a single **strict total order** S on all memory_order​::​seq_cst operations, including fences, that satisfies the following constraints.

**Comment by frederick-vs-ja** [comment]
This strongly feels editorial to me.

**Comment by jensmaurer** [comment]
CWG2954

**Comment by opensdh** [comment]
If "two modifications in the modification order are distinct elements", they can't have a≤b and b≤a, precisely because in a (non-strict) total order we then have a=b and they aren't _two_ modifications.  a=b there doesn't mean "the two modifications occupy the same place in the order"; it means that they are two labels for the same modification.
