### ISSUE TITLE
LWG4182 [support.types.nullptr] Definition of NULL is too broad

### ISSUE THREAD

**Issue by randomnetcat** [cplusplus/CWG#653]
Full name of submitter: Janet Cobb

Reference (section label): [support.types.nullptr]

Issue description:

[conv.ptr]/1 reads in part: "A <i>null pointer constant</i> is an integer literal ([lex.icon]) with value zero or a prvalue of type <code>std::nullptr_t</code>.".

[support.types.nullptr]/2 reads: "The macro <code>NULL</code> is an implementation-defined null pointer constant.".

Together, these imply that <code>#define NULL (::std::unreachable(), nullptr)</code> is a conforming definition. The expression is a prvalue of type <code>std::nullptr_t</code>, so it is a null pointer constant. This makes it implementation-defined whether any program that evaluates <code>NULL</code> has undefined behavior.

Since this is an issue with a standard library definition (`NULL`), I attempted to submit this as an LWG issue first; the response was to ask if I submitted a core issue, so I am submitting one here.

Suggested resolution:

TBD.

**Comment by t3nsor** [comment]
If LWG bounced you to CWG, doesn't that mean they want a change to the core wording (e.g. the definition of "null pointer constant" in [conv.ptr])?

**Comment by randomnetcat** [comment]
Maybe? I'm not sure exactly what they want. I'll just remove the proposed resolution for now then.

**Comment by frederick-vs-ja** [comment]
IMO the crux is that we're not saying such "prvalue of type `std::nullptr_t`" needs to be itself a prvalue core constant expression.

C23 (WG14 [N3220](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3220.pdf)) 6.3.2.3/3 says

> An integer constant expression with the value 0, such an expression cast to type `void *`, or the predefined constant `nullptr` is called a _null pointer constant_.

, which excludes other `nullptr_t` values.

But I think we do want non-constant `nullptr_t` prvalues to be special in the type system.

**Comment by t3nsor** [comment]
Yes, and we use "null pointer constant" in core several times while library only uses it once, so the least intrusive change is for us to leave the definition the way it is, and ask LWG to change the definition of `NULL` so that instead of it saying that it's a null pointer constant, it says it's always a literal, or something like that. Perhaps if CWG reaches consensus on asking LWG to do so, then they'll reconsider it.

**Comment by t3nsor** [comment]
That said, if we feel that "null pointer constant" is a misleading term for something that's potentially not a constant expression, we could certainly take C's approach, and invent some other term for what we currently call "null pointer constant", such as "null pointer initializer" (maybe someone can come up with a better one).

**Comment by jensmaurer** [comment]
I think using "prvalue of type std::nullptr_t" is correct in the core language; we can discuss separately if designating this a "constant" when it might not be is worthwhile to near-editorially fix by renaming the term.

If LWG believes that `#define NULL (::std::unreachable(), nullptr)` is not a definition for `NULL` suitable for the target audience of the library (and I concur), then we should fix the rules around `#define NULL`, e.g. by saying "The macro `NULL` is an implementation-defined <ins>core constant expression</ins> that is a null pointer constant."

**Comment by jensmaurer** [comment]
I've resubmitted as an LWG issue.

**Comment by Dani-Hub** [comment]
The LWG issue exists now: [LWG 4182](https://cplusplus.github.io/LWG/issue4182)
