### ISSUE TITLE
[expr.reinterpret.cast] It is unclear whether `const void*` can be converted to a function pointer, if `void*` can be

### ISSUE THREAD

**Issue by Eisenwave** [cplusplus/CWG#657]
**Reference (section label):** [[expr.reinterpret.cast]](https://eel.is/c++draft/expr.reinterpret.cast)

## Issue description
```cpp
const void* null = nullptr;
auto n = reinterpret_cast<void(*)(void)>(null);
```
It is unclear whether this code is ill-formed, and major implementations disagree.

GCC accepts,  but Clang rejects because the conversion to `void(*)(void)` "casts away qualifiers". Superficially, a `const` qualifier is removed, but it would have been removed based on the fact that function types cannot be cv-qualified anyway.

Furthermore, all major implementations support a conversion from function pointers to `void*`, but [[expr.reinterpret.cast] paragraph 8](https://eel.is/c++draft/expr.reinterpret.cast#8) only mentions conversions involving pointers to object types, and `void` is not an object type.

[[expr.reinterpret.cast] paragraph 8](https://eel.is/c++draft/expr.reinterpret.cast#8) already mentions "possibly with different cv-qualification" for that conversion, but it is unclear whether
- this implies that support for different cv-qualifications is mandated, or
- if support for different cv-qualifications is provided, such conversions have the specified semantics in the paragraph.

## Suggested resolution

Update [[expr.reinterpret.cast] paragraph 2](https://eel.is/c++draft/expr.reinterpret.cast#2) as follows:
<blockquote>
The <code>reinterpret_cast</code> operator shall not cast away constness ([expr.const.cast])<del>.</del><ins>, unless <code>T</code> is a function pointer type or reference to a function type.</ins>
An expression of integral, enumeration, pointer, or pointer-to-member type can be explicitly converted to its own type; such a cast yields the value of its operand.
</blockquote>

Update [[expr.reinterpret.cast] paragraph 8](https://eel.is/c++draft/expr.reinterpret.cast#8) as follows:

<blockquote>
Converting a function pointer to <del>an object pointer type</del> <ins>a "pointer to <i>cv</i> object type or <code>void</code>"</ins>, or vice versa is conditionally-supported.
The meaning of such a conversion is implementation-defined, except that if an implementation supports conversions in both directions, converting a prvalue of one type to the other type and back, possibly with different cv-qualification, shall yield the original pointer value.
<ins>Let <code>T</code> be an object type or <code>void</code>. If converting a pointer of type "pointer to <code>T</code>" to a function pointer type <code>F</code> is supported, converting a "pointer to <code>const T</code>" to <code>F</code> shall also be supported</ins>.
</blockquote>

**Editor's note:** No wording changes for the other conversion direction are needed because conversions to `const void*` where `void*` is supported are already performed through a subsequent qualification conversion.

**Comment by Eisenwave** [comment]
As a drive-by fix, we might also want to say that if you can convert to some `T*`, you can also convert to `void*`. `void*` can be created from any object pointer type, and this conversion is implicit, meaning that:
```cpp
void* p = reinterpret_cast<int*>(fptr);
```
... works, even if conversion directly to `void*` is unsupported. That also seems somewhat nonsensical to me, and we might want to say that `reinterpret_cast<void*>` must be possible in that case.

**Comment by Eisenwave** [comment]
@lprv I think you're right. I think the proposed resolution should still target [expr.reinterpret.cast] because that's really the only case where such conversions would even come up; anywhere else, you cannot convert `const void*` to a function pointer anyway, regardless of cv-qualifications.

The proposed resolution still makes sense for p8 because it's not really clear whether `void*` to function pointer support implies `const void*` to function pointer support, even though providing just the former is quite nonsensical and leads to implementation divergence, as observed.

**Comment by jensmaurer** [comment]
Can someone please explain to me why the conversion in question would "cast away constness" here? What are the values of n and U1 and U2 that we're looking at in [expr.const.cast] p6?

**Comment by Eisenwave** [comment]
@jensmaurer The way I'm reading it, say we are converting `T1 = const void*` to `void(*)()`.

The qualification-decomposition ([[conv.qual] p1](https://eel.is/c++draft/conv.qual#1)) of `T1` is "(no cv) pointer to `const void`", which yields *n = 1*. U<sub>1</sub> is `void`.

The qualification-decomposition of `T2` is "(no cv) pointer to `void()`". U<sub>2</sub> is `void()`.

Because
- `T1` and `T2` are different,
- `T2` does match the pattern described in [[expr.const.cast] p6](https://eel.is/c++draft/expr.const.cast#6), and
- there is no qualification conversion from `void(*)()` to `const void*`,

converting from `const void*` to `void(*)()` does cast away constness, and `reinterpret_cast` is not allowed to do that.

**Comment by jensmaurer** [comment]
> Unless I'm wrong, the funny thing is that the conversion from const void * const * (yielding n = 2 from the decomposition) to void(*)() does not cast away constness because the qualification-decompositions don't have the same length, and so the second requirement of "casting away constness" is not satisfied.

The qualification-decomposition is not unique ("there is a... yielding n"), so n=1 is possible for your example.

Oh, and "object pointer type" includes "void*", but "pointer to object type" does not. See [basic.compound] p3 for the former.

So, what's left here?  The wording clearly establishes that we have a "casting away constness" situation here (note that wording clarity in this area was improved not too long ago), and the existing wording already allows casting from/to "void*".

Oh, and "possibly with different cv-qualification" just means "shall yield the original pointer value" (which is a requirement on the implementation) also applies when converting back to a type similar to the original type.

**Comment by Eisenwave** [comment]
> So, what's left here?

Submitting a GCC bug report at this point.

To be honest, I don't think it makes any sense for `const void*` to function pointers being disallowed, but that also seems to be less of a defect and more of an inconvenient restriction, which needs a paper to go through EWG.
