### ISSUE TITLE
CWG2604 [temp.expl.spec] Attributes and function template specializations

### ISSUE THREAD

**Issue by AaronBallman** [cplusplus/CWG#68]
Full name of submitter (unless configured in github; will be published with the issue): Aaron Ballman

Reference (section label): [temp.expl.spec]

Link to reflector thread (if any): https://lists.isocpp.org/core/2022/06/12840.php

Issue description:
It's unclear whether a function template specialization "inherits" the attributes written on the primary function template, or whether the specialization has to repeat the attributes. For example:
```
template <typename Ty>
[[noreturn]] void func(Ty);

template <>
void func<int>(int) {
  // Warning about returning from a noreturn function or not?
}
```
Implementations diverge on this point: https://godbolt.org/z/o6bT5cn8M

Similarly, it's not clear about attributes written on the parameters of the primary function template. For example:
```
template <typename Ty>
void func([[maybe_unused]] int i);

template <>
void func<int>(int i) {
  // i is not used, should it be warned on or not?
}
```
Implementations diverge on this point as well: https://godbolt.org/z/1eTrTorn1

Suggested resolution:
I think attributes should be handled the same as the `inline` and `constexpr` specifiers, as in [temp.expl.spec]p13, for attributes written in any position on the primary function template. By not automatically "inheriting" attributes from the primary template, we allow the specialization to convey more information to the compiler specific to that specialization. If we inherited attributes, users would have no way to "remove" a problematic attribute in a specialization.

Guidance on (vendor-specific) attributes which impact the type of the function (like calling conventions) would also be appreciated, as that seems like a different situation than declaration attributes.

**Comment by jensmaurer** [comment]
CWG2604
