### ISSUE TITLE
CWG2600 [expr.new] p2 should cover placeholder for a deduced class type

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#69]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[expr.new] p2 says
> If a **[placeholder type](https://eel.is/c++draft/dcl.spec.auto)** appears in the [type-specifier-seq](https://eel.is/c++draft/dcl.type.general#nt:type-specifier-seq) of a [new-type-id](https://eel.is/c++draft/expr.new#nt:new-type-id) or [type-id](https://eel.is/c++draft/dcl.name#nt:type-id) of a [new-expression](https://eel.is/c++draft/expr.new#nt:new-expression), the allocated type is deduced as follows: Let init be the [new-initializer](https://eel.is/c++draft/expr.new#nt:new-initializer), if any, and T be the [new-type-id](https://eel.is/c++draft/expr.new#nt:new-type-id) or [type-id](https://eel.is/c++draft/dcl.name#nt:type-id) of the [new-expression](https://eel.is/c++draft/expr.new#nt:new-expression), then the allocated type is the type deduced for the variable x in the invented declaration ([[dcl.spec.auto]](https://eel.is/c++draft/dcl.spec.auto)):

The cross-reference to **placeholder type** that only refers to [dcl.spec.auto], however, according to the example after the rule, a placeholder for a deduced class type should be also covered by this rule. 

[dcl.spec.auto.general] p1 explicitly says
> A *placeholder-type-specifier* designates a **placeholder type** that will be replaced later by deduction from an initializer.

However, [dcl.type.class.deduct] does not say a placeholder for a deduced class type designates a **placeholder type**.

**Comment by jensmaurer** [comment]
I've made that a drive-by fix in the suggested resolution for CWG2600.
