### ISSUE TITLE
CWG2605 [class.prop] Implicit-lifetime aggregates

### ISSUE THREAD

**Issue by opensdh** [cplusplus/CWG#70]
Reference (section label): [class.prop]

Link to reflector thread (if any): an [editorial issue](https://github.com/cplusplus/draft/issues/5318#issuecomment-1049885482)

Issue description:

It doesn't make sense that _all_ aggregates should be implicit-lifetime types, since
```c++
struct X {
  Y i;
  ~X();
};
```
is an aggregate and yet (regardless of the type `Y`) doesn't satisfy ["Destroying an instance of the type runs no code"](https://www.open-std.org/JTC1/SC22/WG21/docs/papers/2020/p0593r6.html#affected-types).

Suggested resolution:

Require a trivial, non-deleted destructor for all class types.

**Comment by jensmaurer** [comment]
Since the implicit-lifetime rules are only concerned with the object itself, but not with any of the subobjects, maybe we should allow non-trivial destructors in subobjects.

I've put words into CWG2605 to make that happen; please have a look.

**Comment by opensdh** [comment]
Right: you wrote what I should have written, since (with aggregates alone!) we can distinguish these.  Thanks.
