### ISSUE TITLE
[expr.prim.lambda.capture] An identifier that is a simple-capture is not an expression

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#73]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

Consider this example:
````cpp
int main(){
   int a = 0;
   auto f = [](){
    auto f2 =  [a](){}; // #1
   };
}
````
[basic.def.odr] p5 says
> A variable is named by an expression if the expression is an id-expression that denotes it.  A variable x ... **expression E** is **odr-used by E**

[expr.prim.lambda.capture] p7 says
> For the purposes of lambda capture, an expression potentially references local entities as follows:
>> - An **id-expression** that names a local entity potentially references that entity; 
>> - [...]
>> - A lambda-expression potentially references the local entities **named by its simple-captures**.

The grammar *simple-capture* specifies that `a` at `#1` is an identifier. There is no definition in the standard that says that a variable is named by an **identifier**. 

Furthermore, the above example is intended to be regulated by [basic.def.odr] p10
> A local entity is odr-usable in a scope if:
>> - [...]
>
> If a local entity is **odr-used** in a scope in which it is not odr-usable, the program is ill-formed.

However, whether a variable(local entity) is odr-used by an **expression** or not is defined in [basic.def.odr] p5. `a` at `#1` is an identifier, we can say that an *id-expression* might be an *identifier* but not the way around.  So whether an entity is odr-used by a non-expression(identifier) does not make sense. 

### Suggested resolution

Change all `identifiers` in *simple-capture* to **id-expression**, which is an expression. Change all `identifier`s in *init-capture* to *declarator-id*, which make [expr.prim.lambda.capture] p6 be clearer. 
> ... explicitly captures a variable of the form “auto init-capture ;”

Change [expr.prim.lambda.capture] p4 to
> The ~identifier~ *id-expression* in a simple-capture shall denote a local entity ([basic.lookup.unqual], [basic.pre]). The simple-captures this and * this denote the local entity *this.  

Change [basic.def.odr] p10
> the intervening scope is the function parameter scope of a lambda-expression that has a simple-capture ~naming~ **denoting** the entity or has a capture-default, and the block scope of the lambda-expression is also an intervening scope.

Since we use "denote" in [expr.prim.lambda.capture] p4, the verb should be consistently used in  [basic.def.odr] p10. 

After this modification, `a` at `#1` is clear to be an expression that names the variable, and that expression odr-uses the variable at `#1` that is not odr-usable.

**Comment by xmh0511** [comment]
> expr.prim.lambda.capture] p7 says that the lambda-expression f2 potentially references the local entity a.
>
>All further talks about "expression" should be read as referring to the lambda-expression for the capture case

That's the issue here. We just define whether an entity(i.e. a variable) is odr-used by an *id-expression*. In this case, the expression referring to the local entity `a` is the lambda expression, so, whether the lambda expression at `#2` odr-uses the entity? This is unclear, but the major implementations require the entity should be captured by the outer lambda expression.

**Comment by jensmaurer** [comment]
p7 says (after the bullets)

> If an expression potentially references a local entity within a scope in which it is odr-usable (6.3), and the expression would be potentially evaluated if the effect of any enclosing typeid expressions (7.6.1.8) were ignored, the entity is said to be implicitly captured by each intervening lambda-expression with an associated capture-default that does not explicitly capture it.

So, we have to find out whether `a` is odr-usable at the point where `f2` appears. (`f2` is obviously potentially-evaluated.)

This is [basic.def.odr] p10, in particular p10.2.2 seems to apply here.

We don't even get to the actual "odr-use" items that talk about _id-expression_.

**Comment by xmh0511** [comment]
> p7 says (after the bullets)

This part just defines what **implicitly capture** means. If the local entity is not odr-usable in the scope, at best, we say the local entity is not **implicitly captured** by the intervening lambda-expressions. We even can use the value of a local entity if we do not odr-use it. I mean, if we didn't odr-use the local entity that is not captured, the program shouldn't be ill-formed. p7 defines nothing if the local entity is not odr-usable, I think.

**Comment by xmh0511** [comment]
> p7 is exactly what applies to your initial example; a is odr-usable and is implicitly captured by f.

My initial example is 
````cpp
int main(){
   int a = 0;  // #0
   auto f = [](){  // #1 start
    auto f2 =  [a](){}; // #2
   };  // #1 end
}
````
According to [basic.def.odr] p10, the intervening scopes between `#2` and `#0` contain the parameter scope of `f`, `f` **does not** have the simple-capture naming `a` nor has a capture-default, how could `a` be odr-usable in the (block)scope introduced by the compound-statement of `f`? Since `a` is not usable in the block scope, p7 defines nothing about it.

**Comment by jensmaurer** [comment]
Thanks for the additional information.

So, we're looking for rationale why the program is ill-formed.

I think we want [basic.def.odr] p10 to trigger: "If a local entity is odr-used in a scope in which it is not odr-usable, the program is ill-formed."

And [expr.prim.lambda.capture] p8 says: "An entity captured by a lambda-expression is odr-used (6.3) by the lambda-expression."

So, `a` is odr-used inside `f`, but isn't odr-usable there (because "f" doesn't have a capture-default).

**Comment by xmh0511** [comment]
Oh, thanks so much. It seems that I omitted the important rule [expr.prim.lambda.capture] p8, which designates how the entity is **odr-used** by the lambda-expression.
