### ISSUE TITLE
CWG2608 [temp.arg.explicit] Allowing ommiting empty template argument list for default arguments

### ISSUE THREAD

**Issue by ranaanoop** [cplusplus/CWG#79]
Full name of submitter (unless configured in github; will be published with the issue): Anoop Rana

Reference (section label): [temp.arg.explicit]

Link to reflector thread (if any): https://github.com/cplusplus/draft/pull/5512

Issue description: Currently the wording in [temp.arg.explicit] does not allow for empty `<>`  to be omitted  when all of the template arguments can be obtained from the default arguments. This was also discussed in this [pull request](https://github.com/cplusplus/draft/pull/5512). In particular, [temp.arg.explicit] currently states:

> Trailing template arguments that can be deduced or obtained from default template-arguments may be omitted from the list of explicit template-arguments.A trailing template parameter pack ([temp.variadic]) not otherwise deduced will be deduced as an empty sequence of template arguments. **If all of the template arguments can be deduced, they may all be omitted; in this case, the empty template argument list <> itself may also be omitted.** 

Note in the above highlighted statement it says that when all of the template arguments can be deduced then they may all be omitted and in this case the empty `<>` itself may also be omitted. **This is an issue because** it does not mention that we can also omit the empty `<>` when all of the template arguments can be obtained from the default template arguments. Since deducing arguments and using default values are two different things, there should be a separate mention of the latter.

This also means that according to the current wording(sentence 3 highlighted above) the following should be invalid:

```
template<typename T = int>
void func()
{

}
int main()
{
    func(); //this is invalid according to the current wording(the highlighted part above in particular)
}
```

But we know that the above is not actually invalid and so there should be changes made to the sentence 3 highlighted above to include the case of default template arguments.

<h3>Suggested resolution:</h3>

We can resolve this by changing [temp.arg.explicit] to:

> Trailing template arguments that can be deduced or obtained from default template-arguments may be omitted from the list of explicit template-arguments. A trailing template parameter pack ([temp.variadic]) not otherwise deduced will be deduced as an empty sequence of template arguments. If all of the template arguments can be deduced **or obtained from default template arguments**, they may all be omitted; in this case, the empty template argument list <> itself may also be omitted.

The added part has been highlighted in bold in the above statement. 

<h4>Consequence</h4>

After the proposed resolution(above), the example given above is valid:

```
template<typename T = int>
void func()
{

}
int main()
{
    func(); //valid after the proposed resolution
}
```

**Comment by jensmaurer** [comment]
CWG2608
