### ISSUE TITLE
CWG2544 [basic.compound] Address represented by a pointer past the end of an object may be incorrectly specified

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/CWG#8]
Full name of submitter (unless configured in github; will be published with the issue): Jiang An

Reference (section label): [basic.compound]

Link to reflector thread (if any):

Issue description:

On common (if not all) implementations, pointer arithmetic doesn't know whether a pointed-to object is potentially-overlapping, so `p + 1` would give the result as if `*p` is non-potentially-overlapping. Assuming
- size and alignment of `int` are both 4,
- size and alignment of `short` are both 2,
- the implementation uses Itanium C++ ABI,

the following code should not compile according to [basic.compound]/3, but accepted by both gcc and clang.

```C++
struct Foo {
    Foo() = default; // Considering Itanium C++ ABI
    int x;
    short y;
};
struct Bar {
    [[no_unique_address]] Foo f;
    short z;
};

Bar bar{};
static_assert(sizeof(Foo) == sizeof(Bar));
static_assert(static_cast<void*>(&bar.f + 1) != static_cast<void*>(&bar.z));
static_assert(static_cast<void*>(&bar.f + 1) == static_cast<void*>(&bar.z + 1));
```
In this case, `bar.f` is a potentially-overlapping subobject and only occupies the first 6 bytes in `bar`. According to [basic.compound]/3, `&bar.f + 1` represents the address of the byte at offset 6, same as the first byte of `bar.z`, so `static_cast<void*>(&bar.f + 1)` compares equal to `static_cast<void*>(&bar.z)` according to [expr.eq]/(3.2). But compilers don't think so.

On the other hand, the address represented by a pointer past the end of a zero-sized object seems underspecified.
And if `p` points to a non-contiguous object (e.g. a base subobject that contains a virtual base subobject), `p + 1` may have some unwanted (but should still be defined) result.

----
Suggested resolution:

This proposed resolution also addresses CWG2324. It also supersedes P1945, and defines a core item _empty class_, which is intendedly used for LWG2358.

Change [intro.object]/1 as indicated:

> ... An object **potentially** occupies a region of storage in its period of construction ...

Add a bullet between [intro.object]/7 and [intro.object]/8:

> **The _size_ of a non-bit-field object is the number of bytes of storage potentially occupied by the object, which is greater than zero.**

[Editorial notes: an object created by `new T [0]` makes current rules contradictory, this should be handled in CWG2532, etc..]

Change [intro.object]/8 as indicated:

> ~An object has nonzero size if it~
> - ~is not a potentially-overlapping subobject, or~
> - ~is not of class type, or~
> - ~is of a class type with virtual member functions or virtual base classes, or~
> - ~has subobjects of nonzero size or unnamed bit-fields of nonzero length.~
> 
> **A non-bit-field object shall occupy contiguous bytes of storage, unless it is a base class subobject that contains a virtual class base subobject.** **The circumstances under which a base class subobject that contains a virtual base class subobject potentially occupies contiguous bytes is implementation-defined.** **An object potentially occupies every byte that is potentially occupied in full or in part by any of its subobjects.** **The bytes of storage occupied by an object is also potentially occupied by the object.** **If a non-bit-field object is not a potentially-overlapping subobject, it occupies all bytes that it potentially occupies.** **Otherwise, if the non-bit-field object is of a type other than an empty class type ([class.prop]), it occupies nonzero bytes.** Otherwise, if the object is a base class subobject of a standard-layout class type with no non-static data members, it ~has zero size~ **occupies no bytes**. Otherwise, the circumstances under which the object ~has zero size~ **of an empty class type occupies no bytes** are implementation-defined. ~Unless it is a bit-field, an object with nonzero size shall occupy one or more bytes of storage, including~  **A non-bit-field object that occupies nonzero bytes occupies** every byte that is occupied in full or in part by any of its subobjects.  An object of trivially copyable or standard-layout type ([basic.types.general]) shall occupy contiguous bytes of storage.

[Editorial notes: the intent is that the potentially occupied bytes are exactly the bytes of object representation, but this should be handled in P1839.]
[Editorial notes: occupying contiguous bytes also means that middle paddings are not reusable. I don't know whether it is intended.]

Change [intro.object]/9 as indicated:

> Unless an object is a bit-field ~or a subobject of zero size~, the address of that object is the address of the first byte it **potentially** occupies. Two objects with overlapping lifetimes that are not bit-fields may have the same address if one is nested within the other, or if at least one is a subobject ~of zero size~ **that occupies no bytes** and they are of different types; otherwise, they have distinct addresses and occupy disjoint bytes of storage.
> [...]
> ~The address of a non-bit-field subobject of zero size is the address of an unspecified byte of storage occupied by the complete object of that subobject.~ **It is unspecified which bytes are potentially occupied by a non-bit-field subobject that occupies no bytes among the bytes occupied by the complete object of that subobject.**

Change [basic.compound]/3 as indicated:

> A value of a pointer type that is a pointer to ~or past the end of~ an object represents the address of the first byte in memory ([intro.memory]) **potentially** occupied by the object 36) ~or the first byte in memory after the end of the storage occupied by the object, respectively~. **A value of a pointer type that is a pointer past the end of the object represents the address of the first byte in the memory after the end of storage potentially occupied by the object if the object potentially occupies contiguous bytes of storage ([intro.object]), otherwise, it represents the address of an unspecified byte that is either occupied by the complete object of that object, or the first byte in the memory after the end of storage occupied by the complete object.**

Change footnote 36 as indicated:

> For an object that is not within its lifetime, this is the first byte in memory that it will **potentially** occupy or used to **potentially** occupy.

Change [expr.sizeof]/1 as indicated:

> The `sizeof` operator yields the ~number of bytes potentially occupied by a non-potentially-overlapping~ **the size of an** object of the type of its operand **([intro.object])**. ...

[Editorial notes: a non-potentially-overlapping of that type is not always creatable, e.g., the type may be an abstract class.]

Change footnote 63 as indicated, and associate it with the first sentence of [expr.sizeof]/1:

> The actual ~size of~ **number of bytes occupied by** a potentially-overlapping subobject can be less than the result of applying `sizeof` to the subobject, due to virtual base classes and less strict padding requirements on potentially-overlapping subobjects.

Delete these two sentences in [expr.sizeof]/2:

> ... ~When applied to a class, the result is the number of bytes in an object of that class including any padding required for placing objects of that type in an array.~ ~The result of applying `sizeof` to a potentially-overlapping subobject is the size of the type, not the size of the subobject.~ ...

[Editorial notes: these sentences become redundant.]

Change [expr.rel]/(4.2) as indicated:

> If two pointers point to different non-static data members of the same object, or to subobjects of such members, recursively, the pointer to the later declared member is required to compare greater provided neither member is a subobject ~of zero size~ **that occupies no bytes** and their class is not a union.

Change [class.pre]/6 as indicated:

> [Note 3: Complete objects of class type ~have nonzero size~ **occupy nonzero bytes**. Base class subobjects and members declared with the `no_­unique_address` attribute ([dcl.attr.nouniqueaddr]) are not so constrained. — end note]

Add a bullet between [class.prop]/8 and [class.prop]/9:

> **A class is an _empty class_ if it:**
> - **has no virtual member functions**,
> - **has no virtual base classes, and**
> - **has no unnamed bit-fields of nonzero length, and**
> - **has no non-static data members that are not of empty class types or not declared with the `no_unique_address` attribute, and**
> - **has no base classes other than empty classes.**
>
> **In addition to these rules, the circumstances under which a non-static data member makes the class not an empty class is implementation-defined.**

Change [class.mem.general]/20 as indicated:

> [Note 8 : Non-variant non-static data members ~of non-zero size~ **that occupy nonzero bytes** ([intro.object]) are allocated so that later members have higher addresses within a class object ([expr.rel]). ... — end note]

Change [class.derived.general]/7 as indicated:

> [Note 5: ... A base class subobject can ~be of zero size~ **occupy no bytes**; ... — end note]

[Editorial notes: the specification of `is_empty` in [meta.unary.prop] still uses "zero size". Once the resolution is accepted, we can just say "`T` is a non-union empty class type ([class.prop])."]

**Comment by jensmaurer** [comment]
It seems to me that your premise is wrong: It is explicitly unspecified whether a pointer to one-past a member compares equal to a pointer to another member, or not (there might be padding involved, or not). And I think we're rather explicit that sizeof yields the size of a complete object, not the size of the same type used as a subobject.

If you could state with more clarity why you think your example is required to be ill-formed (and thus needs a diagnostic), that would be helpful.

**Comment by frederick-vs-ja** [comment]
> It seems to me that your premise is wrong: It is explicitly unspecified whether a pointer to one-past a member compares equal to a pointer to another member, or not (there might be padding involved, or not).

I think the explicitly unspecified case is that two pointer values are associated with two difference complete objects ([[expr.eq]/(3.1)](https://eel.is/c++draft/expr.eq#3.1)), not are those represent address within (or one past the end of) the same complete object. Actually the result depends on the implementation, but it should be implementation-defined when the complete object is of a standard-layout class type, not unspecified.

Let me show a less confusing example. The following `static_assert`s also pass when compiled with gcc/clang.
```C++
static_assert(static_cast<void*>(&bar.f) == static_cast<void*>(&bar)); // required
static_assert(static_cast<void*>(&bar.f + 1) == static_cast<void*>(&bar + 1)); // ??
```

Even if Itanium ABI is not assumed, `bar.f` must occupy less bytes then `bar`, and given both `Foo` and `Bar` are standard-layout and trivially copyable classes, `bar.f` and `bar` must occupy contiguous bytes. As a result, "the first byte in memory after the end of the storage occupied by the `bar.f`" and "the first byte in memory after the end of the storage occupied by the `bar`" must be different bytes.
So `&bar.f + 1` and `&bar + 1` are currently required to represent addresses of different bytes (according to [basic.compound]/3), and as this is not the case of (3.1), so they are currently required to compare unequal when converted to `void*`.

> And I think we're rather explicit that sizeof yields the size of a complete object, not the size of the same type used as a subobject.

This part (resolution for CWG2324) is more like a wording only improvement. It's very confusing for me that the standard explicitly says that `sizeof(o)` is not equal to the size of `o` in some cases. I think it may be clearer to divorce "size" with "number of occupied bytes of storage".
On the other hand, it is currently underspecified where are the non-occupied bytes of a potentially-overlapping subobject (Do all `sizeof(o)` bytes exist? Can they be allocated outside of the complete object?). I want to make some clarification.

**Comment by languagelawyer** [comment]
> It seems to me that your premise is wrong: It is explicitly unspecified whether a pointer to one-past a member compares equal to a pointer to another member

It seems to me that you confuse complete and most derived objects

**Comment by languagelawyer** [comment]
@frederick-vs-ja 
> `static_assert(static_cast<void*>(&bar.f) == static_cast<void*>(&bar)); // required`

Why? 

> The address of a non-bit-field subobject of zero size is the address of an unspecified byte of storage occupied by the complete object of that subobject[.](https://timsong-cpp.github.io/cppwp/n4868/intro.object#9.sentence-3)

Which I think is meant to be read that a pointer to a subobject of zero size represents the address of an unspecified byte.

**Comment by frederick-vs-ja** [comment]
> Why?

`bar.f` is not an object of zero size, so it must has the same address of `bar` because it's the first member and `Bar` is a standard-layout type.

**Comment by languagelawyer** [comment]
I thought `[[no_unique_address]]` would make it zero-size, but it just makes it potentially-overlapping.
(Speaking of standard-layout, I think there was a CWG issue or just a discussion to make `[[no_unique_address]]` incompatible with standard-layout.)

**Comment by jensmaurer** [comment]
I agree; standard-layout ought to be incompatible with `[[no_unique_address]]`.  That's my take-away from this issue so far.

**Comment by frederick-vs-ja** [comment]
The proposed definition of empty class is changed as below to match MSVC, which currently ignores `[[no_unique_address]]`.

> **A class is an _empty class_ if it:**
> - **has no virtual member functions**,
> - **has no virtual base classes, and**
> - **has no unnamed bit-fields of nonzero length, and**
> - **has no non-static data members that are not of empty class types and declared with the `no_unique_address` attribute, and**
> - **has no base classes other than empty classes.**
>
> **In addition to these rules, the circumstances under which a non-static data member makes the class not an empty class are implementation-defined.**

**Comment by jensmaurer** [comment]
@frederick-vs-ja , sorry, I'm not seeing the difference vs. the original proposal. Please point me to them.

In any case, please note that `no_unique_address` is an attribute, and ignoring it entirely must not change a "good" program to an ill-formed or misbehaving one.

I note that this discussion is becoming a bit large for a core issue. I think there is one narrow question that can be treated as a core issue, namely standard-layout vs. `[[no_unique_address]]`.

Is there anything else of similar magnitude that needs fixing?

For the rest, please consider submitting a paper with rationale.

**Comment by frederick-vs-ja** [comment]
@jensmaurer 

> I think there is one narrow question that can be treated as a core issue, namely standard-layout vs. `[[no_unique_address]]`.

Oh... I think this question should be separated into another issue. The `Foo` and `Bar` are also trivially copyable classes which are also required to occupy contiguous bytes now, so whether `Bar` is standard-layout doesn't matter here.

> I'm not seeing the difference vs. the original proposal. Please point me to it.

In the original proposal, the definition of empty class was:

> A class is an empty class if it:
> - has no virtual member functions,
> - has no virtual base classes, and
> - has no unnamed bit-fields of nonzero length, and
> - given an object of the class type, the object has no subobjects other than potentially-overlapping subobjects of empty class types.

The former definition left no room for implementation-defined choice. And the revised definition allows that whether a class is empty depend on whether `[[no_unique_address]]` on a member is ignored.
IMO `is_empty` should reflect whether the implementation ignores `[[no_unique_address]]` and thus thinks such a member subobject is not potentially-overlapping, even if the standard say so, which is allowed by the revised definition, but not the original one (if the library wording is synchronously changed).

**Comment by jensmaurer** [comment]
intro.object p8:

> An object of trivially copyable or standard-layout type (6.8.1) shall occupy contiguous bytes of storage.

You're right; this says "or". "Trivially copyable" is sufficient to cause contiguous bytes of storage.

And I think the older definition did leave a choice, because "potentially-overlapping" depends on `no_unique_address`: "a non-static data member declared with the `no_unique_address` attribute"

**Comment by frederick-vs-ja** [comment]
I think whether `[[no_unique_address]]` is actually entirely ignorable should become another issue. The new definition of empty class doesn't depend on the potentially implementation-dependent "potentially-overlapping" property.

**Comment by jensmaurer** [comment]
Well, it's definitely the intent that `no_unique_address` is entirely ignorable.

If the older definition is equivalent to the newer one of "is empty class", why do we need to change anything?

Can someone remind me of the issue we're trying to solve here, in succinct words?

**Comment by frederick-vs-ja** [comment]
Oh... I wanted to solve 3 related but different issues:
1. pointer arithmetic (`p + 1`) on a pointer to a potentially-overlapping subobject, or a non-contiguous subobject is not correctly specified in [basic.compound]/3.
2. CWG2324, divorcing size with number of occupied bytes, which I think should be resolved together with the aforementioned issue.
3. LWG2358, for which I think a suitable resolution would add a core item.

**Comment by languagelawyer** [comment]
> pointer arithmetic (`p + 1`) on a pointer to a potentially-overlapping subobject, or a non-contiguous subobject is not correctly specified

Some time ago in private communication with R. Smith we agreed that the following is possible in some inhumane implementation:
```c++
int i, j;
static_assert(&i != &j); // required
static_assert(&i + 1 != &j + 1); // can fail, NOT required
```
i.e. for different complete objects, even though their past-the-end pointer values are different values, they can represent the same address.
However, I also wanted past-the-end byte be same for any object (including subobjects), whilst R. Smith was favoring the model where the address represented by a past-the-end pointer value respects subobject's placement inside its parent object.

I still think if we adopt the model where what is «the first byte in memory after the end of the storage occupied by the object» is **defined** as what implementation represents by past-the-end pointer (`p + 1`), in contrast to the model where it can be **derived** which address it should be, this would trivially resolve this issue.

**Comment by jensmaurer** [comment]
For item 1, we might also argue that several objects occupy the same storage.
For item 2, this is an existing core issue that I'm not too worried about; we normatively define "object of zero size" as a term of art, and that might be different from what `sizeof` returns on such an object. Some clarification might be helpful, though.
For item 3, LWG limits this to non-union class types, ignoring empty unions. That's at least surprising from a CWG perspective, and thus (for this particular definition), I wouldn't be happy providing a CWG definition. Maybe asking LWG for the intended use-case would help; the issue seems silent on that.

**Comment by languagelawyer** [comment]
> For item 1, we might also argue that several objects occupy the same storage.

And replacing a member subobject would kill unrelated base class or another member subobject because the first one happened to share storage with the other's padding?

**Comment by jensmaurer** [comment]
That is a rather realistic option if we e.g. placement-new over the member subobject. We also prohibit memcpy on potentially-overlapping subobjects, for example: [basic.types.general] p2

**Comment by jensmaurer** [comment]
CWG2544

**Comment by zygoloid** [comment]
For the suggested wording in the core issue, I think we also should handle the case of objects of zero size:

> A value of a pointer type that is a pointer to <del>or past the end of</del> an object represents the address of <del>the first byte in memory (6.7.1 [intro.memory]) occupied by</del> the object <ins>as specified in [intro.object]</ins>

... referring to the definition of the address of an object in [intro.object]/9:

> Unless an object is a bit-field or a subobject of zero size, the address of that object is the address of the first byte it occupies. [...] The address of a non-bit-field subobject of zero size is the address of an unspecified byte of storage occupied by the complete object of that subobject.

Though this is a bit awkward from a phrasing perpsective: we're joining the terms of art "represents the address"(which we're *defining* here) and "address of an object" and only using the word "address" once. The current proposed wording change also splits the definition of the term "represents the address" in an awkward way. Maybe a larger-scale rephrasing would help:

> A value _V_ of pointer type _represents the address_ _A_ as follows:
> * If _V_ is a pointer to an object, _A_ is the address of the object as specified in [intro.object].[Footnote]
> * If _V_ is a pointer past the end of an object that is not a potentially-overlapping subobject, _A_ is the address of the first byte in memory after the end of the storage occupied by the object.
> * If _V_ is a pointer past the end of a potentially-overlapping subobject, _A_ is an implementation-defined address within the complete object.
> * If _V_ is a null pointer value or an invalid pointer value, _V_ does not represent an address.

**Comment by jensmaurer** [comment]
@zygoloid, sounds mostly good. I'm wondering whether "implementation-defined address" is what we want for potentially-overlapping subobjects. This seems to mean that an implementation has to document the choice here. Maybe "unspecified" is better?

**Comment by frederick-vs-ja** [comment]
@zygoloid 
> If _V_ is a pointer past the end of a potentially-overlapping subobject, _A_ is an implementation-defined address within the complete object.

I think we should also allow _A_ allow to be "the first byte in memory after the end of the storage occupied by the complete object" in this case. Otherwise, `static_assert(static_cast<void*>(&bar.f + 1) == static_cast<void*>(&bar + 1));` in [this example](https://github.com/cplusplus/CWG/issues/8#issue-1144981663) may be still disallowed.

**Comment by jensmaurer** [comment]
Agreed, a potentially-overlapping subobject should allow all outcomes of a subobject that is not potentially-overlapping.

**Comment by t3nsor** [comment]
@jensmaurer The minutes from the 2022 Kona meeting appear to reflect that CWG decided that the past-the-end pointer should always be sizeof(T) bytes after the beginning of a T object, even if it's a potentially-overlapping subobject, but the log note I would expect to see in the issue description that indicates this direction is missing.

**Comment by jensmaurer** [comment]
Fixed.
