### ISSUE TITLE
[class.mem] Whether a class type is complete at a point is underspecified

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#81]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

For the cast that is not within the complete-class contexts, [class.mem] p8 just says
> A class is considered a completely-defined object type ([basic.types.general]) (or complete type) at the closing } of the class-specifier.

Consider this example:
````cpp
// file a
export module A;
export class X{};

// file b
import A;
X x;  // is `X` complete at this point? 
````
It is not clear whether [class.mem] p8 suitable for this case since there is no lexical *class-specifier* in the translation unit `b`. Even though [basic.def.odr] p13 says
> A definition of a class shall be reachable in every context in which the class is used in a way that requires the class type to be complete.

This rule just imposes the requirement but does not define whether a class type is complete at one point. In this document, many rules require a class type shall be complete, such as in [expr]

### Suggested resolution

Change [class.mem] p8 
> A class is considered a completely-defined object type ([basic.types.general]) (or complete type) if its *class-specifier* is reachable. The class is regarded as complete within its complete-class contexts; otherwise it is regarded as incomplete within its own class member-specification.

The modification could clarify the module import case.

**Comment by jensmaurer** [comment]
Why is [basic.def.odr] p13 not enough?

It's always either
- it's irrelevant whether the class is complete (e.g. forming a pointer to class type)
- if the class is not complete, the construct is ill-formed (e.g. defining a variable of class type)

It seems "a definition shall be reachable if the use requires a complete class type" is good enough for these.

**Comment by xmh0511** [comment]
Because it is a bit subtle here. [basic.types.general] p6 says
> A class type (such as “class X”) can be incomplete at one point in a translation unit and complete later on; the type “class X” is the same type at both points. 

So, at which point the class type is considered to be incomplete, and at which point it is considered to be complete? It is clear if the point `P` and the class-specifier appear in the same translation unit, according to [class.mem] p8. However, it is unclear if they appear in different module units. 

***
It's indeed that we only concern with two things regarding whether the class is complete at the program point `P` 
> 1. The context where the class type requires to be complete, which is regulated by [basic.def.odr] p13.
> 2. The lookup result for the class members, which is regulated by [basic.lookup.general] p2   

In general, it seems that we do not need to care whether a class type is complete or incomplete at the point `P`.

**Comment by jensmaurer** [comment]
So, there's no defect here.
