### ISSUE TITLE
CWG2619 [dcl.init.aggr] "{ D }" is not a designated-initializer-list

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#93]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

Consider this [example](https://godbolt.org/z/5evGo6h49)
````cpp
struct A{
    explicit A(int){}
};
struct B{
    A a;
};
struct C{
    union{
      A a;
    };
};
int main(){
    B b = {.a{0}};  // #1
    C c = {.a{0}};  // #2
}
````
Clang accepts both while GCC rejects both. For `#1`, the relevant rule is 
> Otherwise, the element is copy-initialized from the corresponding initializer-clause or is **initialized** with the brace-or-equal-initializer of the corresponding designated-initializer-clause. If that initializer is of the form assignment-expression or = assignment-expression and a narrowing conversion ([dcl.init.list]) is required to convert the expression, the program is ill-formed.

The verb is "initialized", which can arguably say it's not clear which kind of initialization applies. Presumably, it is determined by the form of brace-or-equal-initializer, in other words, if the *brace-or-equal-initializer* has the form `= initializer-clause`, that is copy-initialization, and direct-initialization if it is `braced-init-list`. At `#1`, the explicit initialized element is `B::a` and the "brace-or-equal-initializer of the corresponding designated-initializer-clause" is `{0}`, thus clang seems to be right. 

For `#2`, the relevant rule is
> If the element is an anonymous union member and the initializer list is a brace-enclosed designated-initializer-list, the element is **initialized** by the designated-initializer-list { D }, where D is the designated-initializer-clause naming a member of the anonymous union member. There shall be only one such designated-initializer-clause.

The verb "initialized" is again used here. The *designated-initializer-clause* in this example is `.a{0}`, thus the new synthesized initializer is `{.a{0}}` and the corresponding explicitly initialized element is the anonymous union member, which is still an aggregate initialization, whose process is similar to the above. Clang seems to be right again. 

Incidentally, in the second rule, `{D}` shouldn't be called *designated-initializer-list*, they cannot match on grammar. `{D}` should be called *braced-init-list*. 

### Suggested resolution
Change [dcl.init.aggr] p4.1
> If the element is an anonymous union member and the initializer list is a brace-enclosed designated-initializer-list, the element is **copy-initialized** by the ~designated-initializer-list~  *braced-init-list* `{ D }`, where D is the designated-initializer-clause naming a member of the anonymous union member. There shall be only one such designated-initializer-clause.

Change [dcl.init.aggr] p4.2
> Otherwise, the element is copy-initialized from the corresponding initializer-clause, or is copy-initialized or direct-initialized with the brace-or-equal-initializer of the corresponding designated-initializer-clause, **determined by the form of the *brace-or-equal-initializer***. If that initializer is of the form assignment-expression or = assignment-expression and a narrowing conversion ([dcl.init.list]) is required to convert the expression, the program is ill-formed.

**Comment by jensmaurer** [comment]
This is not the forum to report gcc bugs; please use their bug tracker instead.

The wording seems clear as written, and your reading above seems correct. In particular, the syntactic form of initializer determines which kind of initialization is done; we don't have to repeat that over and over again throughout the wording.

**Comment by xmh0511** [comment]
@jensmaurer  What about saying that `{ D }` is a *designated-initializer-list* in the original rule? Anyway, *designated-initializer-list* cannot match `{...}`. Moreover, 
> the element is initialized by the designated-initializer-list { D }

What is the kind of initialization with the initializer `{D}`?

**Comment by xmh0511** [comment]
> direct-list-initialization

If we don't explicitly say the initialization is direct-list-initialization, I thought it was copy-list-initialization, my reason is [dcl.init.general p14
> The initialization that occurs, ..., aggregate member initialization, is called copy-initialization.

Since we just say the anonymous union member, which is an aggregate member, is **initialized** from `{ D }`. If we didn't explicitly specify what kind of the initialization is, the other rule such as p14 will apply.

**Comment by xmh0511** [comment]
As I can figure out, copy or direct initialization doesn't matter for anonymous union members here, since it is an aggregate and cannot have any constructor, thus the initialization for the member can only be purely aggregate initialization.

***
@jensmaurer  However, to a certain degree, I think GCC reports errors for that two cases are reasonable. The original initializer for the aggregate elements are *designated-initializer-clause*s, [dcl.init.general] p15 says
> The initialization that occurs
>> - for an ***initializer*** that is a parenthesized expression-list or a braced-init-list
>
> is called direct-initialization.

Note the italic *initializer*, which directly refers to the initializer in the init-declarator. Apparently, the *braced-init-list* in the first bullet does not refer to the one in *designated-initializer-clause*. 

Thus, only [dcl.init.general] p14 can apply to such cases
> The initialization that occurs in, ..., **aggregate member initialization**, is **called copy-initialization**.

Whether the initialization for `B::a` or `C::a`, they are so-called **aggregate member initialization**. This is the divergence between GCC and Clang.

**Comment by jensmaurer** [comment]
CWG2619
