### ISSUE TITLE
[intro.object] The start of the region of storge

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/CWG#98]
Full name of submitter (unless configured in github; will be published with the issue): Jim X

[intro.object] p11 says
> These operations select one of the implicitly-created objects **whose address is the address of the start of the region of storage**, and produce a pointer value that points to that object 

Consider a simple example
````cpp
int* ptr = (int*)malloc(sizeof(int)*12);  // #1
````
[intro.object] p11 imposes the requirement that the **address of the object** must be the **start** of the region of storage. 

[c.malloc] p4 says
> These functions implicitly create objects ([intro.object]) **in the returned region of storage** and return a pointer to a suitable created object.

This provision didn't clearly say these objects are created at the start of the region of storage. It just says the pointer would point to the created object. They don't have the same meaning. "in the region" means the operation can create the object anywhere in the region as long as the object is not outside of the region, which means the object is not necessary to be created at the start of the region. 

In the above case, the created `int` object may locate at the address offset 2 times of `sizeof(int)` from the start of the region of storage, as per [c.malloc] p4. 

Furthermore, the operation `malloc` that can implicitly create objects also says
> The functions memcpy and memmove are signal-safe. Both functions implicitly create objects ([intro.object]) **in the destination region of storage** immediately prior to copying the sequence of characters to the destination.

As well, it just says create these objects **in** the destination region instead of saying create these objects at the start of the region. 

It makes whether the address of the object that is created by these operations is the start of the region of storage unclear. 

### Suggested resolution

Clearly say these operations that can implicitly create objects create objects at the start of the region of storage. This is consistent with the requirement of [intro.object] p11. For example

Change [intro.object] p13
> An operation that begins the lifetime of an array of char, unsigned char, or std​::​byte implicitly creates objects ~within~ at the start of the region of storage occupied by the array.
>
> Any implicit or explicit invocation of a function named operator new or operator new[] implicitly creates objects ~in~ at the start of the returned region of storage and returns a pointer to a suitable created object.

[c.malloc] p4
> These functions implicitly create objects ([intro.object]) ~in~ at the start of the returned region of storage and return a pointer to a suitable created object. 

change [cstring.syn] p3
> Both functions implicitly create objects ([intro.object]) ~in~ at the start of the destination region of storage immediately prior to copying the sequence of characters to the destination.

[intro.object] p11 
> These operations select one of the implicitly-created objects ~whose address~ that is created at ~the address of~ the start of the region of storage, and produce a pointer value that points to that object

**Comment by languagelawyer** [comment]
> This provision didn't clearly say these objects are created at the start of the region of storage

Why it should?

>  "in the region" means the operation can create the object anywhere in the region as long as the object is not outside of the region, which means the object is not necessary to be created at the start of the region.

And it is intended.

> In the above case, the created int object may locate at the address offset 2 times of sizeof(int) from the start of the region of storage, as per [c.malloc] p4.

No, it can not. `malloc` identifies itself as producing a pointer to a suitable created object. All operations which do so are constrained by [intro.object]/11 to produce a pointer representing the address of the beginning of the storage.

> It makes whether the address of the object that is created by these operations is the start of the region of storage unclear.

It is clear that they can be created anywhere.

> Suggested resolution

Completely against the intent.

**Comment by jensmaurer** [comment]
I'm not seeing a defect here. `malloc` implicitly creates objects (they're all over the place in the malloced memory) and then takes those that happen to be at the start of the memory to select a "suitable created object" to return a pointer to.

(All of these are Heisenberg objects; they only come to be if the surrounding program is constructed in a way that observes their presence.)

**Comment by xmh0511** [comment]
````cpp
int* ptr = (int*)malloc(sizeof(int)*12);
*ptr = 1;
````
Which provision says the address of `ptr` is the start of the region? [c.malloc] p4 only say the returned value is a point to a suitable object. It didn't say the address of the suitable object is the address of the start of the region.

**Comment by languagelawyer** [comment]
> Which provision says the address of `ptr` is the start of the region? [c.malloc] p4 only say the returned value is a pointer to a suitable object.

https://github.com/cplusplus/CWG/issues/98#issuecomment-1189863346:
> `malloc` identifies itself as producing a pointer to a suitable created object. All operations which do so are constrained by [intro.object]/11 to produce a pointer representing the address of the beginning of the storage.

**Comment by xmh0511** [comment]
> malloc identifies itself as producing a pointer to a suitable created object. 
Yes, it is explicitly specified in [c.malloc] p4

> All operations which do so are constrained by [intro.object]/11 to produce a pointer representing the address of the beginning of the storage. 

That's our divergence here. I construe [intro.object]/11 as
> If the address of the implicitly created object is the address of the start of the region, the operations will produce a pointer value that represents the address of that object. 

In other words, the operations won't produce a pointer to point to the implicitly created object whose address **is not the start of the region**.

You construe  [intro.object]/11 as
> These operations select one of the implicitly-created objects and produce a pointer value that points to that object where the pointer value represents the address of the start of the region of storage, if that value would result in the program having defined behavior.

The difference is I think "whose address is the start of the region" is a condition while you think it is a statement.

**Comment by xmh0511** [comment]
@jensmaurer 
> then takes those that happen to be at the start of the memory to select a "suitable created object" to return a pointer to.

That is the issue here. which implicitly created object whose address happens to be at the start of the memory? It is not specified in the relevant subclause of the operations.

**Comment by languagelawyer** [comment]
> which implicitly created object whose address happens to be at the start of the memory?

That, producing a pointer to which would give the program defined behavior.

**Comment by xmh0511** [comment]
> That, producing a pointer to which would give the program defined behavior.

According to [intro.object]/11,  in order to be eligible to be a suitable created object, the address of the implicitly created objects must be the address of the start of the region. However, the operation didn't say all implicitly created objects would be located at the start of the region.  

````
*ptr = 1;
````
This is well-defined if and only if the pointer points to an object of type `int`, which is a suitable created object. However, how are you sure that the address of the object of type `int` is the start of the region?

**Comment by xmh0511** [comment]
Actually, the concern could be simplified into two sentence
> 1. The person in the group whose card is blue will be the chair of the group
>2. The person in the group will be the chair of the group if the *condition* is true, thus the person will have a blue card. 

They are totally different meanings. [intro.object]/11 uses the first utterance while it wants to express the second meaning.

**Comment by languagelawyer** [comment]
> However, the operation didn't say all implicitly created objects would be located at the start of the region.

Why all implicitly-created objects have to be created at the start of the storage?

> This is well-defined if and only if the pointer points to an object of type `int`, which is a suitable created object. However, how are you sure that the address of the object of type `int` is the start of the region?

Because otherwise this won't be well-defined.

> I think the intent is we consider one of the implicitly created objects as a suitable created object, and if such consideration would make the program well-defined, then the object so considered will have the address of the start of the region.

The intent is that if program requires an implicitly-created object at the start of the storage to have defined behavior, and it is possible, such object will be created and the pointer to it will be produced.

**Comment by xmh0511** [comment]
> Why all implicitly-created objects have to be created at the start of the storage?

I meant they are all possible to be located at the start of the region, which is similar to “Schrödinger’s Cat”. Once a suitable created object is observed, the superposition will be collapsed to the unique state.

> The intent is that if program requires an implicitly-created object at the start of the storage to have defined behavior, and it is possible, such object will be created and the pointer to it will be produced.

The exact concern is that this opinion is not well conveyed through the current wording.

**Comment by xmh0511** [comment]
> [intro.object]/10 is pretty clear that objects which would give the program defined behavior are implicitly created, if possible.

Please see https://github.com/cplusplus/CWG/issues/98#issuecomment-1189921582. Do you think they have the same meaning?

**Comment by languagelawyer** [comment]
I'm bad at analogies. What I see that [intro.object]/10 expresses the intent that
> if program requires an implicitly-created object at the start of the storage to have defined behavior, and it is possible, such object will be created

well enough.

**Comment by xmh0511** [comment]
> if program requires an implicitly-created object at the start of the storage to have defined behavior, and it is possible, such object **will** be created

I don't agree, the operation of creating objects happens before producing the pointer value, see [intro.object]/11
> **after** implicitly creating objects within a specified region of storage

Note the emphasized "after".

**Comment by languagelawyer** [comment]
I don't get what are you disagree with and  what it has to do with "will" vs. "after".

**Comment by xmh0511** [comment]
> Further, **after implicitly creating objects within a specified region of storage**, some operations are described as producing a pointer to a suitable created object. 

It means, that producing a pointer to a suitable created object is after all implicitly created objects are done. It does not mean we first select a suitable created object and then create the object at the start of the region.

**Comment by languagelawyer** [comment]
> It means, that producing a pointer to a suitable created object is after all implicitly created objects are done.

All "uses" of implicitly-created objects [can] only happen after their creation, I think this is obvious.

> It does not mean we first select a suitable created object and then create 

Ofc. How is it even possible to first select something which does not exist yet?

**Comment by xmh0511** [comment]
So, the intent should be the operations implicitly create objects in the specified region, and then the operations select one of them as a suitable created object if the selection could make the program well-defined. The address of the so-selected suitable created object is the address of the start of the region. This would be clear if we so say.

**Comment by languagelawyer** [comment]
> the intent should be the operations implicitly create objects in the specified region, and then the operations select one of them as a suitable created object if the selection could make the program well-defined.

This exactly what [intro.object]/10 /11 say. 

> The address of the so-selected suitable created object is the address of the start of the region

This is what /11 says.

**Comment by xmh0511** [comment]
> > the intent should be the operations implicitly create objects in the specified region, and then the operations select one of them as a suitable created object if the selection could make the program well-defined.
> 
> This exactly what [intro.object]/10 /11 say.
> 
> > The address of the so-selected suitable created object is the address of the start of the region
> 
> This is what /11 says.

Again, when you say a stuff whose `XXX` property is `YYY`, it means we impose the requirement `YYY` on the stuff's `XXX`. In other words, any stuff whose `XXX` is not `YYY` is not within our extent of consideration. 

Back to [intro.object], it says that an object whose address is `YYY` is considered as a suitable created object if `Condition` is true. It didn't say an object that can be considered a suitable created object will have its address be `YYY` if `Condition` is true.

They are completely different meanings.
